linagora/tmail-flutter

- lib/features/home/presentation/home_controller.dart
- lib/features/login/domain/state/authentication_user_state.dart
- lib/features/login/domain/state/delete_credential_state.dart
- lib/features/login/domain/state/get_credential_state.dart
- lib/features/login/domain/usecases/delete_credential_interactor.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/session/data/datasource/session_datasource.dart
- lib/features/session/data/datasource_impl/session_datasource_impl.dart
- lib/features/session/data/network/session_api.dart
- lib/features/session/data/repository/session_repository_impl.dart
- lib/features/session/domain/repository/session_repository.dart
- lib/features/session/domain/state/get_session_state.dart
- lib/features/session/domain/usecases/get_session_interactor.dart
- lib/features/session/presentation/session_bindings.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/session/presentation/session_view.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/pages/app_pages.dart
- lib/main/routes/app_routes.dart
- model/pubspec.yaml
- pubspec.yaml
- Get session when logged success
> Get session for TMail

- lib/features/thread/presentation/thread_controller.dart
https://user-images.githubusercontent.com/80730648/132619767-6451bce5-50ae-43ac-8bdb-a54bbbfd4063.mp4
> TF-47 Reply email

- lib/features/composer/presentation/widgets/email_address_composer_widget_builder.dart
> Fix display two line for from email address

- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/top_bar_composer_widget_builder.dart
https://user-images.githubusercontent.com/80730648/132826080-7c94c71a-ee50-4c47-b79f-4979568c6204.mp4
> Fix some bug compose email

- bitrise.yml
The previous config didn't work.
> Fix set xcode build number step

- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/login/presentation/login_view.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/thread/presentation/thread_controller.dart
https://user-images.githubusercontent.com/80730648/133954606-feada33a-59a1-47f1-ba34-bf6cd528b957.mov
> Fix bug subject email deleted when compose email

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/features/composer/data/datasource/contact_datasource.dart
- lib/features/composer/data/datasource_impl/contact_datasource_impl.dart
- lib/features/composer/data/repository/contact_repository_impl.dart
- lib/features/composer/domain/model/contact_suggestion_source.dart
- lib/features/composer/domain/repository/contact_repository.dart
- lib/features/composer/domain/state/get_autocomplete_state.dart
- lib/features/composer/domain/state/get_device_contact_suggestions_state.dart
- lib/features/composer/domain/usecases/get_autocomplete_interactor.dart
- lib/features/composer/domain/usecases/get_autocomplete_with_device_contact_interactor.dart
- lib/features/composer/domain/usecases/get_device_contact_suggestions_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- model/lib/contact/contact.dart
- model/lib/contact/device_contact.dart
- model/lib/model.dart
- pubspec.yaml
https://user-images.githubusercontent.com/80730648/134137828-6d1d2425-7db9-4ef7-a8e1-16ba3c22284f.mov
> TF-60 Suggestion email from contact device

- README.md
This make the FAQ section easier to read
Preview: https://github.com/chibenwa/tmail-flutter/tree/chibenwa-patch-readme-1
> README Use collapsable sections

- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/composer/presentation/widgets/email_address_composer_widget_builder.dart
https://user-images.githubusercontent.com/80730648/135442238-cad55e90-af6f-4fc3-b91d-919755bcb452.mov
> TF-129 Fix bug focus disabled on recipient input form

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/top_bar_composer_widget_builder.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/email/presentation/widgets/app_bar_mail_widget_builder.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_select_mode_active_builder.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- model/lib/extensions/list_email_address_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/lib/extensions/utc_date_extension.dart
https://user-images.githubusercontent.com/80730648/135822829-04d92e00-627d-4a11-83cd-d3223cd8ff74.mov
> Fix some bug UI

- docs/adr/0001-record-architecture-decisions.md
- docs/adr/0002-caching.md
@chibenwa @dab246 please help me review this ADR
> [ADR] Caching mailbox and email

- bitrise.yml
- core/pubspec.yaml
- model/pubspec.yaml
- pubspec.yaml
- Flutter doctor -v 
````
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en)
• Flutter version 2.8.1 at /Users/datvu/Library/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
• Engine revision 890a5fca2e
• Dart version 2.15.1
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Users/datvu/Library/Android/sdk
• Platform android-31, build-tools 31.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
• All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
• Xcode at …
```
> Upgrade fllutter sdk 2.8.1

- lib/features/composer/data/network/composer_api.dart
- model/lib/upload/file_info.dart
- model/pubspec.yaml
https://user-images.githubusercontent.com/80730648/151537034-a2df591f-8523-4c27-abdb-dae265465bab.mov
> [BUG] Fix upload attachment

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- core/pubspec.yaml
- lib/features/email/presentation/widgets/email_content_item_builder.dart
https://user-images.githubusercontent.com/80730648/154023490-8d76dedd-f4ac-4809-8e72-d0d99c0a1636.mov
> TF-255 Read Email in Browser

- lib/features/composer/presentation/composer_controller.dart
- pubspec.yaml
-  Add individual header field for JMap Client: [https://github.com/linagora/jmap-dart-client/pull/22](https://github.com/linagora/jmap-dart-client/pull/22)
> TF-221 Create emails with User-Agent header

- Dockerfile
- bitrise.yml
- lib/features/home/presentation/home_controller.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/login_view.dart
- lib/main/utils/app_config.dart
> TF-256 Change login form for web

- core/lib/core.dart
- core/lib/presentation/views/dialog/edit_text_dialog_builder.dart
- core/lib/presentation/views/modal_sheets/edit_text_modal_sheet_builder.dart
- lib/features/mailbox/data/datasource/mailbox_datasource.dart
- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/datasource_impl/mailbox_datasource_impl.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/model/rename_mailbox_request.dart
- lib/features/mailbox/domain/repository/mailbox_repository.dart
- lib/features/mailbox/domain/state/rename_mailbox_state.dart
- lib/features/mailbox/domain/usecases/rename_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox/presentation/widgets/bottom_bar_selection_mailbox_widget.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_tile_builder.dart
- lib/features/mailbox_creator/presentation/extensions/validator_failure_extension.dart
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/80730648/155652149-e80e4106-be4a-48a2-85c4-8798d66aff5f.mp4
> TF-235 Rename a mailbox

- Dockerfile
- README.md
- env.file
- lib/main.dart
- lib/main/utils/app_config.dart
- pubspec.yaml
- server/nginx.conf
> Startup web mail

- Jenkinsfile
I think it should work but we still need to check after merge.
Indeed, Jenkins is expecting a Jenkinsfile being present in the branch it's trying to build. So we need to merge this on master and also on release if you want both docker builds and pushes for tmail flutter webapp :)
> Add a Jenkinsfile for web app docker build and push

- lib/features/composer/presentation/composer_controller.dart
- model/lib/email/email_content.dart
https://user-images.githubusercontent.com/80730648/156957444-a3d0e8cd-f878-4a7a-8fcc-ec71f97aa6a7.mov
> TF-287 Fix bug replies do not preserve line breaks

- core/lib/presentation/extensions/url_extension.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/login_view.dart
https://user-images.githubusercontent.com/80730648/156967758-d2475619-d663-4655-a39a-1ec3713b17be.mov
> TF-265 Remove prefix https:// in url login form

- core/lib/data/network/download/download_manager.dart
- core/lib/presentation/views/dialog/downloading_file_dialog_builder.dart
- core/pubspec.yaml
- env.file
- lib/features/composer/data/network/composer_api.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/top_bar_composer_widget_builder.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/state/download_attachment_for_web_state.dart
- lib/features/email/domain/usecases/download_attachment_for_web_interactor.dart
- lib/features/email/presentation/email_bindings.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/upload/domain/usecases/local_file_picker_interactor.dart
- lib/main/localizations/app_localizations.dart
- model/lib/upload/file_info.dart
- pubspec.yaml
- test/features/caching/email_cache_client_test.dart
- test/features/caching/mailbox_cache_client_test.dart
https://user-images.githubusercontent.com/80730648/156513006-05a1ccf5-2eb3-41c9-82ac-0c26112a49b6.mov
> TF-296 Support upload download file on browser

- lib/features/email/presentation/email_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
https://user-images.githubusercontent.com/80730648/157164150-47575bea-9a44-4b41-abb6-51ad2667c7ec.mov
> TF-275 Fix bug reload changes colors

- core/lib/core.dart
- core/lib/presentation/utils/shims/dart_ui.dart
- core/lib/presentation/utils/shims/dart_ui_fake.dart
- core/lib/presentation/utils/shims/dart_ui_real.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- core/lib/presentation/views/html_viewer/html_viewer_controller_for_web.dart
- core/pubspec.yaml
- lib/features/email/presentation/widgets/email_content_item_builder.dart
https://user-images.githubusercontent.com/80730648/157378456-f52a761d-eeeb-49e7-ab9c-4b7035efaa70.mov
> TF-292 Fix two scroll bars for medium sized screens

- core/lib/presentation/state/success.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/open_mailbox_view_event.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/main.dart
- pubspec.yaml
#343 
https://user-images.githubusercontent.com/6462404/158525574-a1b84011-b4da-43b8-be71-736263af5220.mov
#340 
https://user-images.githubusercontent.com/6462404/158620243-0c91bace-9c96-40bd-93ba-624a55b91ce5.mov
> Some bugs in Email list

- analysis_options.yaml
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_content_item_builder.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_controller.dart
https://user-images.githubusercontent.com/80730648/158779033-0f951365-ec52-43b1-8d3c-5c8d1ce940a7.mov
> Fix can't scroll email content in browser

- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/extensions/mailbox_extension.dart
- lib/features/mailbox/presentation/model/mailbox_node.dart
- lib/features/mailbox/presentation/model/mailbox_tree_builder.dart
- lib/main/bindings/credential/credential_bindings.dart
- test/features/mailbox/presentation/model/mailbox_tree_builder_test.dart
> TF-322 sort default mailbox base on SortOrder value

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- pubspec.yaml
https://user-images.githubusercontent.com/80730648/158997543-825276fd-76b8-4b5a-9076-f0beab71a8fd.mov
https://user-images.githubusercontent.com/80730648/158997170-9715045e-b35a-4f67-9164-24fb04539294.mp4
https://user-images.githubusercontent.com/80730648/158999102-aeb85bd8-752a-459e-92dc-8bd314e2b16f.mov
> Fix some bug composer in browser

- core/lib/presentation/utils/responsive_utils.dart
https://user-images.githubusercontent.com/80730648/159880598-e1b24859-47d3-4001-a760-21517ad85372.mov
> TF-398 Fix responsive on browser firefox

- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
https://user-images.githubusercontent.com/80730648/159891231-745d10fd-737f-4851-9fa4-3034d465ac43.mov
> TF-393 Fix threadView auto scroll up to the top after reading email

- lib/features/base/base_mailbox_controller.dart
- lib/features/mailbox/domain/state/delete_multiple_mailbox_state.dart
- lib/features/mailbox/domain/usecases/delete_multiple_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
https://user-images.githubusercontent.com/80730648/160054031-31848f9c-4bb0-4f0d-b878-25d751f24b8f.mov
> TF-372 Fix after deleted a mailbox, Tmail does not refresh and update the result

- core/lib/presentation/views/button/button_builder.dart
- lib/features/base/base_controller.dart
- lib/features/base/base_mailbox_controller.dart
- lib/features/email/presentation/email_bindings.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox/domain/state/refresh_changes_all_mailboxes_state.dart
- lib/features/mailbox/domain/usecases/refresh_all_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_tree_builder.dart
- lib/features/thread/domain/state/refresh_changes_all_email_state.dart
- lib/features/thread/domain/usecases/refresh_changes_emails_in_mailbox_interactor.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- model/lib/extensions/list_presentation_email_extension.dart
- test/features/thread/domain/usecases/refresh_changes_emails_in_mailbox_interactor_test.dart
https://user-images.githubusercontent.com/80730648/160100595-028a4379-c8fd-4c7f-9a6b-55108004d490.mov
> TF-348 Fix unread email counter not updating

- lib/features/email/domain/usecases/get_email_content_interactor.dart
- lib/features/email/presentation/email_view.dart
- model/lib/email/attachment.dart
- model/lib/extensions/list_attachment_extension.dart
https://user-images.githubusercontent.com/80730648/160330360-ecc7f852-803e-4ab5-8c41-db7136f8e8db.mov
> TF-389 Fix can not see the attachment in EmailView

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_content_item_builder.dart
https://user-images.githubusercontent.com/80730648/160331766-0196f108-6530-4482-87ac-3dddb7c49571.mov
> Fix select email bodies, subject

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_content_item_builder.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_view.dart
https://user-images.githubusercontent.com/80730648/160376969-be1b187b-a1ec-4d53-a6dc-ada404a650d0.mov
> TF-335 Open links in another tab in email detail view on browser

- lib/features/composer/data/network/composer_api.dart
https://user-images.githubusercontent.com/80730648/160534272-97d4d9ab-2b17-4a46-a7b4-cc53d28f17d8.mov
> TF-328 Fix can not upload files without extensions

- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/80730648/160543861-2f62bf07-76d9-43ea-945f-766163d61a08.mov
> TF-130 Checking `maxSizeAttachmentsPerEmail` when uploading attachments

- lib/features/email/presentation/email_controller.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
https://user-images.githubusercontent.com/80730648/160787686-4f6dde44-696b-4eba-bdc1-0f9ed688971d.mp4
> TF-386 Rework the select items in a message list in edit mode

- lib/l10n/intl_messages.arb
- lib/main.dart
- lib/main/localizations/app_localizations.dart
- web/index.html
> TF-323 Customise page name

- .gitignore
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- ios/Runner/Runner.entitlements
- lib/main.dart
- lib/main/bindings/core/core_bindings.dart
- lib/main/notification/firebase_push_notification.dart
- pubspec.yaml
- https://firebase.flutter.dev/docs/messaging/apple-integration/
> Config firebase

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.yaml
> TF-451 Add version information

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
https://user-images.githubusercontent.com/80730648/161955705-ddc2abf3-43b3-4810-a604-16447ea59478.mov
> TF-424 Fix the margin between email header and body is too big

- lib/features/base/mixin/message_dialog_action_mixin.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/extensions/list_attachment_extension.dart
https://user-images.githubusercontent.com/80730648/162159042-51d9b5d3-f82c-4090-adbd-f5b72ec763b2.mov
> Fix toast message when sending a message

- core/lib/presentation/utils/html_transformer/dom/link_transformers.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
https://user-images.githubusercontent.com/80730648/162939450-02c26335-c5a5-498c-a8ac-4ab123aa35af.mov
> TF-341 Show view flyover for links in Email Detail

- Dockerfile
- server/nginx.conf
Tested and gzip works locally.
The new `nginx.conf` file = default `nginx.conf` + server block + gzip on.
The GZIP setting includes compressed mime types review is welcome.
> Enable GZIP for Nginx

- core/lib/presentation/extensions/color_extension.dart
- lib/features/thread/presentation/thread_bindings.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- model/lib/email/email_action_type.dart
@hoangdat  please review it
https://user-images.githubusercontent.com/80730648/163512335-d5871739-75ba-4110-ad28-a5df8fd475c4.mov
> TF-484 Hover in email, action buttons are available to do in ThreadView

- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
https://user-images.githubusercontent.com/80730648/165245818-07a5fc8c-b038-49f8-81e6-e2c1cdd8cfd8.mov
> TF-483 Hover in email, checkbox is available to select email in Thread

- core/lib/presentation/utils/html_transformer/dom/sigature_transformers.dart
- core/lib/presentation/utils/html_transformer/html_transform.dart
- core/lib/presentation/utils/html_transformer/message_content_transformer.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- pubspec.yaml
- Signature only display on Web and Tablet 
+ If `html Signature` is not empty, display the signature with `html Signature`. Otherwise display the signature with `textSignature`
- Mobile don't display signature, but signature will be appended when sending email
- Create two functions written in `javascript` to handle `adding` Signature and `removing` it on composer: 
+ `insertSignature`:  Add a new signature
+ `removeSignature'` Delete the previous signature.
- Update composer for Web [https://github.com/dab246/html-editor-enhanced/commit/b7c2e32fe773fe766a99167f9e9149176dd045cc](https://github.com/dab246/html-editor-enhanced/commit/b7c2e32fe773fe766a99167f9e9149176dd045cc)
- Update composer for Mobile [https://github.com/dab246/enough_html_editor/commit/64c5fd104e54e7d4f79bebce9f443a42166 …
> TF-457 Display signature, bcc email address in composer

- lib/features/identity_creator/presentation/identity_creator_bindings.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/widgets/identity_field_no_editable_builder.dart
- lib/features/identity_creator/presentation/widgets/identity_input_field_builder.dart
- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/network/manage_account_api.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/domain/model/edit_identity_request.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/state/edit_identity_state.dart
- lib/features/manage_account/domain/usecases/edit_identity_interactor.dart
- lib/features/manage_account/domain/usecases/get_all_identities_interactor.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- model/lib/extensions/identity_extension.dart
- model/lib/identity/identity_request_dto.dart
- model/lib/model.dart
https://user-images.githubusercontent.com/80730648/168585884-0db4b03d-1cea-4fd2-bc8e-babc50b30739.mov
> #561 Fix edit identity

- bitrise.yml
@tnstung @dab246 Please help me review it
> Upgrade xcode stack for bitrise to 13.1.x

- bitrise.yml
(cherry picked from commit 22aade39dacceb3fa7244350644f9454d68a5dfd)
> Upgrade xcode stack for primary and default in bitrise to 13.1.x

- Dockerfile
@tnstung @Arsnael @dab246  Please help me review it
> Add script to run build_runner and pub get for `contact` module

- lib/features/login/presentation/login_view_web.dart
> Fix padding login

- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/profiles/profiles_view.dart
> #587 Remove search bar in setting screen

- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- core/pubspec.yaml
> Create QuickSearchInputForm widget

- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/model/signature_type.dart
- lib/features/identity_creator/presentation/widgets/identity_field_no_editable_builder.dart
- lib/features/identity_creator/presentation/widgets/identity_input_field_builder.dart
https://user-images.githubusercontent.com/80730648/170408394-2cd779e2-e53b-4ef7-9c7b-ef7d5141c9ec.mov
> #582+584 Fix bug text input is hidden and weird scroll bar in signature identity

- core/lib/presentation/utils/html_transformer/html_template.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
https://user-images.githubusercontent.com/80730648/170460996-8d945612-aed7-48df-9fe7-d68c11408071.mov
> #583 Fix weird scroll bar in email view

- model/lib/email/email_content.dart
https://user-images.githubusercontent.com/80730648/170466961-a0ca73ea-4841-48a3-9cc0-619353605daf.mov
> #558 Fix links broken in email view

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/widgets/identity_input_with_drop_list_field_builder.dart
- lib/features/mailbox_creator/domain/exceptions/verify_name_exception.dart
- lib/features/mailbox_creator/domain/model/verification/email_address_validator.dart
- lib/features/mailbox_creator/presentation/extensions/validator_failure_extension.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.yaml
https://user-images.githubusercontent.com/80730648/170420203-fbf7a685-6227-4683-810d-04690eeb5da2.mov
> #585 Fix identity restrict BCC field

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- model/lib/identity/identity_request_dto.dart
https://user-images.githubusercontent.com/80730648/170703535-b0525d93-5890-420a-9080-2fbfa1a0ce24.mov
https://user-images.githubusercontent.com/80730648/170703711-c9970929-af13-4435-9196-3b4249b02761.mov
> #597 Fix edit identity on browser

- core/lib/core.dart
- core/lib/presentation/extensions/html_extension.dart
- core/lib/presentation/utils/app_toast.dart
- core/lib/presentation/utils/responsive_utils.dart
- core/lib/presentation/views/text/text_field_builder.dart
- core/lib/presentation/views/toast/tmail_toast.dart
- core/lib/presentation/views/toast/toast_position.dart
- core/pubspec.yaml
- lib/features/composer/domain/state/save_email_as_drafts_state.dart
- lib/features/composer/domain/usecases/save_email_as_drafts_interactor.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- pubspec.yaml
https://user-images.githubusercontent.com/80730648/170965071-568b5a51-cee5-4b28-80eb-e3080e811b26.mov
https://user-images.githubusercontent.com/80730648/170965183-b1981e12-a4b0-4cd1-b378-7cbe856f4aa1.mov
> #475 Fix save draft on browser

- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/login/data/datasource/authentication_oidc_datasource.dart
- lib/features/login/data/datasource_impl/authentication_oidc_datasource_impl.dart
- lib/features/login/data/local/oidc_configuration_cache_manager.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/login/data/network/oidc_http_client.dart
- lib/features/login/data/repository/authentication_oidc_repository_impl.dart
- lib/features/login/domain/repository/authentication_oidc_repository.dart
- lib/features/login/domain/state/delete_authority_oidc_state.dart
- lib/features/login/domain/usecases/delete_authority_oidc_interactor.dart
- lib/features/login/domain/usecases/get_authenticated_account_interactor.dart
- lib/features/login/domain/usecases/get_stored_token_oidc_interactor.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/features/manage_account/domain/state/log_out_oidc_state.dart
- lib/features/manage_account/domain/usecases/log_out_oidc_interactor.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/main/bindings/local/local_bindings.dart
- model/lib/oidc/oidc_configuration.dart
https://user-images.githubusercontent.com/80730648/171792661-9818753b-2545-46c9-8c49-b320c258e916.mov
> #607 Logout OIDC

- Dockerfile
1. Custom env.file:
```
SERVER_URL=http://jmap.linagora.com
DOMAIN_REDIRECT_URL=http://jmap.linagora.com:3000
WEB_OIDC_CLIENT_ID=teammail-web
```
2. Volume the custom env.file 
```shell
hp@hp-quanth  ~/IdeaProjects/tmail-flutter   enable-nginx ±  docker run -v $PWD/env.file:/usr/share/nginx/html/assets/env.file tmail-flutter:latest
2022/06/14 07:03:20 [notice] 8#8: using the "epoll" event method
2022/06/14 07:03:20 [notice] 8#8: nginx/1.20.2
2022/06/14 07:03:20 [notice] 8#8: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
2022/06/14 07:03:20 [notice] 8#8: OS: Linux 5.15.0-37-generic
2022/06/14 07:03:20 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/06/14 07:03:20 [notice] 8#8: start worker processes
2022/06/14 07:03:20 [notice] 8#8: start worker process 9
2022/06/14 …
```
> TF-615 Gzip env.file on container startup

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/main.dart
<table>
<tr>
<th>Android</th>
<th>iOS</th>
</tr>
<tr>
<td><img src='https://user-images.githubusercontent.com/80730648/173730152-ad63c2cb-dbcd-4e0d-ac01-baeda71db199.png'/></td>
<td><img src='https://user-images.githubusercontent.com/80730648/173730179-b72d3b6e-7e58-4abd-8347-d6e9e971df3e.png'/></td>
</tr>
</table>
> TF-641 Change color for status bar in Android device

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
https://user-images.githubusercontent.com/80730648/173742481-8aad1bc2-a37b-4f3f-b045-f896c138d4a9.mov
> TF-452 Fix search boxes should be collapsed automatically when search inputs lost focus

- core/lib/presentation/utils/responsive_utils.dart
- core/lib/presentation/views/responsive/responsive_widget.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
<table>
<tr>
<th>#652</th>
<th>#653</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/80730648/174229514-5a2f11b5-e974-46fc-a73e-809e17bdbaf7.png" /></td>
<td><img src="https://user-images.githubusercontent.com/80730648/174229546-35bf8a7a-7f4b-4e3d-9e3a-f657a2252dfc.png" /></td>
</tr>
</table>
<table>
<tr>
<th>Issues</th>
<th>Resolved</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/80730648/174229615-208b7984-6700-493b-bff9-8b5cff78c304.png" /></td>
<td><img src="https://user-images.githubusercontent.com/80730648/174229651-3b20b9c9-a2f1-4e89-a1a7-bcf63e5cd03e.png" /></td>
</tr>
</table>
> TF-652,653 Fix some bug margin

- core/lib/presentation/views/button/icon_button_web.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
https://user-images.githubusercontent.com/80730648/174059415-9fe45089-4472-4a8d-b173-cd018ca04706.mov
> TF-602 Fix size changes when selection email in browser

- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/bottom_bar_selection_mailbox_widget.dart
- model/lib/mailbox/presentation_mailbox.dart
https://user-images.githubusercontent.com/80730648/174726635-af03ec23-5e01-4bd7-8384-62b3b1aa8a49.mov
> TF-551 Fix mailbox scrollbar jumps resizes

- lib/features/composer/presentation/composer_controller.dart
- Web
https://user-images.githubusercontent.com/80730648/174791285-1be442c2-d470-46dc-964c-027546d6ed76.mov
- Mobile (Android)
https://user-images.githubusercontent.com/80730648/174791358-1ce07dfa-c045-424a-825e-c98aeaf0a767.mov
> TF-647 Fix unable to select an email address after saving draft

- core/lib/core.dart
- core/lib/data/network/remote_exception_thrower.dart
- core/lib/domain/exceptions/remote_exception.dart
- lib/features/login/domain/exceptions/authentication_exception.dart
- lib/features/login/domain/usecases/get_credential_interactor.dart
- lib/features/login/domain/usecases/get_stored_token_oidc_interactor.dart
- lib/features/session/data/datasource_impl/session_datasource_impl.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/session/presentation/session_page_bindings.dart
- lib/l10n/intl_messages.arb
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/session/session_bindings.dart
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/80730648/174943499-bcf1771b-30d4-4d67-a600-42b5bdf8746d.mov
> TF-196 Form validation in Login form

- core/lib/presentation/utils/responsive_utils.dart
- core/lib/presentation/views/button/button_builder.dart
- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- core/lib/presentation/views/responsive/responsive_widget.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/app_bar_mail_widget_builder.dart
- lib/features/email/presentation/widgets/bottom_bar_mail_widget_builder.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_view.dart
- lib/features/mailbox_dashboard/presentation/base_mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form_bottom_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/icon_open_advanced_search_widget.dart
- lib/features/mailbox_dashboard/presentation/widgets/email_quick_search_item_tile_widget.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/model/app_setting.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/bottom_bar_thread_selection_widget.dart
- Tablet
https://user-images.githubusercontent.com/80730648/176895200-1b9dbe82-43f0-4a44-a344-9e1af36ba389.mp4
- Web
https://user-images.githubusercontent.com/80730648/176895113-8353f654-db39-4360-8178-61f4c7ec7cd8.mp4
> TF-682 Standardize Layout of Mailbox Dashboard base on the designer

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
https://user-images.githubusercontent.com/107173849/177191314-89b9b3aa-b52b-4f3f-9f22-fd535b03f6da.mov
> TM-679: Some links in mail can not open in other tabs

- core/lib/presentation/extensions/html_extension.dart
- lib/features/composer/domain/state/update_email_drafts_state.dart
- lib/features/composer/domain/usecases/update_email_drafts_interactor.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/email/domain/state/get_email_content_state.dart
- lib/features/email/domain/usecases/get_email_content_interactor.dart
- lib/features/email/presentation/email_view.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- lib/features/upload/presentation/model/upload_file_state_list.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/email/email_content.dart
- After getting `EmailContent` from `jmap` we converted it to html using `HtmlTransform` class so most emails will have content wrapped in default html tag assembly
```html
<html><head></head><body>${CONTENT_ORIGINAL}</body></html>
```
- Get the original email content to compare with the current content in the editor. If it's different, save it, if not, that's okay.
https://user-images.githubusercontent.com/80730648/178208688-867dbd1e-ab25-49c1-ac9e-9dff62e690d4.mov
> TF-332 Fix when nothing is change, Tmail still making jmap request

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- pubspec.yaml
-  [super_tag_editor](https://pub.dev/packages/super_tag_editor)
> TF-692 Use `super_tag_editor` library on `pub.dev` for autocomplete

- lib/features/thread/presentation/thread_view.dart
https://user-images.githubusercontent.com/107173849/178759362-39412e49-5692-4059-aeea-43b31eeb470b.mov
> TM-715: [Tablet] suggestion of quick search show unrelated result

- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
https://user-images.githubusercontent.com/107173849/178788061-2fcf2bf2-916d-4b1b-aa70-45b74d0e3c76.mov
> [Tablet] unexpected item is added to field when search in advance

- core/lib/presentation/utils/html_transformer/html_template.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
https://user-images.githubusercontent.com/107173849/178792482-7c2e09d6-d155-437d-ad5c-6ec853b5d16e.mov
> TF-583: Weird scroll bar in email view

- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
https://user-images.githubusercontent.com/107173849/179555091-09e4262f-9594-40bc-9fc8-a045a04afa99.mov
> TF-709: After search with advanced search, load more is not show corrected results

- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
https://user-images.githubusercontent.com/107173849/179194295-7e8ba6cf-3df0-4152-801f-16e12e2ad4e2.mov
https://user-images.githubusercontent.com/107173849/179436303-83ecafa8-c1cf-4d3f-b570-ac3bdde95c68.mov
> Compose email with text style for mobile

- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
https://user-images.githubusercontent.com/6462404/179939535-9780be6e-4d3a-4392-8c4f-1e466359f0d6.mov
> TF-717 Fix back in Manage account in large tablet

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- docs/adr/0009-on-before-unload-not-support-indexed-db.md
- docs/adr/0010-crash-app-when-open-webview-on-android-device.md
https://user-images.githubusercontent.com/107173849/179885716-ca2dd90f-fc31-46ba-bcee-78735ff9c824.mov
> hot fix crash app on android when loading webview

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- pubspec.yaml
https://user-images.githubusercontent.com/107173849/180655242-b3edeef9-81cf-47ff-9aab-592110b3880b.mov
> TF-726: add text_color background_color text_font setting

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/mixin/rich_text_button_mixin.dart
> edit UI rich text for design

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
https://user-images.githubusercontent.com/107173849/180972713-90f7bf07-5956-4905-b1c9-fbddf5adedf0.MP4
https://user-images.githubusercontent.com/107173849/180984656-91cb08c4-9176-4543-b4da-e8a168bbf147.mov
> add insert inline image function for tablet and mobile

- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
https://user-images.githubusercontent.com/107173849/181310967-ac69325a-ec1a-47fc-b183-93e86e20de04.mov
> add header style

- lib/features/email/presentation/email_view.dart
https://user-images.githubusercontent.com/6462404/181415863-d6b40049-425f-4555-bf95-67f88f2af032.mov
https://user-images.githubusercontent.com/6462404/181415893-5b056e10-eaa6-48b5-aaf4-f0ff9949102e.mov
> TF-755 Prevent WillPop in EmailView in mobile

- core/lib/presentation/views/dialog/color_picker_dialog_builder.dart
- lib/features/composer/presentation/composer_view.dart
https://user-images.githubusercontent.com/80730648/181485411-8526c92b-06e4-47d9-9ad9-0df5326e808c.mov
> TF-767 Support text style in mobile composer

- lib/features/email/domain/usecases/get_email_content_interactor.dart
https://user-images.githubusercontent.com/6462404/181490609-19d5b076-4c50-4d79-8bda-06a1d5f807b8.mp4
> #730 Show attachment in the case email content empty

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
https://user-images.githubusercontent.com/107173849/181574299-be05a6aa-dfd6-47e0-8dab-75d2bf5e28db.mov
https://user-images.githubusercontent.com/107173849/181677434-515ebe45-6d79-4bab-9cf5-6a5c7cccc6e8.mov
https://user-images.githubusercontent.com/107173849/181678607-d5f453fc-998d-4c83-9dbb-2a63342645ab.mov
> TF-739, TF-737 : Add bullets and align composer tablet

- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- model/lib/extensions/list_email_extension.dart
1. Continuous flashing effect when hovering avatar icon. Get a log bug of dart trên console web
2. Took a long time to select all emails
https://user-images.githubusercontent.com/80730648/182085779-775c7621-c633-4571-a4c5-840489284cf2.mov
3.  Sometimes selecting an email will de-select another email
1. Adjust icon size
2. Set size for each item list view
3. Because the `sort` function is wrong. Updated sort function inside [jmap_dart_client](https://github.com/linagora/jmap-dart-client/pull/32) and `tmail` app
1.
https://user-images.githubusercontent.com/80730648/182088009-0157fb48-f329-4bdc-a7ab-05ef580d55db.mov
2,3.
https://user-images.githubusercontent.com/80730648/182086479-0887ed3f-aee5-49f6-9a00-19749dd57cbd.mov
> TF-694 Fix bug selection emails

- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- model/lib/mailbox/presentation_mailbox.dart
https://user-images.githubusercontent.com/80730648/182102263-25563c28-3e48-476d-88d9-2c231687f1d8.mov
> TF-688 Fix [Trash folder] the deleted folder should not count messages

- core/lib/data/network/download/download_client.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/base_rich_text_controller.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
https://user-images.githubusercontent.com/80730648/182317741-0ebf3b74-59b2-402a-b95c-7c85c2e21376.mov
> TF-764 Fix inline images are not saved and shown successfully in Draft

- core/lib/presentation/extensions/color_extension.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/destination_picker/presentation/widgets/top_bar_destination_picker_web_builder.dart
- lib/features/thread/presentation/thread_view.dart
https://user-images.githubusercontent.com/80730648/182343702-33530fb4-3b8b-48f1-b567-5eb9c84a428d.mov
> TF-710 [WEB] Relayout destination picker base on prototype

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/linagora/android/tmail/MainActivity.kt
- docs/adr/0012-change-app-group-id-in-receive-sharing-intent.md
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- ios/TeamMailShareExtension/Info.plist
- ios/TeamMailShareExtension/ShareViewController.swift
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/utils/email_receive_manager.dart
- pubspec.yaml
https://user-images.githubusercontent.com/107173849/182308220-9d25513b-ece8-404b-8a7e-27636376cc67.mov
https://user-images.githubusercontent.com/107173849/182308364-d9f6dcbf-1554-41cb-8c31-443a81e54a04.mov
> TF-768: [Tablet/Mobile] Share image with TeamMail app

- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
https://user-images.githubusercontent.com/6462404/182568961-3cb65f5d-e7d0-4de4-8e1f-56330478500c.mov
> #785 Hide/Show selection options for ThreadView in web app

- core/lib/presentation/utils/html_transformer/base/dom_transformer.dart
- core/lib/presentation/utils/html_transformer/dom/add_tooltip_link_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/blockcode_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/blockquoted_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/script_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/sigature_transformers.dart
- core/lib/presentation/utils/html_transformer/html_transform.dart
- core/lib/presentation/utils/html_transformer/message_content_transformer.dart
- core/lib/presentation/utils/html_transformer/text/convert_url_string_to_html_links_transformers.dart
- core/lib/utils/linkify_html.dart
- core/test/linkify_html_test.dart
- lib/features/email/data/local/html_analyzer.dart
- lib/features/email/presentation/email_controller.dart
#786
https://user-images.githubusercontent.com/80730648/182574721-ba96173a-5b46-4df0-a237-db4e74d72f6f.mov
> TF-786 Can not see the link (jenkin) in email content 

- contact/lib/data/network/contact_api.dart
- core/lib/presentation/utils/style_utils.dart
- core/lib/presentation/views/button/button_builder.dart
- core/lib/presentation/views/button/icon_button_web.dart
- core/lib/presentation/views/search/search_bar_view.dart
- core/lib/presentation/views/text/rich_text_builder.dart
- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/composer/presentation/widgets/attachment_file_composer_builder.dart
- lib/features/composer/presentation/widgets/drop_down_menu_header_style_widget.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/destination_picker/presentation/widgets/app_bar_destination_picker_builder.dart
- lib/features/destination_picker/presentation/widgets/top_bar_destination_picker_web_builder.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_controller.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_view.dart
- lib/features/mailbox_creator/presentation/widgets/app_bar_mailbox_creator_builder.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/input_field_focus_manager.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form_bottom_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/text_field_auto_complete_email_adress.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#691 
https://user-images.githubusercontent.com/80730648/182835328-6359fe39-aeb3-4cdf-a6e7-42fcd43656d1.mov
> TF-691 Advanced search improvement

- lib/features/base/mixin/network_connection_mixin.dart
- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/login_view_web.dart
#783 
- Mobile
<table style="width:100%">
<tr>
<th>Have an internet connection</th>
<th>No connection internet</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/80730648/183006749-3fdc3317-57a7-41ae-a92a-7e8551c3a15a.png" /></td>
<td><img src="https://user-images.githubusercontent.com/80730648/183006619-57e48afc-7972-4749-b564-672b743eb65f.png" /></td>
</tr>
</table>
- Web
https://user-images.githubusercontent.com/80730648/183007599-303f32da-bf60-4888-a0a1-6b165fc81862.mov
> TF-783 Login in network not available

- core/lib/data/network/download/download_manager.dart
- core/lib/presentation/extensions/color_extension.dart
- core/pubspec.yaml
- lib/features/base/mixin/app_loader_mixin.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/state/download_attachment_for_web_state.dart
- lib/features/email/domain/usecases/download_attachment_for_web_interactor.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/download/download_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/model/download/download_task_state.dart
- lib/features/mailbox_dashboard/presentation/widgets/download/download_task_item_widget.dart
- lib/features/thread/presentation/thread_view.dart
- lib/main/bindings/network/network_bindings.dart
- model/lib/email/attachment.dart
- pubspec.yaml
#654 
- Upgrade version `dio` for `jmap-dart-client` at [PR#33](https://github.com/linagora/jmap-dart-client/pull/33)
https://user-images.githubusercontent.com/80730648/183249742-17d4e1fc-ed2c-4744-9316-428e7af32440.mov
> TF-654 Show the progress of download attachment in app

- core/pubspec.yaml
- lib/features/email/presentation/email_controller.dart
- pubspec.yaml
- Library `device_info_plus ` get error `Required named parameter 'userName' must be provided` 
- Upgrade latest version `device_info_plus` to `4.0.2`
> [HOT] Fix run `flutter test` failed

- lib/features/composer/presentation/controller/rich_text_web_controller.dart
#795 
https://user-images.githubusercontent.com/80730648/183571381-a34877f7-a238-4ca7-bcca-8f195eab2480.mov
> TF-795 [Web] Fix customizing style in composer unselect the composer widget

- core/lib/presentation/views/floating_button/scrolling_floating_button_animated.dart
- lib/features/thread/presentation/thread_view.dart
> TF-765 Compose button is not shown properly in mobile

- lib/features/composer/presentation/controller/rich_text_web_controller.dart
#797 
https://user-images.githubusercontent.com/80730648/183566434-666d5070-ec00-492b-97c4-260b5085a548.mov
> TF-797 [Web] Fix cursor position should display style of the current position in composer

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/features/composer/presentation/widgets/suggestion_email_address.dart
#784 
https://user-images.githubusercontent.com/6462404/183619270-cf8316cf-b099-4c05-a383-f3dd39490f8d.mov
https://user-images.githubusercontent.com/6462404/183619297-dfd40c57-02f8-4e80-ac4c-60f8e865b2b4.mov
> Avoid duplicated recipient

- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/network/manage_account_api.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/domain/model/delete_email_rule_request.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/state/delete_email_rule_state.dart
- lib/features/manage_account/domain/usecases/delete_email_rule_interactor.dart
- lib/features/manage_account/presentation/email_rules/email_rules_bindings.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/manage_account/presentation/email_rules/widgets/list_email_rules_widget.dart
- rule_filter/lib/rule_filter/converter/rule_id_nullable_converter.dart
- rule_filter/lib/rule_filter/get/get_rule_filter_method.dart
- rule_filter/lib/rule_filter/get/get_rule_filter_response.dart
- rule_filter/lib/rule_filter/rule_filter_id.dart
- rule_filter/lib/rule_filter/rule_id.dart
- rule_filter/lib/rule_filter/tmail_rule.dart
https://user-images.githubusercontent.com/107173849/183816628-833d6d16-79d7-4094-874d-861febda05bc.mov
https://user-images.githubusercontent.com/107173849/183816872-00889d07-bb38-481b-99dd-dcf9bb810865.mov
> TF-613: As a user, I wan to delete a filter email rule

- core/lib/presentation/extensions/color_extension.dart
- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/domain/model/edit_email_rule_filter_request.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/state/edit_email_rule_filter_state.dart
- lib/features/manage_account/domain/usecases/edit_email_rule_filter_interactor.dart
- lib/features/manage_account/presentation/email_rules/email_rules_bindings.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/manage_account/presentation/email_rules/email_rules_view.dart
- lib/features/manage_account/presentation/email_rules/widgets/email_rule_item_widget.dart
- lib/features/manage_account/presentation/email_rules/widgets/email_rules_header_widget.dart
- lib/features/manage_account/presentation/email_rules/widgets/list_email_rules_widget.dart
- lib/features/rules_filter_creator/presentation/model/creator_action_type.dart
- lib/features/rules_filter_creator/presentation/model/rules_filter_creator_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_bindings.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/widgets/rules_filter_input_field_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#612 
https://user-images.githubusercontent.com/80730648/184100568-93979daa-8db0-41bf-a242-0a84d9e3403a.mov
> TF-612 Edit a filter email rule

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_controller.dart
#444 
https://user-images.githubusercontent.com/80730648/184322980-210f69d4-1d35-4bf1-ab3e-7639daebd146.mov
> TF-444 Use specials characters to name a mailbox folder

- Dockerfile
- bitrise.yml
- pubspec.yaml
> Release v0.3.12

- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/manage_account/presentation/extensions/vacation_response_extension.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/widgets/vacation_notification_message_widget.dart
- lib/features/thread/presentation/thread_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/extensions/presentation_email_extension.dart
- model/lib/extensions/utc_date_extension.dart
#802 
https://user-images.githubusercontent.com/80730648/185370009-1885aef2-0b04-400c-8538-131ef6dec589.mov
> TF-802 Disable my vacation responder

- forward/lib/forward/set/set_forward_method.dart
- forward/lib/forward/set/set_forward_response.dart
- forward/lib/forward/tmail_forward.dart
- forward/test/forward/set_forward_method_test.dart
- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/network/manage_account_api.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/domain/model/delete_recipient_in_forwarding_request.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/state/delete_recipient_in_forwarding_state.dart
- lib/features/manage_account/domain/usecases/delete_recipient_in_forwarding_interactor.dart
- lib/features/manage_account/presentation/extensions/tmail_forward_extension.dart
- lib/features/manage_account/presentation/forward/forward_bindings.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/features/manage_account/presentation/forward/widgets/email_forward_item_widget.dart
- lib/features/manage_account/presentation/forward/widgets/email_forward_item_widget_for_web.dart
- lib/features/manage_account/presentation/forward/widgets/list_email_forward_widget.dart
- lib/features/manage_account/presentation/menu/widgets/account_menu_item_tile_builder.dart
- lib/features/manage_account/presentation/model/recipient_forward.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#832 
https://user-images.githubusercontent.com/80730648/185558136-15ac1d44-9dac-43d7-b326-28fa9e10ba5f.mov
> TF-832 Delete an recipient and multiple recipients in forwarding

- lib/features/composer/presentation/composer_controller.dart
#834 
- `SentAt` is `null` in some emails
https://user-images.githubusercontent.com/80730648/185840046-c720e894-5b99-4899-adf3-85afce6b6f6a.mov
> TF-834 Fix in replied email, `on` is miss the date

- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
#854 
https://user-images.githubusercontent.com/80730648/185872794-02fe645e-af9b-413f-832d-cd2081f64901.mov
> TF-854 [Mobile] Fix click to Edit rule in Dialog but nothing happen

- core/lib/presentation/utils/html_transformer/dom/add_target_blank_in_tag_a_transformers.dart
- core/lib/presentation/utils/html_transformer/message_content_transformer.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
https://user-images.githubusercontent.com/107173849/185820244-0e85d69a-4107-4669-91fe-fab0c8f3d8fe.mov
https://user-images.githubusercontent.com/107173849/185871637-2d333f62-063d-4088-a463-0e6b920c81be.mov
Tested on product environment
> TF-806 open new tab when click link or tags a

- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/main/routes/app_routes.dart
#855 
https://user-images.githubusercontent.com/80730648/185890798-11073788-94ac-460a-ac4d-b81c8c31d318.mov
> TF-855 [Mobile] Fix bottom corner of `Create new rule` dialog are too high

- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/domain/model/edit_local_copy_in_forwarding_request.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/state/edit_local_copy_in_forwarding_state.dart
- lib/features/manage_account/domain/usecases/edit_local_copy_in_forwarding_interactor.dart
- lib/features/manage_account/presentation/forward/forward_bindings.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/features/manage_account/presentation/forward/widgets/forward_header_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/107173849/185774026-f823f399-739c-485b-b9e5-44f0cfd169eb.mov
https://user-images.githubusercontent.com/107173849/185774033-c12a5a48-d1b9-41a7-9364-76092e487212.mov
> TF-859: Keep local copy in forwards

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/user_information_widget_builder.dart
- lib/features/manage_account/presentation/email_rules/email_rules_view.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/features/manage_account/presentation/forward/widgets/forward_header_widget.dart
- lib/features/manage_account/presentation/language_and_region/language_and_region_view.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_bindings.dart
- lib/features/manage_account/presentation/menu/settings/settings_controller.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_view.dart
- lib/features/manage_account/presentation/menu/settings_utils.dart
- lib/features/manage_account/presentation/menu/widgets/setting_first_level_tile_builder.dart
- lib/features/manage_account/presentation/model/account_menu_item.dart
- lib/features/manage_account/presentation/model/settings_page_level.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/profiles_view.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/6462404/186378869-545d09dc-9ae0-477e-bf0a-bf2e080f083e.mp4
https://user-images.githubusercontent.com/6462404/186380366-e5736f5e-f624-4d99-b3e3-d61a3b3a58bf.mov
https://user-images.githubusercontent.com/6462404/186380795-7e4a9618-497c-49c3-80a9-9e88f8052c07.mov
> #788 Universal settings

- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/forward/widgets/forward_header_widget.dart
https://user-images.githubusercontent.com/107173849/186380743-d32e8778-b242-4701-8037-584c27c1a96d.mov
> TF-859 Keep local copy in Forwarding

- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
Need merge https://github.com/linagora/enough_html_editor/pull/2 before review
https://user-images.githubusercontent.com/107173849/186565654-97c9c8e3-f918-4b07-8468-a2c696c31746.mov
> TF-867 [Android] Share image with TeamMail app 

- android/app/src/main/res/values-night-v21/styles.xml
- android/app/src/main/res/values-night-v29/styles.xml
- android/app/src/main/res/values-night/styles.xml
- android/app/src/main/res/values-v21/styles.xml
- android/app/src/main/res/values-v29/styles.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
#874 
https://user-images.githubusercontent.com/80730648/186622997-40c7d312-db61-4cdc-97d3-9686a7f0b396.mp4
> TF-874 [Android] Fix cursor pointer indicator in composer is wrong color

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/user_information_widget_builder.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/features/manage_account/presentation/forward/widgets/list_email_forward_widget.dart
- lib/features/manage_account/presentation/language_and_region/language_and_region_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/profiles/identities/identities_view.dart
- #852 
- Align center view
- Overflow bottom view
**- Mobile/Tablet:**
https://user-images.githubusercontent.com/80730648/186655016-d9daf87e-b393-4619-9e53-310dcac8a61d.mp4
**- Web:**
https://user-images.githubusercontent.com/80730648/186655118-5dc2ae29-312f-4cd1-ad8c-aaa9c0f0d7e2.mov
> TF-852 Fix some bug UI on Setting Screen

- ios/Podfile
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- pubspec.yaml
#876 
https://user-images.githubusercontent.com/80730648/186890399-e305050b-786d-4f97-b3e5-7da01638be90.mov
> TF-876 [Mobile] Auto suggestion in composer not suggest email in Contact app

- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
#875 
https://user-images.githubusercontent.com/80730648/188344739-f2174752-c167-4121-ac61-663d8f19439a.mp4
> TF-875 [Mobile] Fix reset to default color in text color not work

- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/manage_account/presentation/email_rules/widgets/email_rule_item_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#853 
https://user-images.githubusercontent.com/80730648/188349162-05ac539a-00ca-43c7-be66-897841b5de4a.mov
> TF-853 Fix delete a rule without confirm dialog

- lib/features/composer/presentation/composer_controller.dart
> TF-902 Fix remove `blodId` from `htmlBody` in accordance with `RFC8621` documentation standard

- lib/features/thread/data/repository/thread_repository_impl.dart
https://user-images.githubusercontent.com/107173849/188931186-362d7a67-c31e-4813-9e19-06c2cc12cdb2.mov
> TF-897: [Mobile] Can't loadmore emails on mobile

- lib/features/caching/authentication_info_cache_client.dart
- lib/features/caching/caching_manager.dart
- lib/features/caching/config/hive_cache_config.dart
- lib/features/caching/encryption_key_cache_client.dart
- lib/features/caching/token_oidc_cache_client.dart
- lib/main/bindings/local/local_bindings.dart
#928 
https://user-images.githubusercontent.com/80730648/189047245-ea3d6b27-597c-4c99-9b16-20063832cc97.mp4
https://user-images.githubusercontent.com/80730648/189047337-4f27d1e7-b717-4bc4-9bf1-6161ace0ad5b.mov
> TF-928 Fix force logout when reload web

- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_button_field.dart
- lib/features/rules_filter_creator/presentation/widgets/rules_filter_input_field_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#894 
#856 
https://user-images.githubusercontent.com/80730648/189063028-769f07bf-b7ab-43b3-9dd4-d2577bf9fa4b.mov
> TF-894,856 Fix auto focus input field when create/edit Rule

- core/lib/presentation/extensions/color_extension.dart
- lib/features/email/domain/state/delete_email_permanently_state.dart
- lib/features/email/domain/usecases/delete_email_permanently_interactor.dart
- lib/features/email/presentation/widgets/app_bar_mail_widget_builder.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/thread/presentation/model/delete_action_type.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/bottom_bar_thread_selection_widget.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#421 
https://user-images.githubusercontent.com/80730648/189088243-c69e9c92-3a7a-434a-bd93-08497ed1d707.mov
https://user-images.githubusercontent.com/80730648/189112661-538833c4-f38e-446e-9934-19f5850ff6f1.mov
> TF-421 Support delete permanently in draft

- android/app/src/main/AndroidManifest.xml
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- core/pubspec.yaml
- ios/Runner/Info.plist
-Android:
https://user-images.githubusercontent.com/107173849/189553778-5dd96ee4-7d74-40de-9f52-a693179df48b.mov
-IOS:
https://user-images.githubusercontent.com/107173849/189553785-38b4d94a-2f91-4799-bb7a-b05f237a35eb.mov
> TF-903: Open to other app using deeplink

- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/domain/usecases/delete_multiple_mailbox_interactor.dart
- lib/main/error/capability_validator.dart
- lib/main/error/request_error.dart
- model/lib/extensions/session_extension.dart
- test/main/error/capability_validator_test.dart
https://user-images.githubusercontent.com/6462404/189883659-662cc43f-508e-443d-8654-5868cd7239af.mov
https://user-images.githubusercontent.com/6462404/189887113-387b538b-b515-485c-8a10-13978b81cb3a.mov
> TF-939 [PART-I] Depend on `accountCapabilities` to delete multiple mailboxes

- bitrise.yml
Replacing expired certificates
> Updated provisioning profile and cert

- contact/lib/contact/autocomplete/autocomplete_tmail_contact_method.dart
- contact/lib/contact/model/capability_contact.dart
- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/composer/presentation/extensions/session_extension.dart
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/features/emails_forward_creator/presentation/emails_forward_creator_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/autocomplete_bindings.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/manage_account/data/datasource/manage_account_datasource.dart
- lib/features/manage_account/data/datasource/vacation_data_source.dart
- lib/features/manage_account/data/datasource_impl/manage_account_datasource_impl.dart
- lib/features/manage_account/data/datasource_impl/vacation_data_source_impl.dart
- lib/features/manage_account/data/network/manage_account_api.dart
- lib/features/manage_account/data/network/vacation_api.dart
- lib/features/manage_account/data/repository/manage_account_repository_impl.dart
- lib/features/manage_account/data/repository/vacation_repository_impl.dart
- lib/features/manage_account/domain/repository/manage_account_repository.dart
- lib/features/manage_account/domain/repository/vacation_repository.dart
- lib/features/manage_account/domain/usecases/get_all_vacation_interactor.dart
- lib/features/manage_account/domain/usecases/update_vacation_interactor.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_controller_bindings.dart
- lib/features/manage_account/presentation/vacation/vacation_interactors_bindings.dart
- lib/main/bindings/network/network_bindings.dart
https://user-images.githubusercontent.com/6462404/190364522-df8b306a-a59b-4ddf-8c81-3cc2bbc86f4a.mov
> #939 [Part II] inject auto complete/vacation module

- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/utils/responsive_utils.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- core/lib/presentation/views/search/search_bar_view.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/app_bar_mail_widget_builder.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/action/dashboard_action.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- lib/features/mailbox_dashboard/presentation/widgets/top_bar_thread_selection.dart
- lib/features/thread/domain/state/search_email_state.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/extensions/list_presentation_email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/lib/mailbox/presentation_mailbox.dart
#933 
https://user-images.githubusercontent.com/80730648/190500361-5118ee9d-6f4b-4a6f-b2a7-1e14cdeb6c98.mp4
> TF-933 [PART-1] Apply new design for search

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
https://user-images.githubusercontent.com/107173849/190536568-4c3bed9b-0875-4e66-92b4-28afd166e016.mov
https://user-images.githubusercontent.com/107173849/190557115-84f9368c-b922-4af3-ac26-3a9c29496d4b.mov
> Can't pop back on Web when reload

- core/lib/presentation/extensions/color_extension.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/email_quick_search_item_tile_widget.dart
- lib/features/mailbox_dashboard/presentation/widgets/recent_search_item_tile_widget.dart
- lib/features/search/domain/state/refresh_changes_search_email_state.dart
- lib/features/search/domain/usecases/refresh_changes_search_email_interactor.dart
- lib/features/search/presentation/model/search_more_state.dart
- lib/features/search/presentation/search_email_bindings.dart
- lib/features/search/presentation/search_email_controller.dart
- lib/features/search/presentation/search_email_view.dart
- lib/features/search/presentation/utils/search_email_utils.dart
- lib/features/search/presentation/widgets/app_bar_selection_mode.dart
- lib/features/search/presentation/widgets/email_receive_time_action_tile_widget.dart
- lib/features/search/presentation/widgets/email_receive_time_cupertino_action_sheet_action_builder.dart
- lib/features/thread/presentation/mixin/base_email_action_controller.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/routes/app_routes.dart
- model/lib/extensions/list_presentation_email_extension.dart
#933 
https://user-images.githubusercontent.com/80730648/190505825-9c8a824b-9251-4d35-abc2-d78ef7835394.mp4
https://user-images.githubusercontent.com/80730648/190505930-cb567024-d4ad-4e2a-b305-e1ed148e66ae.mp4
> TF-933 [PART-2] Apply new design for search 

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_view.dart
https://user-images.githubusercontent.com/6462404/190587659-2b94dd78-6d91-4ca0-9830-534ba337ea80.mov
https://user-images.githubusercontent.com/6462404/190587699-873c9461-c0ac-496c-ad8d-9af203c330d4.mov
> TF-939 [part III] Inject Rules/Forwarding/Vacation

- lib/features/thread/presentation/thread_controller.dart
https://user-images.githubusercontent.com/107173849/190974290-577b45fc-b435-4cce-8ae1-050829a3a63a.mov
> Hotfix: Loadmore

- core/lib/core.dart
- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/utils/responsive_utils.dart
- core/lib/presentation/views/button/icon_button_web.dart
- core/lib/presentation/views/checkbox/labeled_checkbox.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form_bottom_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
#913 
https://user-images.githubusercontent.com/80730648/191417568-1d3efc40-f2e6-4d3f-b91a-c172996122eb.mov
> TF-913 Fix line breaks

- core/lib/presentation/utils/app_toast.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- model/lib/extensions/mailbox_extension.dart
#973 
- https://github.com/linagora/jmap-dart-client/pull/41
https://user-images.githubusercontent.com/80730648/192510624-377b8c09-367c-437f-8a56-c3af3553f695.mov
> TF-973 Fix can not create folder with name contain special

- core/lib/presentation/extensions/color_extension.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
#981 
- FireFox
https://user-images.githubusercontent.com/80730648/192694122-402c13d1-f723-43f2-a7f0-ec7286664574.mov
- Chrome
https://user-images.githubusercontent.com/80730648/192694180-f3c5e70c-250b-4f58-bf68-495a7549696c.mov
> TF-981 Fix composer background color is broken

- .github/workflows/ci.yaml
Should be available with a button on the `Actions` page
> Added manual trigger to CI flow

- lib/features/base/base_mailbox_controller.dart
- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/mailbox/presentation/model/mailbox_node.dart
- lib/features/mailbox/presentation/model/mailbox_tree_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_search_tile_builder.dart
- model/lib/extensions/presentation_mailbox_extension.dart
- model/lib/mailbox/mailbox_state.dart
- model/lib/mailbox/presentation_mailbox.dart
- model/lib/model.dart
#975 
https://user-images.githubusercontent.com/80730648/192933561-203a65ab-fc5a-4d6a-8fc3-c57d6437f7d3.mov
> TF-975 Ignore and blur out all sub folder of folder when move it

- .github/workflows/analyze-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Missed a file when committing 😅
> Updated cache to include all pubspec.lock files

- lib/features/composer/presentation/mixin/rich_text_button_mixin.dart
- lib/features/composer/presentation/model/button_layout_type.dart
- lib/features/manage_account/presentation/extensions/vacation_response_extension.dart
- lib/features/manage_account/presentation/model/vacation/vacation_message_type.dart
- lib/features/manage_account/presentation/model/vacation/vacation_presentation.dart
- lib/features/manage_account/presentation/vacation/utils/vacation_utils.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_controller_bindings.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- lib/features/manage_account/presentation/vacation/widgets/vacation_notification_message_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- pubspec.yaml
#858 
- Mobile
https://user-images.githubusercontent.com/80730648/193243214-b4d432a3-f621-45a0-a185-d9a457b61318.mov
- Web
https://user-images.githubusercontent.com/80730648/193243652-4e117f89-c2f5-426d-80b0-15b35b08a4fc.mov
> TF-858 Support html body for vacation

- core/lib/presentation/extensions/color_extension.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.yaml
- Apply toolbar composer and signature `htmlBody` of identity:
https://user-images.githubusercontent.com/107173849/193200290-b8aa6335-7193-4b0e-9532-eeea32ebba55.mov
> TF-880, 912: Apply new design for rich text 

- lib/features/thread/data/repository/thread_repository_impl.dart
- Cause: combine with cache for only one mailbox while `changes` response in all
- Resolve: get all email cache for synchronizing
https://user-images.githubusercontent.com/6462404/193189780-9e815610-fc52-4906-93cd-c94c668fe4a0.mov
> TF-1009 cache not synchronize enough:

- lib/features/manage_account/presentation/extensions/datetime_extension.dart
- lib/features/manage_account/presentation/extensions/vacation_response_extension.dart
- lib/features/manage_account/presentation/model/vacation/vacation_presentation.dart
- model/lib/extensions/utc_date_extension.dart
#1003 
- Due to the difference between `UTC` and `Local` time
https://user-images.githubusercontent.com/80730648/193010953-f1e9849e-c16f-41c1-9883-241e1daf943a.mp4
> TF-1003 Fix select today as start date, can not receive vacation message

- contact/pubspec.lock
- docs/adr/0017-email-cache-guideline.md
- forward/pubspec.lock
- lib/features/thread/data/repository/thread_repository_impl.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
https://user-images.githubusercontent.com/6462404/193951012-dfe4aa33-80a3-40d2-9e0c-8bc1e2ea75b0.mov
> Force synchronize cache when state available 

- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/email_receive_time_type.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/drop_down_button_filter_widget.dart
- lib/features/manage_account/presentation/extensions/datetime_extension.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- pubspec.yaml
#997 
- [flutter-date-range-picker](https://github.com/linagora/flutter-date-range-picker)
https://user-images.githubusercontent.com/80730648/194107254-ef820990-0108-4cdc-ac11-ee0f8ad9ad35.mov
> TF-997 Custom date ranges in search

- core/lib/presentation/views/responsive/responsive_widget.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/thread/presentation/thread_controller.dart
- pubspec.lock
#1043 
- In the `SearchEmailFilter` filter, the value of `before` date still exists when doing `loadMore` for the first time.
- Before fixed
https://user-images.githubusercontent.com/80730648/194277469-9fc486d5-306b-45a8-be83-5c87fd6014fd.mov
- After fixed
https://user-images.githubusercontent.com/80730648/194278283-cab2f0f4-4ec2-42d7-b83d-394585d48044.mov
> TF-1043 Fix advanced search not working correctly

- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- ios/TeamMailShareExtension/Info.plist
- ios/TeamMailShareExtension/ShareViewController.swift
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/home/presentation/home_controller.dart
- lib/main/utils/email_receive_manager.dart
Test Android:
https://user-images.githubusercontent.com/107173849/193953115-cbd81cf1-99d3-4918-93eb-cfd1907d4220.mov
Test IOS:
https://user-images.githubusercontent.com/107173849/194011667-eacd31a5-8b5d-4d7d-b500-1965e9ebd81d.mov
Test Inline:
https://user-images.githubusercontent.com/107173849/194214636-a6d63250-1550-418d-af6f-f5585fc4aba2.mov
> TF-523: Share a file from my device

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- pubspec.lock
- pubspec.yaml
Merge this PR before review: 
https://github.com/linagora/rich-text-composer/pull/8
Evidence:
https://user-images.githubusercontent.com/107173849/194199760-2c43d2b5-89e7-4180-a908-be5b86b4f88c.mov
> TF-1033: Auto scroll composer to follow user typing

- Jenkinsfile
Since we do not release new versions on `release` branch anymore
> Removed `release` conditionals in Jenkinsfile

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_categories.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#983 
#986 
https://user-images.githubusercontent.com/80730648/194984004-3ed36217-f207-437a-b12c-3f53217193a8.mov
https://user-images.githubusercontent.com/80730648/194984436-664f4545-bb67-4ed7-bdfe-5c14393739c4.mov
> TF-986, 983 Slightly re-arrange mailbox menu

- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
#1038 
https://user-images.githubusercontent.com/80730648/195493889-410986f6-224e-438b-954f-91460ede51cd.mov
https://user-images.githubusercontent.com/80730648/195494011-a040b959-f562-481f-9217-bca297ddd230.mov
> TF-1038 Remove this redundant buttons in `to` `cc` `bcc`

- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- pubspec.lock
- pubspec.yaml
https://user-images.githubusercontent.com/107173849/195791015-081b41d7-324b-4dd6-bc97-e7b00d0ec62c.mov
> TF-1034: Apply new rich text toolbox for Tablet

- docs/configuration/app_grid_configuration.md
- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_categories.dart
- lib/features/mailbox_dashboard/presentation/controller/app_grid_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_grid_dashboard_item.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_list_dashboard_item.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/6462404/196600345-bb5ab43d-2d24-4bbb-860a-3ccba92e038c.mov
> [PART-II] #1018 Apply AppGrid for Tablet/Mobile web

- lib/features/email/presentation/email_view.dart
- pubspec.lock
- pubspec.yaml
> Release v0.3.18

- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/model/move_to_mailbox_request.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/usecases/move_to_mailbox_interactor.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_search_tile_builder.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread/domain/usecases/move_multiple_email_to_mailbox_interactor.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
https://user-images.githubusercontent.com/107173849/196932611-ee0d22e7-e658-42a0-987c-da2b06ff9c0d.mov
Drag with search mailbox: 
https://user-images.githubusercontent.com/107173849/197111718-cea92a86-b29b-47d3-8b04-8fd63214da78.mov
Drag with search email: 
https://user-images.githubusercontent.com/107173849/197125054-9cd95eee-856a-4dc5-b949-f1a00faa2c14.mov
After merge request when searching email :
https://user-images.githubusercontent.com/107173849/197466128-5f3b12ea-0f2d-421b-8921-9fed4e91dba6.mov
> TF-1083: Drag email to mailbox

- lib/features/base/widget/recent_item_tile_widget.dart
- lib/features/caching/config/hive_cache_config.dart
- lib/features/caching/recent_login_username_cache_client.dart
- lib/features/caching/utils/caching_constants.dart
- lib/features/cleanup/data/datasource/cleanup_datasource.dart
- lib/features/cleanup/data/datasource_impl/cleanup_datasource_impl.dart
- lib/features/cleanup/data/local/recent_login_username_cache_manager.dart
- lib/features/cleanup/data/repository/cleanup_repository_impl.dart
- lib/features/cleanup/domain/model/recent_login_username_cleanup_rule.dart
- lib/features/cleanup/domain/repository/cleanup_repository.dart
- lib/features/cleanup/domain/state/cleanup_recent_login_username_cache_state.dart
- lib/features/cleanup/domain/usecases/cleanup_recent_login_username_interactor.dart
- lib/features/home/presentation/home_bindings.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/login/data/datasource/login_username_datasource.dart
- lib/features/login/data/datasource_impl/login_username_datasource_impl.dart
- lib/features/login/data/model/recent_login_username_cache.dart
- lib/features/login/data/repository/login_username_repository_impl.dart
- lib/features/login/domain/extensions/list_recent_login_username_extension.dart
- lib/features/login/domain/model/recent_login_username.dart
- lib/features/login/domain/repository/login_username_repository.dart
- lib/features/login/domain/state/get_all_recent_login_username_state.dart
- lib/features/login/domain/state/save_recent_login_username_state.dart
- lib/features/login/domain/usecases/get_all_recent_login_username_on_mobile_interactor.dart
- lib/features/login/domain/usecases/save_login_username_on_mobile_interactor.dart
- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_bindings.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/widgets/login_text_input_builder.dart
- lib/main/bindings/local/local_bindings.dart
#1068 
https://user-images.githubusercontent.com/43041967/197471563-7433eaf3-a9d1-4210-b323-44dd254735f2.mp4
https://user-images.githubusercontent.com/43041967/197509054-17d7bd8a-778d-4c2a-9cd2-83850ade5551.mp4
> TF-1068 Make a recent list for input of username

- lib/features/mailbox/domain/state/delete_multiple_mailbox_state.dart
- lib/features/mailbox/domain/usecases/delete_multiple_mailbox_interactor.dart
- lib/features/mailbox/presentation/extensions/list_mailbox_node_extension.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_node.dart
- lib/features/mailbox/presentation/utils/mailbox_utils.dart
- lib/features/mailbox/presentation/widgets/bottom_bar_selection_mailbox_widget.dart
- lib/features/mailbox_creator/presentation/mailbox_creator_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- test/features/mailbox/presentation/utils/generate_mapping_delete_multiple_mailbox_test.dart
#1080 
https://user-images.githubusercontent.com/80730648/197955299-0d89fa9f-9b2c-4552-b2ef-b1e1b9ba1480.mp4
> TF-1080 Implement delete multiple mailbox folder

- lib/features/email/domain/state/get_email_content_state.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/manage_account/domain/state/get_all_identities_state.dart
- When opening details 1 email. the loading bar doesn't show up all the time and after about 10s 10s it starts showing loading
https://user-images.githubusercontent.com/80730648/198524863-c836fb17-b5e3-4520-8316-e33bee727a9a.mp4
https://user-images.githubusercontent.com/80730648/198524753-93de75bb-aa10-4c03-97f5-1253f595e0f4.mov
> Fix loading bar displayed after 10s

- lib/features/composer/presentation/composer_controller.dart
- File `.eml` of email received
[Test user agent.eml.zip](https://github.com/linagora/tmail-flutter/files/9916780/Test.user.agent.eml.zip)
https://user-images.githubusercontent.com/80730648/199411110-5d66dea1-c189-4935-bc14-bc433e86d774.mov
> TF-1139 Specify Team Mail in user agent

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/action/dashboard_action.dart
- lib/features/mailbox_dashboard/presentation/base_mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/mixin/filter_email_popup_menu_mixin.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/icon_open_advanced_search_widget.dart
- lib/features/search/presentation/search_email_controller.dart
- lib/features/search/presentation/search_email_view.dart
- lib/features/thread/domain/model/filter_message_option.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
https://user-images.githubusercontent.com/80730648/199641309-90f4be60-93aa-433c-9126-3a9b9c022c40.mp4
> TF-1063 Fixe some bugs related to search

- lib/features/mailbox/presentation/mailbox_view_web.dart
#1120 
https://user-images.githubusercontent.com/80730648/199811897-dcc52c7b-e924-41a7-9c5e-cc3a14117a13.mov
> TF-1120 Fix toast after drag n drop not correctly

- Dockerfile
> Adopt nginx:mainline

- lib/features/mailbox_dashboard/presentation/widgets/top_bar_thread_selection.dart
- lib/features/search/presentation/widgets/app_bar_selection_mode.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
> TF-1165: Wrong Icon Read/Unread at ThreadTopBar

- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/thread/presentation/widgets/app_bar_thread_widget_builder.dart
- lib/features/thread/presentation/widgets/bottom_bar_thread_selection_widget.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- model/lib/email/presentation_email.dart
#1142 
https://user-images.githubusercontent.com/43041967/200782588-31137bf4-b9d2-4024-969d-6211c92d7997.mov
> TF-1142 Fix bug mark draft mail as read, and remove read/unread button from draft mail

- lib/features/base/mixin/handle_error_mixin.dart
- lib/features/mailbox/data/datasource/mailbox_datasource.dart
- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/datasource_impl/mailbox_datasource_impl.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/repository/mailbox_repository.dart
- lib/features/mailbox/domain/usecases/delete_multiple_mailbox_interactor.dart
- model/lib/error_type_handler/set_method_error_handler_mixin.dart
- model/pubspec.lock
- pubspec.lock
- test/features/base/mixin/handle_error_mixin_test.dart
https://user-images.githubusercontent.com/107173849/201033786-033d5fb8-dcc9-46ee-b2c1-858ea6cfd21b.mov
> #1008 Add handler for SetError

- core/lib/utils/double_convert.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/quotas/data/network/quotas_api.dart
- lib/features/quotas/presentation/model/quotas_state.dart
- lib/features/quotas/presentation/quotas_controller.dart
- lib/features/quotas/presentation/quotas_controller_bindings.dart
- lib/features/quotas/presentation/widget/quotas_footer_widget.dart
- pubspec.lock
https://user-images.githubusercontent.com/107173849/201812738-be00e797-5217-42cc-ad2d-e8adf52a65cc.mov
> TF-1014: change validate enableShowQuotas

- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
#1149 
https://user-images.githubusercontent.com/43041967/201024830-001f8dd5-534a-46e0-b2c2-2dc35bf919d8.mp4
https://user-images.githubusercontent.com/43041967/202349733-c0a45af9-5311-42c6-a645-e1d33fd7bcc7.mov
> TF-1149 Fix bug Swipe right when opening mail leads to a random screen

- lib/features/email/presentation/email_view.dart
#1200 
https://user-images.githubusercontent.com/80730648/202366451-74519dbe-033c-4616-9c03-5bff8a55225f.mp4
> TF-1200 Fix sent mails do not show the `CC/BCC` info

- lib/features/base/base_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
https://user-images.githubusercontent.com/80730648/202425627-c10a31d1-e3f2-4b39-860f-d086673f8481.mov
> TF-1180 [Read receipt] Wrong content

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- pubspec.yaml
- Fix Android: store new requirements
> Release v0.4.3

- .github/workflows/analyze-test.yaml
The analyze action was updated to remove `analysis-options-file`.
> Removed unsupported input

- core/lib/presentation/utils/html_transformer/html_event_action.dart
- core/lib/presentation/utils/html_transformer/html_utils.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- lib/features/email/presentation/controller/email_supervisor_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
#1203
<table style="width:100%">
<tr>
<th>Android</th>
<th>iOS</th>
</tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/80730648/204457586-d4fdad6f-ac2a-4314-bfca-51c28f00704d.mov" /></td>
<td><video src="https://user-images.githubusercontent.com/80730648/204457725-98e20a08-e9c8-439e-81e1-5212642d5ff1.mp4" /></td>
</tr>
</table>
> TF-1203: Can not scroll horizontal email content

- docs/configuration/fcm_configuration.md
- lib/features/base/base_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/domain/exceptions/fcm_exception.dart
- lib/features/push_notification/presentation/services/fcm_receiver.dart
- web/firebase-messaging-sw.js
- web/index.html
https://user-images.githubusercontent.com/107173849/204537950-c37b427b-17c0-4722-88f0-5a1c5bec34b3.mov
https://user-images.githubusercontent.com/107173849/204726794-8064135f-8d55-47fe-a4bd-b83febf302b4.mov
> TF-1246: Enable FCM for Web browser

- .github/workflows/analyze-test.yaml
- .github/workflows/ci.yaml
> Added firebase setup to workflows

- lib/features/mailbox_dashboard/presentation/controller/custom_tf_tag_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
https://user-images.githubusercontent.com/107173849/205687424-5b46d074-5796-4105-a4ef-5fc7f84c6de1.mov
> TF-1260: auto-complete dont input the final email

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_tree.dart
- lib/features/thread/presentation/thread_controller.dart
#1243 
https://user-images.githubusercontent.com/80730648/205819032-95e79fca-6250-4d84-916c-883fda86d4f8.mov
> TF-1243 Fix move to after advance search result list went blank

- lib/features/email/presentation/controller/email_supervisor_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/model/page_view_navigator_state.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/search/presentation/search_email_controller.dart
- lib/features/search/presentation/search_email_view.dart
- lib/features/thread/presentation/extensions/list_presentation_email_extensions.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/list_presentation_email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
#1270 
https://user-images.githubusercontent.com/80730648/206067259-484b72b4-efc1-46a1-a20b-ae459f7b4448.mov
> TF-1270 Click on an email then another email open

- core/lib/presentation/extensions/string_extension.dart
- core/test/presentation/extensions/string_extension_test.dart
> TF-1233 Fix error out of range in create avatar icon

- ios/fastlane/Fastfile
To match the naming convention
> Aligned provisioning profile name

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/model/dashboard_routes.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
#284 
https://user-images.githubusercontent.com/43041967/205993197-1c3d4349-9a07-4ab6-a99e-3fc13be2df9e.mp4
https://user-images.githubusercontent.com/43041967/206399356-37f3afa1-2d25-4f99-a9a4-434db2074334.mp4
https://user-images.githubusercontent.com/43041967/206141908-a4def833-ba1e-4f54-b125-3f6530200baf.mp4
> TF-284 open mail from notification

- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
Resolved:
https://user-images.githubusercontent.com/6462404/206617394-154eef1d-5a9d-4375-93bd-47d21b9b238c.mov
> TF-1231 When remove Subject in AdvancedSearch, filter is not updated because it is empty

- env.file
- ios/Podfile.lock
- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- pubspec.lock
- pubspec.yaml
https://user-images.githubusercontent.com/107173849/206820364-9e418acd-6642-416b-b666-687204c84320.mov
https://user-images.githubusercontent.com/107173849/206820447-360a8203-3f36-4295-9dbe-097da0841de1.MP4
https://user-images.githubusercontent.com/107173849/206851949-3d8bb331-b6d7-4496-8c4e-04d472c127b6.MP4
> TF-1248: enable handle push notification IOS

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
#1306 
https://user-images.githubusercontent.com/80730648/208588559-9e62f03e-a9c5-46b9-9631-921a7024b14a.mp4
> TF-1306 Fix auto suggestion list doesn't close when finishing typing

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- lib/features/email/presentation/controller/email_supervisor_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
#1330 
- Android Mobile
https://user-images.githubusercontent.com/80730648/208636942-0e415cf8-89d1-4f4e-9f92-9a99e581c8f0.mov
- iOS Mobile
https://user-images.githubusercontent.com/80730648/208637021-da52c640-0555-4809-8a1a-755b22ca9835.mp4
- iOS iPad
https://user-images.githubusercontent.com/80730648/208637105-afe41ee4-e81e-4d1c-88d7-5083d1c381ff.mov
> TF-1330 Fix can not swipe left/right in email view on mobile

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
#1319 
https://user-images.githubusercontent.com/80730648/208858841-0f5ddd76-290e-4df6-8414-cc8827546987.mp4
> TF-1319 Fix mail body scroll long blank gap

- docs/stories/read-mails/README.md
- Create folder read-mails and README.md file
> Create folder Read-mails

- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
#1358 
https://user-images.githubusercontent.com/80730648/209789419-b1c05ac5-1d8c-4b96-9dab-99f78c60d4ab.mov
> TF-1358 Fix can not use advanced search in email view

- lib/features/base/base_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
#1369 
https://user-images.githubusercontent.com/80730648/210320423-67225e82-1dec-4cf9-8f31-4ed53dfff2c9.mov
> TF-1369 Fix [FCM] Unsupported operation Platform

- lib/features/base/base_controller.dart
- lib/features/network_status_handle/presentation/network_connnection_controller.dart
- lib/main/exceptions/remote_exception.dart
- lib/main/exceptions/remote_exception_thrower.dart
#1361 
https://user-images.githubusercontent.com/80730648/210474895-1f73c428-2433-41b2-afd2-e4defc2676d0.mp4
> TF-1361 Fix open notification while no network connection

- lib/features/base/reloadable/reloadable_controller.dart
TF-1289-PartII : Handle destroy subscription when logout OIDC
> TF-1289-PartII : Handle destroy subscription when logout OIDC

- lib/features/email/presentation/action/email_ui_action.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox/presentation/action/mailbox_ui_action.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/action/dashboard_action.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/push_notification/presentation/config/fcm_configuration.dart
- lib/features/push_notification/presentation/controller/fcm_controller.dart
- lib/features/push_notification/presentation/controller/fcm_token_handler.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/listener/mailbox_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- lib/features/push_notification/presentation/services/fcm_receiver.dart
- lib/features/push_notification/presentation/services/fcm_service.dart
- lib/features/search/presentation/search_email_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/main/utils/app_config.dart
- lib/main/utils/app_utils.dart
#1360 
- On Foreground & Background
https://user-images.githubusercontent.com/80730648/211258697-a46cf8ca-1f78-47c0-9133-05e5092f2ffc.mp4
- On Terminated
https://user-images.githubusercontent.com/80730648/211258664-d0ab5b82-d32c-4877-825a-937d4a89bf45.mov
> TF-1360 Fix can not load new email until reload mail list

- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/login_view_web.dart
- lib/features/login/presentation/privacy_link_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
> TF-1379 Add privacy policy in login screen

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/features/contact/presentation/widgets/autocomplete_contact_text_field_with_tags.dart
- pubspec.lock
#1153 
https://user-images.githubusercontent.com/80730648/212307877-7db47ff0-5de2-4d21-8f2d-b7adf2820487.mov
> TF-1153 Improve recipient input in composer

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/features/contact/presentation/widgets/autocomplete_contact_text_field_with_tags.dart
- pubspec.lock
#1296 
https://user-images.githubusercontent.com/80730648/212636119-412ea41e-5319-4a05-8dee-77fafee69a7b.mov
> TF-1296 Improve auto suggestion is still slow response

- lib/features/base/widget/email_avatar_builder.dart
- lib/features/base/widget/material_text_button.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_receiver_builder.dart
- lib/features/email/presentation/widgets/email_sender_builder.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
- lib/features/email/presentation/widgets/received_time_builder.dart
#1167 
https://user-images.githubusercontent.com/80730648/212867593-9345474b-7285-4dd4-9811-8b2411756a58.mov
https://user-images.githubusercontent.com/80730648/212868807-6d6d93b0-9207-4834-9965-6ff962fe7c55.mov
> TF-1167 Improve more button in recipients of EmailView

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- pubspec.lock
https://user-images.githubusercontent.com/80730648/213088148-10ec580c-3a1b-4347-9196-897fe5b45a3c.mp4
> [HOT] Fix some bug on latest version

- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/widgets/toolbar_rich_text_builder.dart
- lib/features/identity_creator/presentation/identity_creator_bindings.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/model/signature_type.dart
- lib/features/identity_creator/presentation/widgets/identity_input_field_builder.dart
- lib/features/identity_creator/presentation/widgets/set_default_identity_checkbox_builder.dart
- lib/features/manage_account/data/network/identity_api.dart
- lib/features/manage_account/domain/model/create_new_default_identity_request.dart
- lib/features/manage_account/domain/model/create_new_identity_request.dart
- lib/features/manage_account/domain/state/create_new_default_identity_state.dart
- lib/features/manage_account/domain/usecases/create_new_default_identity_interactor.dart
- lib/features/manage_account/domain/usecases/get_all_identities_interactor.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/identity_bindings.dart
- lib/features/manage_account/presentation/profiles/identities/identity_interactors_bindings.dart
- lib/features/manage_account/presentation/profiles/identities/utils/identity_utils.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/pages/app_pages.dart
- model/lib/identity/identity_request_dto.dart
- test/features/manage_account/identity/identity_utils_test.dart
Tablet: 
https://user-images.githubusercontent.com/43041967/212861232-dd36ab68-798a-428c-94d5-492967ade92e.mp4
Mobile:
https://user-images.githubusercontent.com/43041967/212862097-692f7b08-811c-4301-b7a5-87d196769c87.mp4
Web:
https://user-images.githubusercontent.com/43041967/212862375-ea4dc6a1-bdac-474b-b9f8-358362cf1dd9.mp4
> TF-1194: Apply new identity design to create identity screen

- lib/features/base/reloadable/reloadable_controller.dart
#1400 
https://user-images.githubusercontent.com/80730648/213133952-51267378-8057-4e0e-9db9-5dfba699c4bd.mov
> TF-1400 Fix can't logout when fcm disabled

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- model/lib/mailbox/presentation_mailbox.dart
Implement Refresh spam report
https://user-images.githubusercontent.com/99852347/213162962-1c6b0e54-a419-4eda-9d83-f3aaed7cefb2.mov
https://user-images.githubusercontent.com/99852347/213165293-4c9b3d3b-d482-48ec-94be-50733b1227f8.mov
> TF-1390: Implement Refresh spam report

- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/quotas/presentation/widget/quotas_footer_widget.dart
#1257 
https://user-images.githubusercontent.com/80730648/215067585-654057c8-261f-46cf-9786-3a7c91b0658f.mp4
> TF-1257 Resize to smaller quotas bar

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
#1288 
https://user-images.githubusercontent.com/80730648/215010598-b235326b-ba3c-4572-807e-f96a0f6a7b1a.mov
> TF-1288 Fix email detailed view automatically closes when focusing on composer's editor on the web

- lib/features/identity_creator/presentation/identity_creator_bindings.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/model/identity_creator_arguments.dart
- lib/features/manage_account/data/network/identity_api.dart
- lib/features/manage_account/domain/model/edit_default_identity_request.dart
- lib/features/manage_account/domain/model/edit_identity_request.dart
- lib/features/manage_account/domain/state/edit_default_identity_state.dart
- lib/features/manage_account/domain/usecases/edit_default_identity_interactor.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/identity_bindings.dart
- lib/features/manage_account/presentation/profiles/identities/identity_interactors_bindings.dart
- model/lib/extensions/identity_extension.dart
- model/pubspec.lock
https://user-images.githubusercontent.com/43041967/212958965-0dab45a0-9c14-4a4c-847f-79864fb50970.mp4
mobile: 
https://user-images.githubusercontent.com/43041967/213262942-ad0de76f-15cf-43fd-bc2f-693fe4d95fe2.mp4
> TF-1194 [Part II] Apply new identity design to edit identity screen

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
TF-1156: [Presentation] Auto scroll mailbox list while dragging and drop
Demo :
https://user-images.githubusercontent.com/99852347/215420738-7fcf7286-dab2-4288-a16f-f77649aa968f.mov
> TF-1156: [Presentation] Auto scroll mailbox list while dragging and drop

- lib/features/manage_account/domain/usecases/create_new_default_identity_interactor.dart
Before: 
https://user-images.githubusercontent.com/43041967/213383789-6d9fdada-f65a-4082-ae70-bfb41e5cd29e.mp4
After:
https://user-images.githubusercontent.com/43041967/213383923-9259613c-5647-4a3c-8a01-7fde691d2f70.mp4
> TF-1194 Fix create first default identity make a null identity

- lib/features/composer/domain/exceptions/send_email_exception.dart
- lib/features/composer/domain/exceptions/set_email_method_exception.dart
- lib/features/composer/domain/state/send_email_state.dart
- lib/features/composer/domain/usecases/save_email_as_drafts_interactor.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/domain/usecases/update_email_drafts_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/extensions/set_error_extension.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
> TF-1190 Handle `SetError` when send message

- lib/features/manage_account/presentation/profiles/identities/widgets/delete_identity_dialog_builder.dart
Resolved: 
https://user-images.githubusercontent.com/43041967/216816342-c996d3bd-bf39-454a-a7b6-d1e6f5b04e57.mp4
> fix mouse event captured by under signatureView in deleleDialogBuilder

- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/widgets/toolbar_rich_text_builder.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
#1418 
Resolved:
https://user-images.githubusercontent.com/43041967/216816038-9313d23e-e6fe-486d-b11b-b8eb5a172f56.mp4
> Improve UI ux for identity creator view web

- lib/features/base/base_mailbox_controller.dart
- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/mailbox/data/datasource/mailbox_datasource.dart
- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/datasource_impl/mailbox_datasource_impl.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/model/mailbox_subscribe_action_state.dart
- lib/features/mailbox/domain/model/mailbox_subscribe_state.dart
- lib/features/mailbox/domain/model/subscribe_mailbox_request.dart
- lib/features/mailbox/domain/repository/mailbox_repository.dart
- lib/features/mailbox/domain/state/subscribe_mailbox_state.dart
- lib/features/mailbox/domain/usecases/refresh_all_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/subscribe_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/main/localizations/app_localizations.dart
- model/lib/mailbox/presentation_mailbox.dart
- Set subscribeMailbox in UseCase and implement in Repository
- Implement `SetMailboxMethod` in `MailboxApi` to update property `isSubscribed` = false to hide mailbox
- Demo `WEB`
https://user-images.githubusercontent.com/99852347/217490928-57b91160-0bd4-414d-b887-e48d8567e557.mov
- Demo `Mobile`
[mobile.webm](https://user-images.githubusercontent.com/99852347/217492006-d934d5e6-d8e9-4747-9819-30df271ee2d0.webm)
> TF-1311:  Hide Team-Mailboxes in mailbox menu

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- model/lib/mailbox/presentation_mailbox.dart
> TF-1321 Handle read receipt email for team mailbox

- lib/features/mailbox/data/datasource/mailbox_datasource.dart
- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/datasource_impl/mailbox_datasource_impl.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/extensions/list_mailbox_id_extension.dart
- lib/features/mailbox/domain/model/subscribe_multiple_mailbox_request.dart
- lib/features/mailbox/domain/model/subscribe_request.dart
- lib/features/mailbox/domain/repository/mailbox_repository.dart
- lib/features/mailbox/domain/state/subscribe_mailbox_state.dart
- lib/features/mailbox/domain/state/subscribe_multiple_mailbox_state.dart
- lib/features/mailbox/domain/usecases/subscribe_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/subscribe_multiple_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- model/lib/mailbox/presentation_mailbox.dart
#1432 
- Mobile
https://user-images.githubusercontent.com/80730648/218031414-0d2ae7ea-59c5-4e80-ba46-53bbc3a73e09.mp4
- Web 
https://user-images.githubusercontent.com/80730648/218031576-9ad66528-4277-4fbd-85f3-3caafcb67627.mov
> TF-1432 Fix all child/grandchild mailboxes don't hide themselves when hiding parent mailbox

- lib/features/base/base_mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_tree_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/search/mailbox/presentation/search_mailbox_view.dart
- lib/features/search/mailbox/presentation/widgets/mailbox_searched_item_builder.dart
- model/lib/mailbox/presentation_mailbox.dart
#1436 
https://user-images.githubusercontent.com/80730648/218679391-9468bb82-f2e4-4bfe-9490-8d545cf5e006.mov
> TF-1436 Fix not showing Team-Mailbox when having children

- core/lib/presentation/views/button/button_builder.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/bottom_bar_selection_mailbox_widget.dart
- lib/features/mailbox/presentation/widgets/user_information_widget_builder.dart
- model/lib/extensions/list_presentation_mailbox_extension.dart
#1176 
https://user-images.githubusercontent.com/80730648/220032030-a72f12b1-f5ed-4013-b375-6d0c4f16829f.mp4
> TF-1176 Fix delete button is enable even when no mailbox is selected

- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
#1456 
https://user-images.githubusercontent.com/80730648/220502848-636b9038-80da-4d76-ab43-596e9885d282.mov
> TF-1456 Move messages in team-mailbox

- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- Issue
#1244
- Resolved
https://user-images.githubusercontent.com/99852347/220825970-09b92bc1-6572-455f-8849-8e919aadf29b.mov
> TF-1244: Image get the resized value when open from draft

- lib/features/composer/presentation/composer_controller.dart
#1479
Resolved :
Check to, cc, bcc email
https://user-images.githubusercontent.com/99852347/221089878-4ac33407-8ace-4bb8-a5e7-2a2e9f4488b0.mp4
> TF-1479: Check verify toEmail when click to sent email

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/thread/presentation/thread_view.dart
Update the compose icon to display stably
#1475
https://user-images.githubusercontent.com/99852347/220513662-dc045233-22b4-4af0-9e8e-162e64d985ec.mp4
Update scroll suggestion of options once click expand icon to the mailbox list
#1468
`MOBILE`
https://user-images.githubusercontent.com/99852347/220513883-fc8ce104-195f-4eb8-8cf5-5340f62ed680.mp4
`WEB`
https://user-images.githubusercontent.com/99852347/220513899-fb871fe9-98eb-4eb6-be53-75c5ebea7356.mov
> TF-1468: Trigger scroll mailbox

- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
#1478
Update menu option when long press action
https://user-images.githubusercontent.com/99852347/220809450-62453a7e-e09d-4f54-a3b5-4dec8acd5a12.mp4
Update for other mailboxes
https://user-images.githubusercontent.com/99852347/221137510-bdc3b12d-56d8-4d19-ae31-87f9615bcaa2.mp4
> TF-1478: Update menu option when long press action

- web/firebase-messaging-sw.js
#1508 
- Remove `setBackgroundMessageHandler`
> TF-1508 Remove `setBackgroundMessageHandler` not used

- core/lib/presentation/utils/app_toast.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
Issue
#1472
Resolved 
https://user-images.githubusercontent.com/99852347/221746283-c931af97-be51-4509-9dba-85180aa7b827.mp4
> TF-1472: Fixed popup when sending email should be displayed at the bottom of screen

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
#1513 
https://user-images.githubusercontent.com/80730648/221816377-c4f7806c-e224-4e56-afb2-de92dcd18760.mp4
> TF-1513 Rich text toolbar lost

- lib/features/base/widget/link_browser_widget.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_grid_dashboard_item.dart
#1510 
https://user-images.githubusercontent.com/80730648/222125615-d0b8627b-2baa-45a2-b368-e5aa2949f17d.mov
> TF-1510 Fix bad links in the app grid (right click)

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
#1521 
- Use `flutter_inappwebview: ^6.0.0-beta.22`
https://user-images.githubusercontent.com/80730648/222711072-32fecd1a-998e-4484-b37e-288f3270704f.mov
- Android version `29, 31`
> TF-1521 Fix can not scroll to see long email body

- Dockerfile
Currently we're in process of upgrading flutter, so only a PR draft for now.
> Switched to a dedicated flutter base image

- pubspec.lock
- pubspec.yaml
#1527 
https://user-images.githubusercontent.com/80730648/223058618-558aafb1-cc76-4bb5-936c-d2ff0b21732c.mov
> TF-1527 Focus still in the same fields to continue add other email

- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/thread/presentation/thread_view.dart
#1535 
https://user-images.githubusercontent.com/80730648/223321307-5c8c40c1-7f4d-4bd4-be1c-853a27bbea7d.mp4
> TF-1535 Fix cannot scroll to view email list on responsive version browser

- lib/features/composer/presentation/composer_controller.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/main/utils/email_receive_manager.dart
- pubspec.lock
- pubspec.yaml
`Issues`
#1520 
#1523 
Resolved 
Update lib [https://github.com/KasemJaffer/receive_sharing_intent/pull/245](url)
```
- Upgrade `compileSdkVersion` ver 31
- Handle case `Intent.ACTION_SENDTO` action and scheme is `"mailto" == intent.scheme`
- Handle case share `text/plain`
- Handle case share `text/v-card` from Contact Android Phone
```
`DEMO FOR SHARE FILE`
https://user-images.githubusercontent.com/99852347/223190273-30090c27-fd85-41b9-aa55-efc2ac2c6f96.mp4
`SHARE TEXT/PLAIN, TEXT/V-CARD, SENTO EMAILTO`
https://user-images.githubusercontent.com/99852347/223190767-f3885097-49d8-4a58-8600-c0cfe366463e.mp4
https://user-images.githubusercontent.com/99852347/223190829-b474c1b4-5d08-4ce5-9528-99b404f2b27c.mp4
> Handle some cases about share intent from android phone

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
> TF-1546 Fix auto trim blank space after create tag email

- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- lib/features/thread/presentation/thread_controller.dart
#1561 
- Due upgrade flutter to version `v.3.7.5`
https://user-images.githubusercontent.com/80730648/223625865-0ff5bfe5-4b84-421a-97a2-6f40e6fe9f6e.mov
> TF-1561 Fix crash when click search on browser

- core/lib/utils/linkify_html.dart
- core/test/linkify_html_test.dart
#1162 
https://user-images.githubusercontent.com/80730648/224201243-1e7d5fae-d037-424e-8e2b-037dd85b4405.mov
https://user-images.githubusercontent.com/80730648/224201340-101ce203-99fe-4077-8a81-3cbedf876bed.mov
> TF-1162 Got the open link bug again

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- pubspec.lock
- pubspec.yaml
#1576 
https://user-images.githubusercontent.com/80730648/224215916-7b58ceea-4f20-4eca-835f-845f24945ced.mov
> TF-1576 Fix can not select suggestion email by mouse clicking

- lib/features/composer/presentation/composer_controller.dart
- model/lib/extensions/list_email_address_extension.dart
Issue
#1466 
Resolved
https://user-images.githubusercontent.com/99852347/224017779-b25e1038-6848-48f3-9908-f6456177e0ac.mp4
> TF1446: Remove filter email address when reply, reply all

- lib/features/manage_account/presentation/email_rules/widgets/email_rules_header_widget.dart
Issues: #1549
RESOLVED
https://user-images.githubusercontent.com/99852347/224086559-cf80005b-8411-4e6a-88ea-5c39f81e4b0a.mov
`RESPONSIVE`
https://user-images.githubusercontent.com/99852347/224217705-8bb46483-0bb7-4548-aa07-f143933d1cd6.mov
> TF1549: Fix UI when change languages for email rules header

- core/lib/presentation/state/failure.dart
- lib/features/base/base_controller.dart
- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/email/presentation/email_bindings.dart
- lib/features/home/presentation/home_bindings.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/login/presentation/login_bindings.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/push_notification/presentation/controller/fcm_controller.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/session/presentation/session_page_bindings.dart
- lib/features/thread/presentation/thread_bindings.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/bindings/credential/credential_bindings.dart
- lib/main/exceptions/remote_exception.dart
- lib/main/exceptions/remote_exception_thrower.dart
- lib/main/localizations/app_localizations.dart
- prebuild.sh
https://user-images.githubusercontent.com/6462404/222678181-e5e97d2b-9302-438d-8707-02654a6c717b.mov
https://user-images.githubusercontent.com/6462404/222678308-d39e9c3f-2ed4-4ce3-afce-c983f14015ce.mov
https://user-images.githubusercontent.com/6462404/222678506-b1bec6f7-5725-464a-89c4-39189bb2d342.mov
> Refactor bad credentials error handler

- lib/features/composer/presentation/composer_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
Issues:
#1537 
#1574 
RESOLVE 
`DEMO FOR #1537 `
[device-2023-03-12-005024.webm](https://user-images.githubusercontent.com/99852347/224504305-b1a597ff-fd7d-434c-b4b9-1ccf1488110d.webm)
https://user-images.githubusercontent.com/99852347/224504202-09964718-88ae-4360-947b-fa4bd5046e5c.mp4
`DEMO FOR #1574 `
https://user-images.githubusercontent.com/99852347/224504278-db20b4d6-b9a9-4ac0-88fe-f2eac0d87e21.mov
> TF-1537: Fix UI scroll bar destination picker

- lib/features/mailbox_dashboard/presentation/controller/custom_tf_tag_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/text_field_auto_complete_email_adress.dart
Allow use space when type email:
https://user-images.githubusercontent.com/107173849/223639007-ee57d68d-ae15-4219-ad90-fa2731cf7749.mov
Hide suggestion box after select item suggestion:
https://user-images.githubusercontent.com/107173849/224594851-5990516f-49b0-48dc-b3ef-8261d68324f1.mov
> TF-1539: System auto detect the searching keyword once user press space

- lib/features/composer/presentation/controller/rich_text_web_controller.dart
Issue: #1473 
Resolved
`WEB and Desktop`
https://user-images.githubusercontent.com/99852347/225194175-f9304081-8bdc-4d26-a420-4717949a725f.mov
`Responsive for mobile`
https://user-images.githubusercontent.com/99852347/225194738-d2521c1c-e734-4ac7-8377-61bb7a6e71c9.mov
> TF1473: Fixed cursor of typing when insert a image

- core/lib/presentation/extensions/html_extension.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/email/data/datasource/html_datasource.dart
- lib/features/email/data/datasource_impl/html_datasource_impl.dart
- lib/features/email/data/local/html_analyzer.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/usecases/get_email_content_interactor.dart
- pubspec.lock
#1371 
https://user-images.githubusercontent.com/80730648/225213052-0c3b99d2-df55-41e3-8a72-d7cd59f642de.mov
> TF-1371 Update position of Identity in `reply/forward` email

- lib/features/base/mixin/mailbox_action_handler_mixin.dart
- lib/features/mailbox/domain/extensions/presentation_mailbox_extension.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/search/mailbox/presentation/widgets/mailbox_searched_item_builder.dart
#1201 
https://user-images.githubusercontent.com/80730648/225610335-08ecaac7-4c8e-4c7b-81f4-f522c3205687.mov
> TF-1201 Support right-click to open browser context menu

- lib/features/manage_account/presentation/forward/forward_view.dart
issue: #1548 
`Resolved`
https://user-images.githubusercontent.com/99852347/225802386-3c1bb10f-e3ff-43e8-a108-cbd82860be07.mov
> TF-1548: Hide switch icon when list forward is empty

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
Issue: #1616 
`Resolved` 
https://user-images.githubusercontent.com/99852347/225856321-5e0dd521-a091-4d09-8e48-c287c45b0394.mov
> TF-1616: Fix drag and drop email to mailbox

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- pubspec.lock
Need merge https://github.com/linagora/enough_html_editor/pull/19 before review
- Device small:
https://user-images.githubusercontent.com/107173849/225802456-3b61dc9b-03f8-4e8d-82d5-3a84a3510c68.mov
- Device big:
https://user-images.githubusercontent.com/107173849/225802483-9fbecfbe-6116-4df9-ad4d-8d07de615681.mov
- landscape mode :
https://user-images.githubusercontent.com/107173849/225812007-47928546-21d4-493f-833d-bbf683a7a84c.mov
- double cursor Android:
https://user-images.githubusercontent.com/107173849/225825188-13fa8e7c-fcfb-47c3-9b7c-4a313e1aa24f.mp4
> TF-1573: Cursor auto move while typing

- contact/pubspec.lock
- contact/pubspec.yaml
- core/pubspec.lock
- core/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- lib/features/base/mixin/date_range_picker_mixin.dart
- model/pubspec.lock
- model/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
#997 
- Need merged:  https://github.com/linagora/flutter-date-range-picker/pull/3
https://user-images.githubusercontent.com/80730648/226266804-671ac177-aeb6-4af5-a1f8-e813edffe30b.mp4
> TF-997 Custom date ranges

- core/lib/core.dart
- core/lib/data/network/config/dynamic_url_interceptors.dart
- core/lib/presentation/extensions/uri_extension.dart
- core/lib/presentation/extensions/url_extension.dart
- core/test/presentation/extensions/uri_extension_test.dart
- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/session/presentation/session_controller.dart
- model/lib/extensions/session_extension.dart
> TF-1606 Handle relative url in session

- contact/pubspec.lock
- core/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/thread/data/extensions/email_cache_extension.dart
- lib/features/thread/data/extensions/email_extension.dart
- lib/features/thread/data/network/thread_isolate_worker.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/network/network_isolate_binding.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/list_email_extension.dart
- model/lib/extensions/list_presentation_email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- test/fixtures/email_fixtures.dart
#1626 
- Need merged: https://github.com/linagora/jmap-dart-client/pull/58
> TF-1626 Remove `id` of email when call `Email/set` method

- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/data/datasource/identity_data_source.dart
- lib/features/manage_account/data/datasource_impl/identity_data_source_impl.dart
- lib/features/manage_account/data/network/identity_api.dart
- lib/features/manage_account/data/repository/identity_repository_impl.dart
- lib/features/manage_account/domain/repository/identity_repository.dart
- lib/features/manage_account/domain/usecases/create_new_default_identity_interactor.dart
- lib/features/manage_account/domain/usecases/create_new_identity_interactor.dart
- lib/features/manage_account/domain/usecases/delete_identity_interactor.dart
- lib/features/manage_account/domain/usecases/edit_default_identity_interactor.dart
- lib/features/manage_account/domain/usecases/edit_identity_interactor.dart
- lib/features/manage_account/domain/usecases/get_all_identities_interactor.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/mailbox_visibility/mailbox_visibility_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_view.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/main/error/capability_validator.dart
- model/lib/extensions/list_identity_id_extension.dart
- model/lib/model.dart
#1625 
https://user-images.githubusercontent.com/80730648/226580921-2d700669-5e17-4552-8b65-c10130761cb8.mov
> TF-1625 Not use `SortOrder` when not supported

- lib/features/base/base_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/manage_account/presentation/base/setting_detail_view_builder.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/mailbox_visibility/bindings/mailbox_visibility_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_bindings.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_view.dart
- lib/features/manage_account/presentation/menu/widgets/account_menu_item_tile_builder.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/identity_bindings.dart
- lib/features/manage_account/presentation/profiles/profiles_bindings.dart
- lib/features/manage_account/presentation/profiles/profiles_controller.dart
- lib/features/manage_account/presentation/profiles/profiles_view.dart
- lib/features/manage_account/presentation/vacation/utils/vacation_utils.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_controller_bindings.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- lib/features/manage_account/presentation/vacation/widgets/vacation_notification_message_widget.dart
- lib/features/quotas/presentation/widget/quotas_warning_banner_widget.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/spam_report_banner_widget.dart
https://user-images.githubusercontent.com/80730648/227309480-49c72f1b-0440-48f9-b0be-b7f0797d3ecb.mov
> TF-1611 User got blocking once html type on vacation

- lib/features/manage_account/presentation/menu/settings/settings_view.dart
#1632 
https://user-images.githubusercontent.com/80730648/227422054-a7fd7e33-66da-496f-ac02-9ffdbf89ba33.mov
> TF-1632 Fix elements are cut in each other in language and region

- contact/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/email/data/network/email_api.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/quotas/presentation/quotas_controller.dart
- model/lib/extensions/list_presentation_mailbox_extension.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- test/fixtures/session_fixtures.dart
- test/main/error/capability_validator_test.dart
- Need merge: https://github.com/linagora/jmap-dart-client/pull/59
> TF-1645 Fix can not parse mail capability

- lib/features/thread/presentation/thread_controller.dart
- pubspec.yaml
- Fix infinite scroll is broken
> Release v0.7.6

- .github/workflows/image.yaml
We should add our Docker Hub credentials to secrets if we are using this. The secret keys should be `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.
> Added Docker image build to CI

- lib/features/mailbox_dashboard/presentation/controller/spam_report_controller.dart
#1598 
https://user-images.githubusercontent.com/80730648/227842655-41460189-f560-4ff3-b7ce-76abf3debc52.mp4
> TF-1598 Mark emails in the spam box as seen when dismiss banner

- lib/features/base/base_controller.dart
- lib/features/login/data/datasource/authentication_oidc_datasource.dart
- lib/features/login/data/datasource_impl/authentication_oidc_datasource_impl.dart
- lib/features/login/data/network/authentication_client/authentication_client_base.dart
- lib/features/login/data/network/authentication_client/authentication_client_mobile.dart
- lib/features/login/data/network/authentication_client/authentication_client_web.dart
- lib/features/login/data/network/oidc_http_client.dart
- lib/features/login/data/repository/authentication_oidc_repository_impl.dart
- lib/features/login/domain/repository/authentication_oidc_repository.dart
- lib/features/manage_account/domain/usecases/log_out_oidc_interactor.dart
- model/lib/model.dart
- model/lib/oidc/response/oidc_discovery_response.dart
https://user-images.githubusercontent.com/6462404/227988875-79496b19-a2f1-4ae3-9000-379339bb465c.mov
> Single logout 

- lib/features/base/base_controller.dart
- lib/features/push_notification/presentation/action/fcm_action.dart
- lib/features/push_notification/presentation/controller/fcm_base_controller.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/controller/fcm_token_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- lib/features/push_notification/presentation/services/fcm_receiver.dart
- lib/features/push_notification/presentation/services/fcm_service.dart
- lib/features/push_notification/presentation/utils/fcm_utils.dart
- lib/main/bindings/session/session_bindings.dart
#1631 
In `onBackgroundMessage` mode from FCM
- Because some classes in `BaseController` have not yet been `bindings` but are directly declared and used `Get.find()`
- Value `Session is null`
> TF-1631 User cannot receive new email notification

- pubspec.lock
TF-1666: Update rich text composer lib for support hide keyboard on android 
[device-2023-03-29-130543.webm](https://user-images.githubusercontent.com/99852347/228462851-44b49890-0f74-4c15-a846-620eb3149f71.webm)
> TF-1666: Update rich text composer lib for support hide keyboard

- android/app/src/main/AndroidManifest.xml
#1569 
- Before
https://user-images.githubusercontent.com/80730648/228727077-63cb4763-cb0a-4ebd-a2c9-b112d5e6e228.mov
- After
https://user-images.githubusercontent.com/80730648/228726882-2d0b5766-7adf-49a6-a891-77bd4f7d491f.mov
> TF-1569 Fix android system keeps showing an app that run at background

- docs/adr/0019-conventions-for-display-push-notifications.md
- lib/features/push_notification/data/repository/fcm_repository_impl.dart
- lib/features/push_notification/domain/repository/fcm_repository.dart
- lib/features/push_notification/domain/state/get_mailboxes_not_put_notifications_state.dart
- lib/features/push_notification/domain/usecases/get_mailboxes_not_put_notifications_interactor.dart
- lib/features/push_notification/domain/utils/fcm_constants.dart
- lib/features/push_notification/presentation/bindings/fcm_interactor_bindings.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/list_presentation_email_extension.dart
- model/lib/extensions/list_presentation_mailbox_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/lib/mailbox/presentation_mailbox.dart
#1600 
https://user-images.githubusercontent.com/80730648/228835213-e68c0724-6795-4304-8f5d-bbfacb356871.mp4
> TF-1600 No notification for content of `Draft, Sent, Outbox, Spam, Trash`

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/widgets/identity_input_with_drop_list_field_builder.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identities_radio_list_builder.dart
- Issues: 
1. #1679 
2. #1693 
- Resolved:
https://user-images.githubusercontent.com/99852347/229974473-e32061a2-adb2-4ab7-bf44-82dc4a7247c2.mp4
[device-2023-04-05-102307.webm](https://user-images.githubusercontent.com/99852347/229974576-a58c5a11-97a2-40a4-9131-395bab164b33.webm)
- Responsive for language is a long text
> Fix bug UI when create identity

- core/lib/data/model/source_type/data_source_type.dart
- lib/features/mailbox/data/local/mailbox_cache_manager.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/data/datasource/spam_report_datasource.dart
- lib/features/mailbox_dashboard/data/datasource_impl/share_preference_spam_report_data_source_impl.dart
- lib/features/mailbox_dashboard/data/datasource_impl/spam_report_cache_datasource_impl.dart
- lib/features/mailbox_dashboard/data/local/share_preference_spam_report_data_source.dart
- lib/features/mailbox_dashboard/data/repository/spam_report_repository_impl.dart
- lib/features/mailbox_dashboard/domain/exceptions/spam_report_exception.dart
- lib/features/mailbox_dashboard/domain/repository/spam_report_repository.dart
- lib/features/mailbox_dashboard/domain/state/get_spam_mailbox_cached_state.dart
- lib/features/mailbox_dashboard/domain/usecases/get_spam_mailbox_cached_interactor.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/spam_report_controller.dart
- lib/features/mailbox_dashboard/utils/mailbox_dashboard_constant.dart
- lib/main/localizations/app_localizations.dart
#1667 
https://user-images.githubusercontent.com/80730648/230027102-7180650f-0f23-45c6-954b-ef1a2a964f1d.mov
> TF-1667 Do not request spam on every email I move

- lib/features/contact/presentation/widgets/autocomplete_contact_text_field_with_tags.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/main/localizations/app_localizations.dart
- Issue:  #1677 
- Resolved 
`MOBILE`
https://user-images.githubusercontent.com/99852347/230036075-2fc6a809-a8eb-440f-8e24-2ccbc8818386.mp4
`WEB`
https://user-images.githubusercontent.com/99852347/230032258-3fb2f388-ec2e-44cd-b45f-105fff32d4cc.mov
> TF-1677: Fix validation for email forward

- CHANGELOG.md
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- issue:  #1699 
- Resolved:
`Desktop` 
https://user-images.githubusercontent.com/99852347/230058676-5d92fc34-b6de-4cf4-97f7-238efdd18725.mov
`Web`
https://user-images.githubusercontent.com/99852347/230058757-e6279d1c-ba4f-4bd3-9f9d-bae563173c18.mov
> TF-1699: Support hide suggestion when scrolling list email to, cc, bcc.

- CHANGELOG.md
- lib/l10n/intl_fr.arb
- lib/l10n/intl_it.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
> TF-1681: Add a dot at the end of the description

- CHANGELOG.md
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
> TF-1687: Set name email and counter displayed in a single line

- CHANGELOG.md
- lib/features/composer/presentation/composer_view_web.dart
- Issue: #1685 
- Resolved :
https://user-images.githubusercontent.com/99852347/230443759-dfcd7345-ae9e-44ef-85e5-803d242a04a3.mov
> TF-1685: Fix hover and click to button show all or hide attachments

- lib/features/composer/domain/model/email_request.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/domain/usecases/update_email_drafts_interactor.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/exceptions/email_exceptions.dart
- lib/features/email/domain/repository/email_repository.dart
#1749 
- Because the email is `destroyed` before it is successfully initialized, the `attachment` files cannot be found
https://user-images.githubusercontent.com/80730648/230602202-77c15737-3c6f-4cb0-b2ae-c69b70b6dbc5.mov
> TF-1749 Can not save draft and send email from draft mailbox

- CHANGELOG.md
- lib/features/base/base_controller.dart
- lib/features/push_notification/data/repository/fcm_repository_impl.dart
- lib/features/push_notification/domain/exceptions/fcm_exception.dart
- lib/features/push_notification/domain/repository/fcm_repository.dart
- lib/features/push_notification/domain/state/get_email_changes_to_push_notification_state.dart
- lib/features/push_notification/domain/state/get_email_changes_to_remove_notification_state.dart
- lib/features/push_notification/domain/usecases/get_email_changes_to_push_notification_interactor.dart
- lib/features/push_notification/domain/usecases/get_email_changes_to_remove_notification_interactor.dart
- lib/features/push_notification/presentation/action/fcm_action.dart
- lib/features/push_notification/presentation/bindings/fcm_interactor_bindings.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_config.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
#1599 
https://user-images.githubusercontent.com/80730648/230581002-6ff733e0-38ec-4f5b-8ff4-fbd662ef8d72.mp4
> TF-1599 Remove notification when read

- core/lib/presentation/extensions/html_extension.dart
#1655
https://user-images.githubusercontent.com/80730648/230864205-9ac99b19-9758-4459-8430-7b61d512cbe6.mov
> TF-1655 Fix add a line break after signature in composer

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- Issue: #1544 
- Resolved:
https://user-images.githubusercontent.com/99852347/231244910-a809c599-0655-4557-8e71-5a51533b6b72.mov
`These case fields are empty`
https://user-images.githubusercontent.com/99852347/231349407-6ad3ef5b-cb28-46cf-8e3e-739a280feae4.mov
> TF-1544: Support can `TAB` another field in composer

- android/app/src/main/AndroidManifest.xml
- configurations/app_dashboard.json
- core/lib/presentation/utils/app_toast.dart
- core/lib/presentation/views/text/slogan_builder.dart
- core/lib/presentation/views/toast/tmail_toast.dart
- docs/configuration/app_grid_configuration.md
- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/features/login/presentation/login_view_web.dart
- lib/features/login/presentation/privacy_link_widget.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
- lib/features/mailbox_dashboard/domain/app_dashboard/linagora_app.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_grid_dashboard_item.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_grid_dashboard_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/app_dashboard/app_list_dashboard_item.dart
- lib/features/manage_account/presentation/manage_account_dashboard_view.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/l10n/intl_messages.arb
- pubspec.lock
- pubspec.yaml
#1665 
- Android
https://user-images.githubusercontent.com/80730648/231087765-3651708e-84b5-4a5c-a121-7118f1583528.mov
- iOS
https://user-images.githubusercontent.com/80730648/231090625-de366503-607f-4b65-ae57-b2e8611ee920.mp4
- Web
https://user-images.githubusercontent.com/80730648/231088113-f61ff3a2-6e91-4e3d-a449-df9541b00ce8.mov
> TF-1665 Improve app grid on mobile and web

- docs/adr/0022-fix-double-vertical-scroll-bar-on-composer.md
- lib/features/composer/presentation/composer_controller.dart
- pubspec.lock
- pubspec.yaml
- Issues: #1740 
- Resolved :
- Need to merge  https://github.com/linagora/html-editor-enhanced/pull/11
`Mac OS`
https://user-images.githubusercontent.com/99852347/233457448-63800f06-df1c-4086-8349-51e99b42999d.mov
`Linux`
https://user-images.githubusercontent.com/99852347/233553849-b6319665-e72e-4c63-845d-df7ae5dcba49.mov
https://user-images.githubusercontent.com/99852347/233553903-27866b50-a24f-428b-a4de-69cfbf61e66f.mov
https://user-images.githubusercontent.com/99852347/233554183-11c569a9-b158-4c62-905f-592d849fbe36.mov
`Code View` Mode
https://user-images.githubusercontent.com/99852347/233694156-33cfa9bb-b329-42c7-91fe-667520842d58.mov
> TF-1740: Fix double vertical scroll bar on composer

- lib/features/composer/presentation/widgets/email_address_input_builder.dart
#1763 
https://user-images.githubusercontent.com/80730648/233897361-2f20ec81-c4a6-4c2f-88b0-bca8f68d4c29.mov
> TF-1763 Fix duplicated email suggestion in the list on composer

- lib/features/base/widget/material_text_icon_button.dart
- lib/features/contact/presentation/widgets/autocomplete_contact_text_field_with_tags.dart
- lib/features/manage_account/presentation/profiles/identities/identities_view.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identities_header_widget.dart
- #1711 
https://user-images.githubusercontent.com/80730648/233940278-dc4f3972-026c-442f-8828-c923c5fc21fc.mov
> TF-1711 Fix label displayed overlap the button with multiple language

- core/lib/presentation/extensions/string_extension.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/manage_account/presentation/email_rules/widgets/email_rule_item_widget.dart
- Issue:
-  #1687 
- EmailTitle is cut off at the wrong place
- #1385
- Resolved:
`WEB`
`MOBILE`
> TF-1687: Re-align title and unread count

- lib/features/contact/presentation/widgets/autocomplete_contact_text_field_with_tags.dart
- lib/features/contact/presentation/widgets/contact_input_tag_item.dart
- lib/main/utils/app_utils.dart
- test/main/utils/app_utils_test.dart
- Issue: #1677 
- Resolved: 
`WEB`
https://user-images.githubusercontent.com/99852347/234503747-db841c7f-cdca-41d9-b00e-16c95345fee5.mov
`Mobile`
https://user-images.githubusercontent.com/99852347/234503811-6fca2bfa-8fe9-4951-80b6-f2517b0025d5.mp4
> TF-1677: Support validation email for `something@localhost` case

- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/utils/app_toast.dart
- lib/features/base/mixin/mailbox_action_handler_mixin.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/search/mailbox/presentation/search_mailbox_controller.dart
- lib/main/localizations/app_localizations.dart
- model/lib/mailbox/presentation_mailbox.dart
#1792 
https://user-images.githubusercontent.com/80730648/236198607-48fc177e-1800-4da1-956d-c4123ab335ff.mov
> TF-1792 Add option `Empty Trash` for mailbox trash

- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- `#1735`
https://user-images.githubusercontent.com/80730648/236163527-185fc32c-59d5-476f-b867-634e9ec9c485.mov
- `#1803`
https://user-images.githubusercontent.com/80730648/236163636-ca21738a-b665-4f59-840c-bcb3b930deb4.mov
> TF-1735 Fix filter not applied to search

- lib/features/composer/presentation/composer_controller.dart
- lib/features/upload/domain/state/attachment_upload_state.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
> TF-1798 Fix error message is displayed behind the keyboard on IOS platform only

- lib/features/offline_mode/worker/hive_task.dart
- lib/features/offline_mode/worker/hive_task_state.dart
- lib/features/offline_mode/worker/hive_worker_queue.dart
- test/features/offline_mode/mailbox_state_worker_queue.dart
- test/features/offline_mode/woker_queue_test.dart
> TF-1821 Add work queue to handle sync task

- core/lib/utils/file_utils.dart
- core/pubspec.lock
- core/pubspec.yaml
- core/test/utils/file_utils_test.dart
> TF-1822 save string to file in internal storage mobile

- lib/features/destination_picker/presentation/widgets/destination_picker_search_mailbox_item_builder.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
#1815 
https://github.com/linagora/tmail-flutter/assets/80730648/c45abfb5-4baf-46b4-9c2d-f06aebaf6c80
> TF-1815 Move email improvement

- lib/features/push_notification/presentation/listener/email_change_listener.dart
#1811 
https://github.com/linagora/tmail-flutter/assets/80730648/019befec-7735-4799-9347-4872e5813635
> TF-1811 Store email when receive in background for Android

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
#1833 
https://github.com/linagora/tmail-flutter/assets/80730648/64afe18b-e3a7-4710-8076-6710dc4bd78e
> TF-1833 Fix the filter `From Me` condition is not working in quick search

- lib/features/base/widget/custom_scroll_behavior.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
#1832 
https://github.com/linagora/tmail-flutter/assets/80730648/ea5734fe-9736-4bf2-a30d-9c9dad212607
> TF-1832 Fix user cannot scroll to view other attachment file in hidden list by using mouse devices

- core/lib/utils/file_utils.dart
- core/test/utils/file_utils_test.dart
- lib/features/caching/clients/opened_email_hive_cache_client.dart
- lib/features/caching/utils/caching_constants.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/state/store_opened_email_to_cache_state.dart
- lib/features/email/domain/usecases/store_opened_email_to_cache_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_bindings.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/offline_mode/manager/detailed_email_cache_manager.dart
- lib/features/offline_mode/manager/opened_email_cache_manager.dart
- lib/features/offline_mode/manager/opened_email_cache_worker_queue.dart
- lib/features/push_notification/presentation/bindings/fcm_interactor_bindings.dart
- lib/main/bindings/local/local_bindings.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/email_extension.dart
- issues: #1808 
- Resolved
`IOS`
- First time
https://github.com/linagora/tmail-flutter/assets/99852347/a2773fb2-6d64-483c-8093-6a0313a7c6f0
- Secondary time (Duplicate)
https://github.com/linagora/tmail-flutter/assets/99852347/65d324d3-4177-457e-a81d-9fae36de2c9f
`Android`
- First time
https://github.com/linagora/tmail-flutter/assets/99852347/7429dbad-529a-4271-b955-7206703bb493
- Secondary time (Duplicate)
https://github.com/linagora/tmail-flutter/assets/99852347/f342bebb-1dc2-48c9-babe-a4a32a0a509a
> TF-1808 store n recently opened email in cache

- web/firebase-messaging-sw.js
- web/index.html
#1802 
- Miss an instance of Firebase Messaging so that it can handle background messages.
https://github.com/linagora/tmail-flutter/assets/80730648/34756683-af7e-4e31-9515-f8f403ca640c
> TF-1802 Fix FCM broken on web

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
#1707 
- Haven't disabled search when the search filter is empty
https://github.com/linagora/tmail-flutter/assets/80730648/4f3aab52-07df-4dbf-9986-3454f03b1b36
> TF-1707 Fix system not response correct result when user filter with Read/Unread email

- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/date_drop_down_button.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/text_field_auto_complete_email_adress.dart
#1844 
- Do focus on email list still exists.
https://github.com/linagora/tmail-flutter/assets/80730648/0051d32b-35fe-41a3-96cc-23f10534d552
> TF-1844 Fix auto open email when press enter on advanced search

- android/build.gradle
- core/lib/core.dart
- core/lib/utils/platform_info.dart
- docs/adr/0026-fix-horizontal-scroll-bar-in-email-detail-view.md
- docs/adr/0027-use-tuplekey-store-data-cache.md
- docs/adr/0028-use-work-manager-to-mange-task-scheduling.md
- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/features/offline_mode/config/work_manager_config.dart
- lib/features/offline_mode/config/work_manager_constants.dart
- lib/features/offline_mode/controller/work_scheduler_controller.dart
- lib/features/offline_mode/manager/work_dispatcher.dart
- lib/features/offline_mode/observer/sending_email_observer.dart
- lib/features/offline_mode/observer/work_observer.dart
- lib/features/offline_mode/scheduler/one_time_work_request.dart
- lib/features/offline_mode/scheduler/periodic_work_request.dart
- lib/features/offline_mode/scheduler/work_request.dart
- lib/features/offline_mode/scheduler/work_status.dart
- lib/features/offline_mode/scheduler/worker.dart
- lib/features/offline_mode/scheduler/worker_type.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
> TF-1861 Implement worker manager

- pubspec.lock
- pubspec.yaml
> TF-1883 Upgrade version flutter-typeahead

- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- pubspec.lock
#1851 
#1852 
- Need merged [html-editor-enhanced-PR#2](https://github.com/linagora/html-editor-enhanced/pull/12)
https://github.com/linagora/tmail-flutter/assets/80730648/c7dbe4e9-17b7-499b-a42c-5e0a61ad9576
> TF-1851, 1852 Selected `rich text menu` do not match current text status

- lib/features/base/base_controller.dart
- lib/features/composer/domain/extensions/sending_email_extension.dart
- lib/features/composer/domain/model/sending_email.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/state/delete_sending_email_state.dart
- lib/features/email/domain/usecases/delete_sending_email_interactor.dart
- lib/features/login/data/local/authentication_info_cache_manager.dart
- lib/features/login/data/repository/credential_repository_impl.dart
- lib/features/login/domain/repository/credential_repository.dart
- lib/features/login/domain/usecases/get_authenticated_account_interactor.dart
- lib/features/login/domain/usecases/get_credential_interactor.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/offline_mode/biding/sending_email_biding.dart
- lib/features/offline_mode/controller/work_scheduler_controller.dart
- lib/features/offline_mode/exceptions/workmanager_exception.dart
- lib/features/offline_mode/manager/sending_email_cache_manager.dart
- lib/features/offline_mode/observer/sending_email_observer.dart
- lib/features/offline_mode/observer/work_observer.dart
- lib/features/push_notification/presentation/notification/local_notification_config.dart
- lib/main.dart
- lib/main/localizations/app_localizations.dart
- issue: #1842 
- Resolved:
**`Foreground `**
https://github.com/linagora/tmail-flutter/assets/99852347/16b8352b-ac0d-427b-88e4-1d55c585e12a
`OIDC`
https://github.com/linagora/tmail-flutter/assets/99852347/f17b0584-5cd6-4399-a1cd-513f6d571f74
**`Background`**
https://github.com/linagora/tmail-flutter/assets/99852347/002ee80a-c001-4144-afb8-1d798c65d771
**`TERMINATED`**
https://github.com/linagora/tmail-flutter/assets/99852347/98e8abc1-4136-452a-a5e4-6f6fbd1cf92e
> TF-1842: handle task in worker manager

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- issue: #1864 
- Resolved:
`Android`
https://github.com/linagora/tmail-flutter/assets/99852347/89503739-bf13-404d-a62a-24c190cb80d5
`Ios`
https://github.com/linagora/tmail-flutter/assets/99852347/785766c5-7483-48e4-b5a6-00720cfbc40d
> TF-1864: disable upload actions in composer while no connection

- CHANGELOG.md
- pubspec.lock
- pubspec.yaml
- Upgrade version flutter-typeahead
> Release v0.7.11

- lib/features/base/isolate/isolate_manager.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/offline_mode/exceptions/workmanager_exception.dart
- lib/features/offline_mode/manager/sending_email_cache_manager.dart
- lib/features/offline_mode/observer/sending_email_observer.dart
- lib/features/offline_mode/scheduler/worker_state.dart
- lib/features/sending_queue/data/repository/sending_queue_repository_impl.dart
- lib/features/sending_queue/domain/repository/sending_queue_repository.dart
- lib/features/sending_queue/domain/usecases/get_all_sending_email_interactor.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/sending_queue/presentation/utils/sending_queue_isolate_manager.dart
- lib/main/bindings/core/core_bindings.dart
#1900 
https://github.com/linagora/tmail-flutter/assets/80730648/31b6d8a7-97e7-42c1-ac5e-1f4b099ca8be
> TF-1900 Auto sync sending queue

- lib/features/composer/domain/extensions/sending_email_extension.dart
- lib/features/composer/domain/model/sending_email.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/offline_mode/controller/work_scheduler_controller.dart
- lib/features/sending_queue/data/repository/sending_queue_repository_impl.dart
- lib/features/sending_queue/domain/repository/sending_queue_repository.dart
- lib/features/sending_queue/domain/state/delete_multiple_sending_email_state.dart
- lib/features/sending_queue/domain/usecases/delete_multiple_sending_email_interactor.dart
- lib/features/sending_queue/domain/usecases/delete_single_sending_email_interactor.dart
- lib/features/sending_queue/presentation/bindings/sending_queue_bindings.dart
- lib/features/sending_queue/presentation/bindings/sending_queue_interactor_bindings.dart
- lib/features/sending_queue/presentation/extensions/list_sending_email_extension.dart
- lib/features/sending_queue/presentation/model/sending_email_action_type.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/sending_queue/presentation/sending_queue_view.dart
- lib/features/sending_queue/presentation/widgets/app_bar_sending_queue_widget.dart
- lib/features/sending_queue/presentation/widgets/bottom_bar_sending_queue_widget.dart
- lib/features/sending_queue/presentation/widgets/sending_email_tile_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#1866 
https://github.com/linagora/tmail-flutter/assets/80730648/a60793c4-47df-426c-9d76-e34fc9d3242b
> TF-1866 Delete sending email in sending queue

- core/lib/utils/file_utils.dart
- lib/features/base/base_controller.dart
- lib/features/caching/caching_manager.dart
- lib/features/caching/utils/caching_constants.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/offline_mode/manager/sending_email_cache_manager.dart
- lib/main/bindings/local/local_bindings.dart
> TF-1839 Clean all offline cache after logout

- docs/stories/TF-1786-TeamMail-Swipe-in-Email-item-in-ThreadView .md
@hoangdat please review it @dieptran88 
- For now, The swipe action is setting default as mentioned in PR.
- The swipe option setting in Account Manage / Swipe Configuration will be upcoming in other story.
> Create TF-1786-TeamMail-Swipe-in-Email-item-in-ThreadView .md

- Dockerfile
resolve https://github.com/linagora/tmail-flutter/issues/1918
```
-rw-r--r-- 1 root root 17748811 May 15 02:35 main.dart.js
-rw-r--r-- 1 root root  2687864 May 15 02:35 main.dart.js.gz
-rw-r--r-- 1 root root    59808 May 15 02:35 main.dart.js_1.part.js
-rw-r--r-- 1 root root     9731 May 15 02:35 main.dart.js_1.part.js.gz
-rw-r--r-- 1 root root   315200 May 15 02:35 main.dart.js_10.part.js
-rw-r--r-- 1 root root    42360 May 15 02:35 main.dart.js_10.part.js.gz
-rw-r--r-- 1 root root      870 May 15 02:35 main.dart.js_2.part.js
-rw-r--r-- 1 root root      470 May 15 02:35 main.dart.js_2.part.js.gz
-rw-r--r-- 1 root root     1340 May 15 02:35 main.dart.js_3.part.js
-rw-r--r-- 1 root root      681 May 15 02:35 main.dart.js_3.part.js.gz
-rw-r--r-- 1 root root   689363 May 15 02:35 …
```
> Dockerfile - Add new stage for minify js file

- lib/features/composer/presentation/base_composer_view.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/email/presentation/widgets/attachment_file_tile_builder.dart
> [HOT-FIX] Release version `v0.8.1`

- CHANGELOG.md
- lib/features/composer/presentation/base_composer_view.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/email/presentation/widgets/attachment_file_tile_builder.dart
- pubspec.yaml
> Release v0.8.2

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/composer/presentation/model/font_name_type.dart
#1878 
https://github.com/linagora/tmail-flutter/assets/80730648/b88cb3aa-f7a1-4f8e-9099-09cbdbdf6331
> TF-1878 Fix font family not changed correctly in composer

- lib/features/offline_mode/observer/sending_email_observer.dart
#1932 
https://github.com/linagora/tmail-flutter/assets/80730648/3fbf8aa3-e437-4088-8d3b-47a676eac8a0
> TF-1932 Turn off notifications after emailing

- lib/features/base/base_controller.dart
- lib/features/session/presentation/session_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/exceptions/remote_exception.dart
- lib/main/exceptions/remote_exception_thrower.dart
- lib/main/localizations/app_localizations.dart
#1829 
https://github.com/linagora/tmail-flutter/assets/80730648/cd1c1a7b-ea9b-41c2-bf79-286c4447b139
> TF-1829 Fix app crash upon 401

- lib/features/base/base_controller.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/login/presentation/login_bindings.dart
- lib/features/login/presentation/login_controller.dart
- lib/main/exceptions/remote_exception_thrower.dart
- `Webfinger` is recalled many times
https://github.com/linagora/tmail-flutter/assets/80730648/27db96aa-73c7-4573-b2af-06710b6c7d70
https://github.com/linagora/tmail-flutter/assets/80730648/320705fc-96de-4532-88c9-4eb9a75704ea
- Request `Webfinger` always return error `Connection Error` so application always call `logout` action
- Call `logout` action only if and only if `isLoggedIn = true`
> [HOT-FIX] `Webfinger` is recalled many times

- lib/features/composer/presentation/composer_controller.dart
#1952 
[device-2023-07-04-170830.webm](https://github.com/linagora/tmail-flutter/assets/80730648/7bb37cf0-8e02-4a24-9830-22cc80e29d3b)
> TF-1952 Display signature in composer on mobile

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
#1895 
https://github.com/linagora/tmail-flutter/assets/80730648/85cdaa6a-4596-40b8-bfb6-d1100420b0c3
> TF-1895 Fix the screen seem be black before loading the email content successfully

- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_form_bottom_view.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
#1993 
https://github.com/linagora/tmail-flutter/assets/80730648/74116e90-bd65-4352-8401-bf3e978a986d
> TF-1993 Fix has attachment checkbox is overflow once it be translated in russia

- ios/Podfile.lock
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/presentation/config/fcm_configuration.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- lib/features/push_notification/presentation/services/fcm_receiver.dart
- lib/features/push_notification/presentation/services/fcm_service.dart
- pubspec.lock
- pubspec.yaml
#1898 
https://github.com/linagora/tmail-flutter/assets/80730648/4f5bc161-8c16-4428-bc79-62e7ef2265c5
> TF-1898 Fix there is no notification badge only on IOS

- core/lib/presentation/views/text/text_overflow_builder.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- Font Arabic not correctly
- Because we use some special character conversion function to avoid ugly text clipping when using `ellipsis`, but it doesn't work correctly with Arabic language
> [HOT] Fix font mailbox on Arabic language

- lib/features/base/widget/material_text_button.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/widgets/email_address_bottom_sheet_builder.dart
- lib/features/email/presentation/widgets/email_address_dialog_builder.dart
- lib/features/email/presentation/widgets/email_receiver_builder.dart
- lib/features/email/presentation/widgets/email_sender_builder.dart
- lib/main/utils/app_utils.dart
#1994 
https://github.com/linagora/tmail-flutter/assets/80730648/229b7faf-7ea3-42fb-bd93-e3bad7685817
> TF-1994 Long press to copy an email address

- core/lib/presentation/extensions/color_extension.dart
- lib/features/base/base_controller.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/network_connection/presentation/network_connection_banner_widget.dart
- lib/features/network_connection/presentation/network_connection_controller.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/main/bindings/network_connection/network_connection_bindings.dart
- lib/main/exceptions/remote_exception_thrower.dart
#2008 
**- Mobile:**
**- Tablet**
**- Tablet Large**
> TF-2008 Instead of toasting network connection

- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
#1985 
https://github.com/linagora/tmail-flutter/assets/80730648/ec1c0db5-1f18-420d-b8e4-e5c5e12f88d0
> TF-1985 Fix hover item email to see the selection

- lib/features/base/base_mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_node.dart
- lib/features/mailbox/presentation/model/mailbox_tree.dart
#1868 
https://github.com/linagora/tmail-flutter/assets/80730648/7503a788-5384-4a94-b1ee-9c3452138ca6
> TF-1868 Fix a mailbox is visible then it's parents needs to be visible too

- pubspec.lock
#2030
https://github.com/linagora/html-editor-enhanced/pull/16
> TF-2030 Turn off composer logs by default

- CHANGELOG.md
- core/lib/presentation/utils/html_transformer/text/sanitize_html_transformers.dart
- core/lib/utils/app_logger.dart
- env.file
- lib/features/composer/presentation/widgets/toolbar_rich_text_builder.dart
- lib/features/email/data/local/html_analyzer.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
- pubspec.yaml
- \#1912 Fix rendering issue on TMail when reading an email
- Fix re-login app when token expires in OIDC
> Release v0.8.7

- lib/features/base/base_controller.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/login_view_web.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/main/routes/route_navigation.dart
#2046 
- Because the `TextEditingController` is used after calling the `dispose`
https://github.com/linagora/tmail-flutter/assets/80730648/265f7588-0afa-45d7-994d-4e4065db72ed
> TF-2046 App crashes when login account information is incorrect on web

- CHANGELOG.md
- lib/features/base/base_controller.dart
- lib/features/home/presentation/home_controller.dart
- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/login_view_web.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/main/routes/route_navigation.dart
- pubspec.yaml
- \#2046 App crashes when login account information is incorrect on web
> Release v0.8.8

- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
#2052 
https://github.com/linagora/tmail-flutter/assets/80730648/c7c38dfb-4eb8-4c23-aff9-fb1925bafe0c
> TF-2052 Fix TeamMailbox email address alignment is incorrect

- lib/features/caching/caching_manager.dart
- lib/features/caching/config/cache_version.dart
- lib/features/caching/config/hive_cache_config.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/extensions/calendar_event_extension.dart
- lib/features/email/presentation/widgets/calendar_event/attendee_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_action_banner_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_attendee_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_location_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_location_information_widget.dart
- model/lib/extensions/list_email_address_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- pubspec.lock
- pubspec.yaml
- #2066 
- #2067 
- #2068 
- #2072
https://github.com/linagora/tmail-flutter/assets/80730648/71f0da3a-2b57-4eb0-9585-d1cc7048680c
https://github.com/linagora/tmail-flutter/assets/80730648/22ffdae7-6dd4-476d-9d83-108742736bf2
> [HOT] Fix some bug calendar on version 0.8.9

- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_categories.dart
- lib/features/mailbox/presentation/model/mailbox_categories_expand_mode.dart
- lib/features/manage_account/presentation/mailbox_visibility/mailbox_visibility_controller.dart
- lib/features/manage_account/presentation/mailbox_visibility/mailbox_visibility_view.dart
- lib/l10n/intl_ar.arb
- lib/l10n/intl_fr.arb
- lib/l10n/intl_it.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
#1982 
https://github.com/linagora/tmail-flutter/assets/80730648/ab7c22c4-f006-41a4-812a-26c4fc8541a3
> TF-1982 Change mailboxes label to folder

- core/lib/presentation/extensions/html_extension.dart
- lib/features/composer/presentation/composer_controller.dart
#2092 
https://github.com/linagora/tmail-flutter/assets/80730648/e231666a-ff71-4660-b404-05e27c0a67d9
> TF-2092 Update signature prefix

- CHANGELOG.md
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/login/data/network/config/oidc_constant.dart
- lib/features/quotas/domain/extensions/quota_extensions.dart
- pubspec.yaml
- \#1974 Fix refreshToken with OIDC on jmap.linagora.com/oidc
- \#2099 Fix quota information are missing
> Release v0.9.1

- lib/features/thread/presentation/thread_controller.dart
---
---
https://github.com/linagora/tmail-flutter/assets/80142234/81606bf9-094a-4e81-adb3-6addf5cf02d8
> [HOT-FIX] Disable swipe right-to-left on item of Thread View

- core/lib/presentation/views/text/slogan_builder.dart
- lib/features/email/presentation/action/email_ui_action.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox/presentation/action/mailbox_ui_action.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
#1977 
https://github.com/linagora/tmail-flutter/assets/80730648/a07202aa-df49-495f-9d93-fa0a94739654
> TF-1977 Clickable logo

- core/lib/core.dart
- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/views/clipper/side_arrow_clipper.dart
- core/lib/utils/app_logger.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox/presentation/model/mailbox_node.dart
- lib/features/mailbox/presentation/styles/empty_mailbox_dialog_overlay_styles.dart
- lib/features/mailbox/presentation/styles/empty_mailbox_popup_dialog_widget_styles.dart
- lib/features/mailbox/presentation/styles/label_mailbox_item_widget_styles.dart
- lib/features/mailbox/presentation/styles/trailing_mailbox_item_widget_styles.dart
- lib/features/mailbox/presentation/utils/mailbox_method_action_define.dart
- lib/features/mailbox/presentation/widgets/empty_mailbox_dialog_overlay.dart
- lib/features/mailbox/presentation/widgets/empty_mailbox_popup_dialog_widget.dart
- lib/features/mailbox/presentation/widgets/label_mailbox_item_widget.dart
- lib/features/mailbox/presentation/widgets/mailbox_item_widget.dart
- lib/features/mailbox/presentation/widgets/trailing_mailbox_item_widget.dart
- lib/features/mailbox_dashboard/domain/state/get_number_of_unread_spam_emails_state.dart
- lib/features/mailbox_dashboard/presentation/controller/spam_report_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_filter_overlay.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- lib/features/manage_account/presentation/language_and_region/widgets/language_menu_overlay.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/extensions/presentation_mailbox_extension.dart
#1984 
https://github.com/linagora/tmail-flutter/assets/80730648/88504811-5d4c-4e08-8ed9-cdf67f9768fa
> TF-1984 Add `Empty` action for `Trash/Spam` mailbox

- lib/features/composer/domain/usecases/update_email_drafts_interactor.dart
- lib/features/composer/presentation/base_composer_view.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/model/save_to_draft_view_event.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/exceptions/email_exceptions.dart
- lib/features/email/domain/repository/email_repository.dart
#2026 
https://github.com/linagora/tmail-flutter/assets/80730648/a7aad214-7fa2-4d3f-a125-0fb04b2c96ea
> TF-2026 Save as draft should not close composer

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailto/presentation/mailto_url_bindings.dart
- lib/features/mailto/presentation/mailto_url_controller.dart
- lib/features/mailto/presentation/mailto_url_view.dart
- lib/features/mailto/presentation/model/mailto_arguments.dart
- lib/main.dart
- lib/main/pages/app_pages.dart
- lib/main/routes/app_routes.dart
- lib/main/routes/navigation_router.dart
- lib/main/routes/route_utils.dart
- model/lib/email/email_action_type.dart
- pubspec.lock
- pubspec.yaml
#2134 
https://github.com/linagora/tmail-flutter/assets/80730648/3270d065-018b-4a8b-8b64-9e1851d254e5
> TF-2134 Support mailto URL for web

- CHANGELOG.md
- pubspec.yaml
- server/nginx.conf
- \[HOT-FIX\] Fix built release but nginx route 404 not found on web
> Release v0.9.3

- lib/features/caching/config/cache_version.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/model/save_to_draft_view_event.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/domain/extensions/detailed_email_extension.dart
- lib/features/email/domain/extensions/detailed_email_hive_cache_extension.dart
- lib/features/email/domain/extensions/email_extension.dart
- lib/features/email/domain/model/detailed_email.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/offline_mode/model/detailed_email_hive_cache.dart
- lib/features/thread/domain/constants/thread_constants.dart
- model/lib/email/email_property.dart
#1608 
https://github.com/linagora/tmail-flutter/assets/80730648/5dd7a633-bd08-4fce-bd61-0e9925e5a673
> TF-1608 Set `References` and `In-Reply-To` fields when reply/forward email

- core/lib/presentation/utils/html_transformer/html_template.dart
- core/lib/presentation/utils/html_transformer/html_utils.dart
- core/lib/presentation/utils/icon_utils.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
#2157 
- Web:
https://github.com/linagora/tmail-flutter/assets/80730648/18d54822-a20f-4647-8904-178e73b98ebb
- Mobile:
https://github.com/linagora/tmail-flutter/assets/80730648/115b3659-91fa-47eb-ac29-f7dfa8ce88a8
> TF-2157 Remove `collapsed/expanded` signature in EmailView

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/manage_account/domain/model/create_new_email_rule_filter_request.dart
- lib/features/rules_filter_creator/presentation/extensions/rule_condition_extensions.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/styles/rule_condition_combiner_bottom_sheet_styles.dart
- lib/features/rules_filter_creator/presentation/styles/rule_filter_title_styles.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_condition_combiner_bottomsheet_action_tile_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_button_field.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_widget.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_title_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- rule_filter/lib/rule_filter/rule_condition_group.dart
- rule_filter/lib/rule_filter/tmail_rule.dart
- rule_filter/test/rule_filter/set_rule_filter_method_test.dart
---
#2085
---
https://github.com/linagora/tmail-flutter/assets/80142234/901fea09-855d-4af9-a06f-0ed6e6a81d19
https://github.com/linagora/tmail-flutter/assets/80142234/a925cd82-e8dd-4f1a-afee-8129ffc5063d
> TF-2085 Combine conditions to create rules

- lib/features/email/presentation/bindings/email_bindings.dart
- lib/features/home/presentation/home_bindings.dart
- lib/features/login/presentation/login_bindings.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailto/presentation/mailto_url_bindings.dart
- lib/features/manage_account/domain/usecases/log_out_oidc_interactor.dart
- lib/features/manage_account/presentation/manage_account_dashboard_bindings.dart
- lib/features/network_connection/presentation/network_connection_controller.dart
- lib/features/session/presentation/session_page_bindings.dart
- lib/main/bindings/credential/credential_bindings.dart
- lib/main/bindings/main_bindings.dart
- lib/main/bindings/network_connection/network_connection_bindings.dart
- lib/main/pages/app_pages.dart
- lib/main/routes/app_routes.dart
https://github.com/linagora/tmail-flutter/assets/80730648/52713e9f-d80a-4a03-a972-caa71217ba0b
> Chore: Fix not found object in bindings

- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailto/presentation/mailto_url_controller.dart
- lib/features/mailto/presentation/model/mailto_arguments.dart
- lib/main/routes/navigation_router.dart
- lib/main/routes/route_utils.dart
- model/lib/email/email_action_type.dart
- test/main/routes/route_utils_test.dart
#2168 
https://github.com/linagora/tmail-flutter/assets/80730648/806872ab-c69c-4d52-b7ae-4562c3cd9baa
> TF-2168 Fix mailto invalid recipient

- pubspec.lock
#2167 
- https://github.com/linagora/html-editor-enhanced/pull/23
https://github.com/linagora/tmail-flutter/assets/80730648/403e62f0-3f7a-47ff-a4af-ed5cb9aa82a9
> TF-2167 Support `CTRL+SHIFT+Z` to be able to restore the user input (REDO action) on windows/linux

- lib/features/composer/presentation/styles/recipient_composer_widget_style.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- pubspec.lock
#2180 
- Need merged: https://github.com/dab246/super_tag_editor/pull/26
https://github.com/linagora/tmail-flutter/assets/80730648/bf79a0c1-e08c-4b0f-86aa-90774b7c12c2
> TF-2180 Fix suggestion list being hidden once user use device with small screen

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/rules_filter_creator/presentation/model/email_rule_filter_action.dart
- lib/features/rules_filter_creator/presentation/model/rule_filter_action_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/styles/rule_filter_action_styles.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_detailed_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_list.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_row_mobile_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_widget.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_button_field.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
---
#2084 
#2086 
---
- web:
https://github.com/linagora/tmail-flutter/assets/80142234/5d431bd3-98a6-4e70-9224-16bd786eba77
- android:
https://github.com/linagora/tmail-flutter/assets/80142234/e7b7abc2-e18a-4acb-b751-12e25b182cf1
> TF-2084 add/remove actions in UI

- lib/features/composer/domain/state/send_email_state.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/network_connection/presentation/network_connection_controller.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/network_connection/network_connection_bindings.dart
- pubspec.lock
- pubspec.yaml
#2202
- Establish connection: 
+ Wifi `Lamoda`: Has internet connection
+ Wifi `OPPO F7`: Personal hotspot no network connection
https://github.com/linagora/tmail-flutter/assets/80730648/de04f781-d2dd-47dd-a03f-714825ed7165
> TF-2202 Fix sending email failed when network is corrupted but wifi still in full

- lib/features/composer/presentation/composer_controller.dart
---
#2199 
---
- Case 1: Suggestion list is empty, but typed text is an email
https://github.com/linagora/tmail-flutter/assets/80142234/db21ee77-7e43-4dfa-bfac-0fba703a0d6b
- Case 2: Suggestion list is not empty, and not include typed email
https://github.com/linagora/tmail-flutter/assets/80142234/8fce2fe7-f172-44dd-9c78-6eaf90b88020
- Android:
https://github.com/linagora/tmail-flutter/assets/80142234/0ed63ffa-942e-44f1-9775-ea8b08b8ca66
> TF-2199 Email suggestion for unknown email

- lib/features/base/mixin/message_dialog_action_mixin.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/model/compose_action_mode.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/network_connection/presentation/network_connection_controller.dart
- lib/features/network_connection/presentation/web_network_connection_controller.dart
- lib/features/sending_queue/presentation/model/sending_email_arguments.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/network_connection/network_connection_bindings.dart
- lib/main/exceptions/remote_exception_thrower.dart
#2189 
[Screen_recording_20231003_194043.webm](https://github.com/linagora/tmail-flutter/assets/80730648/530c5817-648f-4655-b41a-9a5bae326aca)
> TF-2189 Fix composer disappear when click send button in offline mode

- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/offline_mode/model/sending_state.dart
- lib/features/offline_mode/work_manager/sending_email_worker.dart
- lib/features/sending_queue/domain/model/sending_email.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/sending_queue/presentation/sending_queue_view.dart
- lib/features/sending_queue/presentation/widgets/bottom_bar_sending_queue_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
> TF-2188 Sending queue item sent fail but still in sending queue

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/sending_queue/presentation/sending_queue_view.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- model/lib/extensions/presentation_mailbox_extension.dart
#2187 
[Screen_recording_20231005_143035.webm](https://github.com/linagora/tmail-flutter/assets/80730648/c799a523-763c-469b-a68f-cd4c1465b95f)
> TF-2187 Handle click system back button to back to Inbox

- core/lib/domain/extensions/media_type_extension.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/mailbox_dashboard/data/model/composer_cache.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/media_type_nullable_extension.dart
- model/lib/model.dart
- model/lib/upload/file_info.dart
- `mimeType` is empty or null
https://github.com/linagora/tmail-flutter/assets/80730648/10702596-8d56-408c-8e5b-e9483a237be1
https://github.com/linagora/tmail-flutter/assets/80730648/cf1a5b1c-ed79-4114-9323-5ceb48965b33
> [HOT-FIX] Some file with mimeType is empty can not drag n drop

- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- lib/features/composer/presentation/widgets/subject_composer_widget.dart
- pubspec.lock
#2191 
- Need merged: https://github.com/dab246/super_tag_editor/pull/27
- Android:
[Screen_recording_20231010_151534.webm](https://github.com/linagora/tmail-flutter/assets/80730648/d9522b3b-9485-4200-ba82-22864a0f5e86)
- iOS
https://github.com/linagora/tmail-flutter/assets/80730648/2d5597a4-241f-4316-aee5-865589256b9a
> TF-2191 Fix keyboard disappear when switch focus from subject to body in composer android

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- lib/features/email/presentation/email_view.dart
#2253 
- Android
https://github.com/linagora/tmail-flutter/assets/80730648/333ed217-96cc-4fed-8e68-80868ae4c42a
- iOS:
https://github.com/linagora/tmail-flutter/assets/80730648/c9adecdf-b58c-4331-951d-bf1a9665418f
> TF-2253 Fix missing email content on mobile

- core/lib/presentation/extensions/color_extension.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/composer/presentation/model/rich_text_style_type.dart
- lib/features/composer/presentation/styles/web/dropdown_button_font_size_widget_style.dart
- lib/features/composer/presentation/styles/web/dropdown_menu_font_size_widget_style.dart
- lib/features/composer/presentation/styles/web/item_menu_font_size_widget_style.dart
- lib/features/composer/presentation/styles/web/toolbar_rich_text_builder_style.dart
- lib/features/composer/presentation/view/web/web_editor_view.dart
- lib/features/composer/presentation/widgets/web/dropdown_button_font_size_widget.dart
- lib/features/composer/presentation/widgets/web/dropdown_menu_font_size_widget.dart
- lib/features/composer/presentation/widgets/web/item_menu_font_size_widget.dart
- lib/features/composer/presentation/widgets/web/toolbar_rich_text_builder.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
#1301 
- Need merged: https://github.com/linagora/html-editor-enhanced/pull/25 
https://github.com/linagora/tmail-flutter/assets/80730648/9fe599a7-6c90-4e65-8759-dc39a67bdd1c
> TF-1301 Support select font size while compose email

- README.md
Hey folks, was looking at repo for some hacktoberfest work and found some minor spelling error and a phrasing that seemed off/wrong. 
- Minor rephrasing
- Spelling fixes
> README.md - Minor textual changes

- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- rule_filter/lib/rule_filter/rule_action.dart
- rule_filter/test/rule_filter/set_rule_filter_method_test.dart
---
#2184 
https://github.com/linagora/tmail-flutter/assets/80142234/59977606-dc5a-4d7c-98ed-8417c187ea3e
> TF-2184 implement filter rule with multiple action

- lib/features/composer/domain/extensions/email_request_extension.dart
- lib/features/composer/domain/state/send_email_state.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/model/save_to_draft_arguments.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/offline_mode/model/sending_state.dart
- lib/features/sending_queue/domain/model/sending_email.dart
- lib/features/sending_queue/presentation/extensions/list_sending_email_extension.dart
- lib/features/sending_queue/presentation/model/sending_email_arguments.dart
- lib/features/sending_queue/presentation/sending_queue_controller.dart
- lib/features/sending_queue/presentation/sending_queue_view.dart
- lib/features/sending_queue/presentation/styles/app_bar_sending_queue_widget_style.dart
- lib/features/sending_queue/presentation/styles/sending_email_tile_style.dart
- lib/features/sending_queue/presentation/styles/sending_state_widget_style.dart
- lib/features/sending_queue/presentation/utils/sending_queue_utils.dart
- lib/features/sending_queue/presentation/widgets/app_bar_sending_queue_widget.dart
- lib/features/sending_queue/presentation/widgets/banner_message_sending_queue_widget.dart
- lib/features/sending_queue/presentation/widgets/bottom_bar_sending_queue_widget.dart
- lib/features/sending_queue/presentation/widgets/sending_email_tile_widget.dart
- lib/features/sending_queue/presentation/widgets/sending_state_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- #2189 
- Need merged: https://github.com/linagora/enough_html_editor/pull/23
https://github.com/linagora/tmail-flutter/assets/80730648/b9a3662b-b035-4c36-a083-5ff056e14964
> TF-2189 Fix sending queue on iOS

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/styles/email_view_app_bar_widget_styles.dart
- lib/features/email/presentation/styles/email_view_bottom_bar_widget_styles.dart
- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- lib/features/email/presentation/widgets/email_view_bottom_bar_widget.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
#2261 
https://github.com/linagora/tmail-flutter/assets/80730648/f87bf3e1-1282-469c-bcda-13cd89dae01a
> TF-2261 Fix UI broken when user send long email content

- core/lib/presentation/utils/html_transformer/dom/remove_collapsed_signature_button_transformers.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
https://github.com/linagora/tmail-flutter/assets/80730648/a1008b6f-cb1d-4dfc-a0fa-9f63c122e85a
https://github.com/linagora/tmail-flutter/assets/80730648/17351526-c661-4ab3-8238-0f01a272d205
> Remove collapse expand signature button in Email View

- lib/features/manage_account/domain/model/create_new_email_rule_filter_request.dart
- lib/features/manage_account/domain/model/edit_email_rule_filter_request.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
---
When implement new concept of email rule with multiple rules and actions:
- Can not update rules.
- Can not delete rules.
https://github.com/linagora/tmail-flutter/assets/80142234/15c66232-bd09-4c51-95a1-d8dbd194ee58
https://github.com/linagora/tmail-flutter/assets/80142234/31235871-68c9-4048-853b-6949d30cdcf5
> [Hotfix] Cannot edit and delete email rule

- .github/workflows/gh-pages.yaml
Also renamed the file to match what it does.
> Only make 1 PR deployment run at the time

- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- lib/features/thread/presentation/widgets/app_bar/selection_web_app_bar_thread_widget.dart
- lib/features/thread/presentation/widgets/bottom_bar_thread_selection_widget.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- model/lib/extensions/list_presentation_email_extension.dart
---
#1793 
https://github.com/linagora/tmail-flutter/assets/80142234/5d0a82ba-482b-4041-b55e-d20ce64166e1
> TF-1793 Delete message permanently from spam folder

- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/offline_mode/config/work_manager_constants.dart
- lib/features/offline_mode/work_manager/sending_email_worker.dart
- lib/features/offline_mode/work_manager/worker_type.dart
> Feat: Fix sending queue on mobile

- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
---
#2233 
https://github.com/linagora/tmail-flutter/assets/80142234/62138bec-f9fd-4137-8699-7b56cab0c059
> TF-2233 Remove mark as read for trash folder

- lib/features/thread/presentation/widgets/scroll_to_top_button_widget.dart
---
#1017 
- Enable scroll up to top button for web
https://github.com/linagora/tmail-flutter/assets/80142234/77a72c8f-73e6-4866-bf65-fc98bd6196a9
> TF-1017 Enable scroll to top button for web

- core/lib/data/network/download/download_client.dart
- lib/features/composer/data/datasource_impl/composer_datasource_impl.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/composer/presentation/extensions/file_upload_extension.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/upload/data/network/file_uploader.dart
- lib/features/upload/domain/usecases/local_file_picker_interactor.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- model/lib/upload/file_info.dart
#2245
- Because data is uploaded in Stream format. So every time we call the request again we have to re-initialize it.
https://github.com/linagora/tmail-flutter/assets/80730648/9b58be00-ef78-4c74-b916-c45c6b5cabdf
> TF-2245 Cannot upload attachment or image when token expired

- CHANGELOG.md
- ios/Runner/Info.plist
- pubspec.yaml
- Hot fix build release iOS on version 0.10.2
> Release v0.10.3

- lib/main.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/network/network_isolate_binding.dart
- lib/main/localizations/locale_interceptor.dart
- lib/main/localizations/localization_service.dart
> TF-2215 Support communicating L18n to remote servers

- core/lib/presentation/views/button/tmail_button_widget.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/widgets/web/bottom_bar_composer_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
---
#2237 
https://github.com/linagora/tmail-flutter/assets/80142234/8aa9620f-3525-4541-ac7a-c0517113d1de
- Send with long email:
https://github.com/linagora/tmail-flutter/assets/80142234/59d999b0-b54e-430a-8a87-615063a5e7cd
> TF-2237 Limit composer send button clickable only one time

- lib/features/base/widget/drop_down_button_widget.dart
- lib/features/manage_account/domain/model/create_new_email_rule_filter_request.dart
- lib/features/manage_account/domain/model/edit_email_rule_filter_request.dart
- lib/features/manage_account/presentation/email_rules/email_rules_controller.dart
- lib/features/rules_filter_creator/presentation/extensions/rule_condition_extensions.dart
- lib/features/rules_filter_creator/presentation/model/email_rule_filter_action.dart
- lib/features/rules_filter_creator/presentation/model/rule_filter_action_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/styles/rule_condition_combiner_bottom_sheet_styles.dart
- lib/features/rules_filter_creator/presentation/styles/rule_filter_action_styles.dart
- lib/features/rules_filter_creator/presentation/styles/rule_filter_title_styles.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_condition_combiner_bottomsheet_action_tile_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_detailed_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_list.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_row_mobile_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_widget.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_button_field.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_widget.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_title_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- rule_filter/lib/rule_filter/rule_action.dart
- rule_filter/lib/rule_filter/rule_condition_group.dart
- rule_filter/lib/rule_filter/tmail_rule.dart
- rule_filter/test/rule_filter/set_rule_filter_method_test.dart
> Migrate `intern` to `master` branch

- lib/features/caching/caching_manager.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
- lib/features/mailbox/presentation/model/mailbox_actions.dart
- lib/features/mailbox_dashboard/data/datasource_impl/hive_spam_report_datasource_impl.dart
- lib/features/mailbox_dashboard/data/datasource_impl/local_spam_report_datasource_impl.dart
- lib/features/mailbox_dashboard/data/local/local_spam_report_manager.dart
- lib/features/mailbox_dashboard/domain/usecases/get_spam_mailbox_cached_interactor.dart
- lib/features/mailbox_dashboard/domain/usecases/get_unread_spam_mailbox_interactor.dart
- lib/features/mailbox_dashboard/domain/utils/mailbox_dashboard_constant.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/search/mailbox/presentation/search_mailbox_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/bindings/local/local_bindings.dart
- lib/main/localizations/app_localizations.dart
#2269
https://github.com/linagora/tmail-flutter/assets/80730648/0cf71fd7-9873-401d-9721-b5fd02baf1ab
https://github.com/linagora/tmail-flutter/assets/80730648/4fcdeda9-bcbb-4df4-9980-e1efaf803056
> TF-2269 Improve spam banner

- lib/features/base/base_mailbox_controller.dart
- lib/features/base/mixin/handle_error_mixin.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox/data/datasource/mailbox_datasource.dart
- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/datasource_impl/mailbox_datasource_impl.dart
- lib/features/mailbox/data/network/mailbox_api.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/constants/mailbox_constants.dart
- lib/features/mailbox/domain/exceptions/set_mailbox_method_exception.dart
- lib/features/mailbox/domain/extensions/role_extension.dart
- lib/features/mailbox/domain/repository/mailbox_repository.dart
- lib/features/mailbox/domain/state/create_default_mailbox_state.dart
- lib/features/mailbox/domain/usecases/create_new_default_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_bindings.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_tree.dart
- lib/features/mailbox/presentation/utils/mailbox_constants.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/error/capability_validator.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/mailbox_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/lib/extensions/presentation_mailbox_extension.dart
- model/lib/mailbox/presentation_mailbox.dart
- test/features/email/avatar_email_test.dart
- test/fixtures/email_fixtures.dart
- `#1704`:  Set default `MaxCallsInRequest = 1` 
-  `#1705`:  Auto create default folders `(Inbox/Sent/Trash/Drafts)` if missing with appropriate roles
- `#1706`: Check `from` property of email. If is null or empty then display default avatar otherwise display avatar by `hashCode` of email
https://github.com/linagora/tmail-flutter/assets/80730648/d0431027-23e3-4b27-914d-b1aeb1024f28
> TF-1704,1705,1706 Fix some bug on server CYRUS

- core/lib/presentation/views/bottom_popup/confirmation_dialog_action_sheet_builder.dart
- lib/features/base/mixin/message_dialog_action_mixin.dart
- lib/features/composer/presentation/composer_controller.dart
#2321 
https://github.com/linagora/tmail-flutter/assets/80730648/1d68d857-573c-4eb6-b6d0-d47ed044d8c2
> TF-2321 Fix user cannot continue sending email when tap outside to close dialog in offline mode iOS

- lib/features/search/email/presentation/search_email_view.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/email_tile_builder.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
- model/lib/email/presentation_email.dart
#1973
https://github.com/linagora/tmail-flutter/assets/80730648/d8df068c-f80c-459e-b90e-d4cbb9678de7
> TF-1973 Fix selection mode still displayed when dragging or moving email

- lib/features/search/email/presentation/model/simple_search_filter.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/search/email/presentation/search_email_view.dart
- lib/features/search/email/presentation/styles/email_sort_by_action_tile_widget_style.dart
- lib/features/search/email/presentation/styles/email_sort_by_cupertino_action_sheet_action_builder_style.dart
- lib/features/search/email/presentation/widgets/email_sort_by_action_tile_widget.dart
- lib/features/search/email/presentation/widgets/email_sort_by_cupertino_action_sheet_action_builder.dart
---
#2304 
---
- Web responsive:
https://github.com/linagora/tmail-flutter/assets/80142234/58762c6b-73b0-41d2-9e11-f8c6264172ff
- Android:
https://github.com/linagora/tmail-flutter/assets/80142234/f705bd84-05fb-4231-8f53-92dad18a286c
> TF-2304 Implement sorting search result for mobile

- lib/features/caching/config/cache_version.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/domain/extensions/email_extension.dart
- lib/features/email/domain/usecases/get_email_content_interactor.dart
- lib/features/email/presentation/email_view.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/list_attachment_extension.dart
#2331
https://github.com/linagora/tmail-flutter/assets/80730648/38199417-387e-4011-b0a7-2611397c9420
> TF-2331 Fix Read receipt includes weird attachments that are impossible to download

- .github/workflows/build.yaml
11:00 UTC = 18:00 Vietnam time
> Schedule build to run on workday end

- lib/features/rules_filter_creator/presentation/model/email_rule_filter_action.dart
- lib/features/rules_filter_creator/presentation/model/rule_filter_action_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_action_detailed_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
---
#2084 
- Wrong title for action `starIt`
---
https://github.com/linagora/tmail-flutter/assets/80142234/6b8da8d6-efc9-4889-8ad5-7a695db899b5
> TF-2084 Fix wrong action title

- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
#2378 
https://github.com/linagora/tmail-flutter/assets/80730648/c7202d21-5425-4dc1-a6d1-4c47b144022e
> TF-2378 Fix user cannot see the suggestion when recipient is longer than 10 on mobile

- lib/features/email/presentation/widgets/email_receiver_widget.dart
#2263 
- Mobile
https://github.com/linagora/tmail-flutter/assets/80730648/69095251-f0de-4658-8761-81217ede8e26
- Web:
https://github.com/linagora/tmail-flutter/assets/80730648/65da93de-39c7-4f08-be91-4d972b614c3d
> TF-2263 Fix recipient list in field "Cc" is not in correct position

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
> fix: Failed to build ios app on Xcode `15.1`

- core/lib/data/network/download/download_client.dart
- core/lib/presentation/utils/html_transformer/html_utils.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
#2401 
https://github.com/linagora/tmail-flutter/assets/80730648/9d350af7-d9af-4a96-bbb7-199548c39421
> TF-2401 Fix cannot upload svg image as signature

- contact/pubspec.lock
- lib/features/contact/presentation/contact_controller.dart
- lib/features/contact/presentation/contact_view.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/model/search/email_sort_order_type.dart
- lib/features/mailbox_dashboard/presentation/model/search/quick_search_filter.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/search/email/domain/usecases/refresh_changes_search_email_interactor.dart
- lib/features/search/email/presentation/model/simple_search_filter.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/data/datasource/thread_datasource.dart
- lib/features/thread/data/datasource_impl/local_thread_datasource_impl.dart
- lib/features/thread/data/datasource_impl/thread_datasource_impl.dart
- lib/features/thread/data/network/thread_api.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/domain/model/get_email_request.dart
- lib/features/thread/domain/repository/thread_repository.dart
- lib/features/thread/domain/usecases/search_email_interactor.dart
- lib/features/thread/domain/usecases/search_more_email_interactor.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/routes/dialog_router.dart
- model/pubspec.lock
#2323 
#2381 
https://github.com/linagora/tmail-flutter/assets/80730648/a6a8c683-de79-4925-9785-04c27a104ff8
> TF-2323 Improve from filter in quick search result

- lib/features/manage_account/presentation/language_and_region/widgets/language_and_region_header_widget.dart
- lib/features/manage_account/presentation/model/account_menu_item.dart
- lib/l10n/intl_ar.arb
- lib/l10n/intl_en.arb
- lib/l10n/intl_fr.arb
- lib/l10n/intl_it.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
---
#2241 
---
https://github.com/linagora/tmail-flutter/assets/80142234/80b82321-8d10-4877-8133-cc33b4748037
> TF-2241 Naming for language setting

- core/lib/presentation/extensions/html_extension.dart
---
#2399  
---
https://github.com/linagora/tmail-flutter/assets/80142234/af2ce065-7028-4c90-a928-21a4894db254
> [bugfix] TF-2399 Can not click to open signature in composer

- lib/features/composer/presentation/extensions/email_action_type_extension.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/email/email_action_type.dart
- model/lib/extensions/presentation_mailbox_extension.dart
- model/lib/mailbox/presentation_mailbox.dart
---
#1328 
---
- Web
https://github.com/linagora/tmail-flutter/assets/80142234/fddf81dd-66c5-468c-9231-46de853f39aa
- Android
https://github.com/linagora/tmail-flutter/assets/80142234/263cb8c7-852e-4c8a-99c1-74190b410b22
> TF-1328 Quick archive message

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- ios/TwakeCore/Extensions/DateExtensions.swift
- ios/TwakeCore/Extensions/StringExtensions.swift
- ios/TwakeCore/Jmap/JmapClient.swift
- ios/TwakeCore/Jmap/Utils/JmapConstants.swift
- ios/TwakeCore/Network/AlamofireService.swift
- ios/TwakeCore/Network/Interceptor/AuthenticationInterceptor.swift
- ios/TwakeCore/Network/Model/Authentication.swift
- ios/TwakeCore/Network/Model/AuthenticationCredential.swift
- ios/TwakeCore/Network/Model/AuthenticationSSO.swift
- ios/TwakeCore/Network/Model/TokenOidc.swift
- ios/TwakeCore/Network/Model/TokenResponse.swift
- ios/TwakeCore/Network/TokenRefreshManager.swift
- ios/TwakeMailNSE/Keychain/KeychainController.swift
- ios/TwakeMailNSE/Model/KeychainSharingSession.swift
- ios/TwakeMailNSE/NotificationService.swift
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/push_notification/data/keychain/keychain_sharing_session.dart
- lib/main/utils/ios_sharing_manager.dart
- model/lib/oidc/response/oidc_discovery_response.dart
> TF-2384 [PART-2] Improvement notification iOS

- ios/Runner/AppDelegate.swift
- ios/TwakeCore/Jmap/JmapClient.swift
- ios/TwakeCore/Jmap/Model/Response/JmapResponseObject.swift
- ios/TwakeCore/Network/AlamofireService.swift
- ios/TwakeCore/Network/TokenRefreshManager.swift
- ios/TwakeMailNSE/NotificationService.swift
- lib/features/home/presentation/home_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/model/preview_email_arguments.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/services/fcm_receiver.dart
- lib/features/push_notification/presentation/services/fcm_service.dart
- lib/features/push_notification/presentation/utils/fcm_utils.dart
> TF-2384 [PART-3,4] Improvement notification iOS  notification

- lib/features/email_recovery/presentation/controller/input_field_focus_manager.dart
- lib/features/email_recovery/presentation/email_recovery_controller.dart
- lib/features/email_recovery/presentation/model/email_recovery_field.dart
- lib/features/email_recovery/presentation/model/email_recovery_time_type.dart
- lib/features/email_recovery/presentation/styles/date_selection_field/date_selection_dropdown_button_styles.dart
- lib/features/email_recovery/presentation/styles/date_selection_field/date_selection_field_styles.dart
- lib/features/email_recovery/presentation/widgets/date_selection_field/date_selection_dropdown_button.dart
- lib/features/email_recovery/presentation/widgets/date_selection_field/date_selection_field_mobile_widget.dart
- lib/features/email_recovery/presentation/widgets/date_selection_field/date_selection_field_web_widget.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_desktop_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_mobile_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_tablet_builder.dart
---
#2101 
---
https://github.com/linagora/tmail-flutter/pull/2406
---
- Web
https://github.com/linagora/tmail-flutter/assets/80142234/73894497-58da-4a7d-a555-b2cc163d8f87
- Android
https://github.com/linagora/tmail-flutter/assets/80142234/5f7a29a9-e719-4138-a871-ff0a1abe4ac7
> TF-2101 [Part 2] Add date selection fields to recover deleted message dialog

- lib/features/email_recovery/presentation/email_recovery_controller.dart
- lib/features/email_recovery/presentation/model/email_recovery_arguments.dart
- lib/features/email_recovery/presentation/styles/text_input_field/avatar_suggestion_item_widget_styles.dart
- lib/features/email_recovery/presentation/styles/text_input_field/avatar_tag_item_widget_styles.dart
- lib/features/email_recovery/presentation/styles/text_input_field/suggestion_item_widget_styles.dart
- lib/features/email_recovery/presentation/styles/text_input_field/suggestion_tag_item_widget_styles.dart
- lib/features/email_recovery/presentation/styles/text_input_field/text_input_field_widget_styles.dart
- lib/features/email_recovery/presentation/styles/text_input_field/text_input_suggestion_field_widget_styles.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_desktop_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_mobile_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_tablet_builder.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/avatar_suggestion_item_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/avatar_tag_item_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/suggestion_item_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/suggestion_tag_item_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/text_input_field_suggestion_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/text_input_field_widget.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
---
#2101 
---
https://github.com/linagora/tmail-flutter/pull/2410
---
- Web
https://github.com/linagora/tmail-flutter/assets/80142234/7f229cb0-6e96-4c88-9c90-20062ee28465
- Android
https://github.com/linagora/tmail-flutter/assets/80142234/7b0a2c45-9b5b-4b96-b4a5-0704537c3e6e
> TF-2101 [Part 3] Add text input fields to recover deleted message dialog

- lib/features/base/base_controller.dart
#2460 
```
{
"sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
"methodResponses": [
[
"FirebaseRegistration/set",
{
"notCreated": {
"3d1b3b62-5237-49a8-9261-5f22b104a665": {
"type": "invalidArguments",
"description": "Token is not valid",
"properties": [
"token"
]
}
}
},
"c0"
]
]
}
```
> TF-2460 Real time update for web broken

- lib/features/email/presentation/extensions/calendar_event_extension.dart
- test/features/email/presentation/extensions/calendar_event_extension_test.dart
---
#2465 
---
https://github.com/linagora/tmail-flutter/assets/80142234/d023b5bf-b230-47b8-afad-2110915d1964
> [bugfix] TF-2465 Blue bar parsing failed for the time of event

- core/lib/presentation/extensions/uri_extension.dart
- core/test/presentation/extensions/uri_extension_test.dart
- lib/features/home/domain/extensions/session_extensions.dart
- model/lib/extensions/session_extension.dart
> TF-2497 Support HTTP in server url

- ios/Podfile.lock
- ios/Runner/AppDelegate.swift
- ios/Runner/en.lproj/Localizable.strings
- ios/Runner/fr.lproj/Localizable.strings
- ios/Runner/ru.lproj/Localizable.strings
- ios/Runner/vi.lproj/Localizable.strings
- ios/TwakeCore/Extensions/StringExtensions.swift
- ios/TwakeCore/Jmap/JmapClient.swift
- ios/TwakeCore/Jmap/Model/Email/Email.swift
- ios/TwakeCore/Jmap/Utils/JmapConstants.swift
- ios/TwakeMailNSE/Keychain/KeyChainControllerDelegate.swift
- ios/TwakeMailNSE/Keychain/KeychainController.swift
- ios/TwakeMailNSE/Model/KeychainSharingSession.swift
- ios/TwakeMailNSE/NotificationService.swift
- lib/features/mailbox/data/datasource_impl/state_datasource_impl.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/data/datasource_impl/cache_fcm_datasource_impl.dart
- lib/features/push_notification/data/extensions/keychain_sharing_session_extension.dart
- lib/features/push_notification/data/keychain/keychain_sharing_session.dart
- lib/features/push_notification/data/local/fcm_cache_manager.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- lib/main/utils/ios_sharing_manager.dart
#2464 
- Due to the process of updating `Keychain` in NSE in the form of `JSON String`. But when parsing it is `Data`
https://github.com/linagora/tmail-flutter/assets/80730648/835b7119-30b8-4844-aefc-49dead949e83
> TF-2464 Fix plain notification iOS

- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- #2509 
https://github.com/linagora/tmail-flutter/assets/99852347/e9f2783e-ac1c-4230-bf87-7c106f3c4f35
> TF-2509: Enable spellcheck for composer on web

- contact/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/composer/presentation/composer_controller.dart
- lib/features/thread/data/extensions/list_email_extension.dart
- lib/features/thread/data/network/thread_api.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- test/features/email/sorting_list_email_by_order_id_list_test.dart
#2528 
- Need merged: https://github.com/linagora/jmap-dart-client/pull/77 
https://github.com/linagora/tmail-flutter/assets/80730648/21bce0cd-2443-43fe-ae1a-99e08995b8ad
> TF-2528 Sorting Emails by order ids list of `Email/query`

- android/app/build.gradle
- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- core/lib/presentation/views/text/type_ahead_form_field_builder.dart
- core/pubspec.lock
- core/pubspec.yaml
- ios/Podfile.lock
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/styles/mobile/mobile_container_view_style.dart
- lib/features/composer/presentation/view/mobile/mobile_container_view.dart
- lib/features/composer/presentation/view/mobile/tablet_container_view.dart
- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/identity_creator/presentation/widgets/identity_input_with_drop_list_field_builder.dart
- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/widgets/dns_lookup_input_form.dart
- lib/features/manage_account/presentation/menu/settings/settings_view.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- pubspec.lock
- pubspec.yaml
- web/index.html
#2475
- Need merged:
- rich_text_composer: https://github.com/linagora/rich-text-composer/pull/25
- html_editor_enhanced: https://github.com/linagora/html-editor-enhanced/pull/27
- flutter_date_range_picker: https://github.com/linagora/flutter-date-range-picker/pull/12
- super_tag_editor: https://github.com/dab246/super_tag_editor/pull/36
- Mobile Android
[demo-mobile-android.webm](https://github.com/linagora/tmail-flutter/assets/80730648/676847bb-8ec8-425d-aeb8-abf857d1c1c7)
- iPhone
https://github.com/linagora/tmail-flutter/assets/80730648/7f57494d-f4e1-4503-8876-ba79b42ff347
- iPad
https://github.com/linagora/tmail-flutter/assets/80730648/627f996e-18de-4592-a754-386adb0b72bb
- Tablet
[demo-tablet.webm](https://github.com/linagora/tmail-flutter/assets/80730648/3e4b5e21-a678-40f8-8190-326 …
> TF-2475 Fix rich text not work on android

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_receiver_widget.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
#2531 
https://github.com/linagora/tmail-flutter/assets/80730648/7841ba59-c310-4376-a69e-2021a6bddbb9
> TF-2531 Fix cannot see all recipients list if email have a lot of recipients

- lib/features/composer/presentation/widgets/recipient_suggestion_item_widget.dart
- lib/features/email_recovery/presentation/widgets/text_input_field/suggestion_item_widget.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/autocomplete_suggestion_item_widget_web.dart
#2538 
[reproduce-android.webm](https://github.com/linagora/tmail-flutter/assets/80730648/7f01368a-c358-4316-b044-9f143dde35d4)
[Screen_recording_20240202_164602.webm](https://github.com/linagora/tmail-flutter/assets/80730648/9e958e67-f267-44f7-b883-b419b349efe2)
> TF-2538 Fix email suggestion list having weird white overlapping

- lib/features/composer/presentation/widgets/recipient_tag_item_widget.dart
> TF-2539 Fix selected email address at `to/cc/bcc` fields are having weird border

- core/lib/utils/platform_info.dart
- lib/features/composer/presentation/styles/recipient_tag_item_widget_style.dart
- lib/features/composer/presentation/widgets/recipient_tag_item_widget.dart
#2540 
[demo.webm](https://github.com/linagora/tmail-flutter/assets/80730648/517660eb-978b-4241-aea6-baf45fc596bf)
> TF-2540 Fix selected email address at `to/cc/ bcc` fields are moving too close to the bottom of input field

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- `flutter_inappwebview` version `6.0.0` requirements `Xcode version >= 14.3`
- Currently CI/CD using Xcode version: `14.2`
> Hotfix: Build app ios failed on CI/CD

- lib/features/email/presentation/email_view.dart
- lib/features/thread/presentation/thread_view.dart
- #2479 
https://github.com/linagora/tmail-flutter/assets/80142234/ceda644b-f543-4155-9b8d-cb4a2ba22ec8
> TF-2479 Hide mark as spam action for team-mailbox

- docs/adr/0034-error-handling-on-no-longer-valid-oidc-token.md
- lib/features/base/base_controller.dart
- lib/features/base/reloadable/reloadable_controller.dart
#2592 
https://github.com/linagora/tmail-flutter/assets/80730648/01a280c9-9659-4f1d-9293-dd7aaef9396b
> TF-2592 Error handling on no logger valid OIDC token

- docs/adr/0035-error-handling-on-no-longer-valid-oidc-token.md
- docs/adr/0036-mailto-uri-chemes-to-interact-twake-mail.md
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailto/presentation/model/mailto_arguments.dart
- lib/main/routes/navigation_router.dart
- lib/main/routes/route_utils.dart
- test/main/routes/route_utils_test.dart
#2596 
https://github.com/linagora/tmail-flutter/assets/80730648/77e2f4a9-db76-49a9-b0ee-3641744a4e2e
> TF-2596 Mailto invalid with several recipients

- ios/Podfile.lock
- ios/Runner/AppDelegate.swift
- ios/Runner/en.lproj/Localizable.strings
- ios/Runner/fr.lproj/Localizable.strings
- ios/Runner/ru.lproj/Localizable.strings
- ios/Runner/vi.lproj/Localizable.strings
- ios/TwakeCore/Extensions/StringExtensions.swift
- ios/TwakeCore/Jmap/JmapClient.swift
- ios/TwakeCore/Jmap/Model/Email/Email.swift
- ios/TwakeCore/Jmap/Utils/JmapConstants.swift
- ios/TwakeMailNSE/Keychain/KeyChainControllerDelegate.swift
- ios/TwakeMailNSE/Keychain/KeychainController.swift
- ios/TwakeMailNSE/Model/KeychainSharingSession.swift
- ios/TwakeMailNSE/NotificationService.swift
- lib/features/mailbox/data/datasource_impl/state_datasource_impl.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/push_notification/data/datasource_impl/cache_fcm_datasource_impl.dart
- lib/features/push_notification/data/extensions/keychain_sharing_session_extension.dart
- lib/features/push_notification/data/keychain/keychain_sharing_session.dart
- lib/features/push_notification/data/local/fcm_cache_manager.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- lib/main/utils/ios_sharing_manager.dart
> Cherry pick notification plain iOS from `master` to `v0.11.3-patch-x`

- docs/adr/0037-only-request-full-email-get-one-by-one.md
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/usecases/get_list_detailed_email_by_id_interator.dart
- lib/features/push_notification/data/repository/fcm_repository_impl.dart
- lib/features/push_notification/domain/state/get_new_receive_email_from_notification_state.dart
- lib/features/push_notification/domain/usecases/get_new_receive_email_from_notification_interactor.dart
- lib/features/push_notification/domain/utils/fcm_constants.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
#2611 
https://github.com/linagora/tmail-flutter/assets/80730648/266058df-abbc-4654-9b49-299dc62db867
> TF-2611 [PART-I ] Only request full email get one-by-one for Android 

- lib/features/email/presentation/extensions/calendar_event_extension.dart
- test/features/features/email/presentation/extensions/calendar_event_extension_test.dart
- #2502 
https://github.com/linagora/tmail-flutter/assets/80142234/6bafae5d-35e7-4ce6-a5fd-9948c2ea3f21
> TF-2502 Display all day event

- web/i18n/translater.js
- web/index.html
- #2622 
- Smart banner text is disappeared in IOS WebApp
- IOS
https://github.com/linagora/tmail-flutter/assets/80142234/7ab60267-1f77-464e-a01c-fd5dbcd8c951
- Android
https://github.com/linagora/tmail-flutter/assets/80142234/002d438e-eab0-4fb4-b5a1-7f5cb9d88d94
- Web
https://github.com/linagora/tmail-flutter/assets/80142234/b09b2f0a-addd-4180-be7f-6b4ac5fa1b4e
> TF-2622 Fix smart banner text disappear in IOS web app

- lib/features/email/presentation/extensions/calendar_event_extension.dart
- test/features/email/presentation/extensions/calendar_event_extension_test.dart
Cherry from `master`
https://github.com/linagora/tmail-flutter/assets/80142234/3850fa82-6d74-4448-bbea-f9f26da26022
> Fix blue bar time

- lib/features/composer/presentation/composer_controller.dart
#2623 
- Due to the implementation of `delay` time when setting `focus` for the editor
https://github.com/linagora/tmail-flutter/assets/80730648/bf876d35-c32f-4913-9009-3d45035dcc6c
> TF-2623 Fix blink blink when user click on recipients filed in an email long recipients

- lib/features/base/base_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/push_notification/domain/state/get_email_changes_to_remove_notification_state.dart
- lib/features/push_notification/domain/state/get_mailboxes_not_put_notifications_state.dart
- lib/features/push_notification/domain/usecases/get_email_changes_to_remove_notification_interactor.dart
- lib/features/push_notification/domain/usecases/get_mailboxes_not_put_notifications_interactor.dart
- lib/features/push_notification/presentation/config/fcm_configuration.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_config.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
#2599 
https://github.com/linagora/tmail-flutter/assets/80730648/b75960fd-b2f0-4860-9cbf-fedb16e39eda
> TF-2599 Fix notification flood

- lib/l10n/intl_fr.arb
> FR translation: vacances => réponse automatique (like GMail) (#2594)

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/login/data/network/interceptors/authorization_interceptors.dart
- lib/features/upload/presentation/controller/upload_controller.dart
#2597 
https://github.com/linagora/tmail-flutter/assets/80730648/2d468688-902a-4f04-9497-9b132b3fc69d
> TF-2597 Fix can click close composer button several time

- docs/adr/0040-handle-multiple-attachment-actions
- lib/features/email/domain/state/download_attachment_for_web_state.dart
- lib/features/email/domain/state/view_attachment_for_web_state.dart
- lib/features/email/domain/usecases/download_attachment_for_web_interactor.dart
- lib/features/email/domain/usecases/view_attachment_for_web_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/utils/email_utils.dart
- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_item_widget.dart
- test/features/email/domain/usecases/view_attachment_for_web_interactor_test.dart
#2628 
- Firefox
https://github.com/linagora/tmail-flutter/assets/160106668/42bba42c-c4f5-455e-b45b-1e5e322f53d7
- Safari
https://github.com/linagora/tmail-flutter/assets/160106668/d6635d4f-8c0f-4e0c-99cc-83b32d8045a2
- Chrome
https://github.com/linagora/tmail-flutter/assets/160106668/b7c03744-4f61-4d42-a38d-13c16d8797b0
> TF-2628 [Part-2] Handle multiple attachment actions

- .github/workflows/analyze-test.yaml
- lib/features/server_settings/data/datasource/server_settings_data_source.dart
- lib/features/server_settings/domain/repository/server_settings_repository.dart
- pubspec.lock
- pubspec.yaml
- scripts/prebuild.sh
- server_settings/.gitignore
- server_settings/.metadata
- server_settings/README.md
- server_settings/lib/server_settings/capability_server_settings.dart
- server_settings/lib/server_settings/converter/always_read_receipt_nullable_converter.dart
- server_settings/lib/server_settings/converter/server_settings_id_nullable_converter.dart
- server_settings/lib/server_settings/get/get_server_settings_method.dart
- server_settings/lib/server_settings/get/get_server_settings_response.dart
- server_settings/lib/server_settings/server_settings.dart
- server_settings/lib/server_settings/server_settings_id.dart
- server_settings/lib/server_settings/set/set_server_settings_method.dart
- server_settings/lib/server_settings/set/set_server_settings_response.dart
- server_settings/lib/server_settings/tmail_server_settings.dart
- server_settings/pubspec.yaml
- server_settings/test/server_settings/get/get_server_settings_method_test.dart
- server_settings/test/server_settings/set/set_server_settings_method_test.dart
- #2615 
- #2677  
- Server settings module with:
- Get server settings method
- Set server settings method
- Abstract data source & repo for Server settings
> TF-2677 Create server settings module and abstractions

- lib/l10n/intl_vi.arb
Currently translated at 100.0% (582 of 582 strings)
Translation: Linagora/TeamMail
Translate-URL: https://hosted.weblate.org/projects/linagora/teammail/vi/
> Translated using Weblate (Vietnamese)

- lib/features/server_settings/data/datasource_impl/remote_server_settings_data_source_impl.dart
- lib/features/server_settings/data/network/server_settings_api.dart
- lib/features/server_settings/domain/exceptions/server_settings_exception.dart
- test/features/server_settings/data/datasource_impl/remote_server_settings_data_source_impl_test.dart
- test/features/server_settings/data/network/server_settings_api_test.dart
- #2615 
- #2678 
- Server settings API
- Remote implementation of Server settings data source
> TF-2678 implement server settings data source

- lib/features/server_settings/data/repository/server_settings_repository_impl.dart
- test/features/server_settings/data/repository/server_settings_repository_impl_test.dart
- #2615 
- #2679
- Implementation of Server settings repository
> TF-2679 Implement server settings repository

- lib/features/composer/domain/extensions/email_request_extension.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/offline_mode/bindings/sending_email_interactor_bindings.dart
- lib/main/bindings/network/network_bindings.dart
- model/lib/extensions/email_extension.dart
- #2615 
- #2680 
**Web**
https://github.com/linagora/tmail-flutter/assets/160106668/48653e2b-45fb-4cb9-9cf4-4b823054ef21
**Mobile**
https://github.com/linagora/tmail-flutter/assets/160106668/9acb2035-e47d-4d01-b75a-251ced81f183
> TF-2680 Integrate get always read receipt on email send

- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/server_settings/domain/state/get_always_read_receipt_setting_state.dart
- lib/features/server_settings/domain/usecases/get_always_read_receipt_setting_interactor.dart
- test/features/server_settings/domain/usecases/get_always_read_receipt_setting_interactor_test.dart
- #2615 
- #2681 
**Web**
https://github.com/linagora/tmail-flutter/assets/160106668/8bb00544-ed84-4260-802e-25acc6af44ec
**Mobile**
https://github.com/linagora/tmail-flutter/assets/160106668/68b717be-8c19-4d68-92cf-f8e0acad6f52
> TF-2681 Create get always read receipt interactor and integrate Composer UI

- lib/features/identity_creator/presentation/identity_creator_view.dart
- #2675 
**Web**
https://github.com/linagora/tmail-flutter/assets/160106668/fdbf5530-8053-4cd3-8d02-d87aa3a9d0f8
**Mobile**
https://github.com/linagora/tmail-flutter/assets/160106668/80307042-12ee-44b0-82bf-1b3fdee7059f
> TF-2675 Pin save button in edit identity dialog

- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/manage_account/presentation/always_read_receipt/always_read_receipt_controller.dart
- lib/features/offline_mode/bindings/sending_email_interactor_bindings.dart
- lib/features/server_settings/domain/state/update_always_read_receipt_setting_state.dart
- lib/features/server_settings/domain/usecases/update_always_read_receipt_setting_interactor.dart
- test/features/server_settings/domain/usecases/update_always_read_receipt_setting_interactor_test.dart
- #2615 
- #2683 
**Web**
https://github.com/linagora/tmail-flutter/assets/160106668/d910d3ab-1356-4bc0-837b-e2b7283eae7c
**Mobile**
https://github.com/linagora/tmail-flutter/assets/160106668/734112a1-4a18-49b9-838c-d7101b66b12e
> TF-2683 Integrate update always read receipt setting in composer

- pubspec.lock
- #2658 
- https://github.com/linagora/flutter-date-range-picker/pull/13
> TF-2658 Update pubspec for date range picker

- core/lib/data/network/download/download_manager.dart
- core/lib/utils/html/html_utils.dart
- core/lib/utils/html/js_interop_stub.dart
- lib/main/bindings/network/network_bindings.dart
- lib/main/bindings/network/network_isolate_binding.dart
- #2708 
- Browser's memory is properly cleaned up when window's closed
https://github.com/linagora/tmail-flutter/assets/160106668/4689d5b2-b2a5-4d04-9752-57beb45a3301
**Responsive**
https://github.com/linagora/tmail-flutter/assets/160106668/81f6e223-2ad8-43cf-8f28-f76ae5d78a92
> TF-2708 Allow Chrome to download PDF after view

- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_item_widget.dart
Mobile cannot download attachment when tapping on it
https://github.com/linagora/tmail-flutter/assets/160106668/7f6b99c9-bf41-459f-b094-bd3572461c7a
> Fix mobile cannot download attachment

- core/lib/domain/extensions/datetime_extension.dart
- core/lib/utils/print_utils.dart
- lib/features/email/data/datasource_impl/print_file_datasource_impl.dart
- lib/features/email/domain/model/email_print.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
- lib/features/email/presentation/widgets/received_time_builder.dart
- lib/features/mailbox_dashboard/presentation/model/search/advanced_search_filter.dart
- lib/l10n/intl_ar.arb
- lib/l10n/intl_en.arb
- lib/l10n/intl_fr.arb
- lib/l10n/intl_it.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
#2713 
https://github.com/linagora/tmail-flutter/assets/80730648/26548f82-b75e-4dac-84f7-8fb1565df690
> TF-2713 Small evolution for printing

- lib/features/composer/presentation/composer_controller.dart
- lib/features/manage_account/presentation/always_read_receipt/always_read_receipt_controller.dart
- lib/features/server_settings/domain/usecases/get_always_read_receipt_setting_interactor.dart
- #2615 
https://github.com/linagora/tmail-flutter/assets/160106668/0613e4c3-16dd-41fa-ba45-d4a54251b365
> Update defaut read receipt setting to false

- lib/features/email/presentation/widgets/email_attachments_widget.dart
- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- #2628 
https://github.com/linagora/tmail-flutter/assets/160106668/524bcc2f-29b7-4784-a978-6f8a7acdda1a
> TF-2628 Disable view attachment in mobile web

- core/lib/data/network/download/download_manager.dart
- core/lib/utils/html/html_utils.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
- #2737 
**Chrome**
https://github.com/linagora/tmail-flutter/assets/160106668/d5ca3a56-b648-4b12-884d-bcc34265208c
**Firefox**
https://github.com/linagora/tmail-flutter/assets/160106668/fc124e4d-7e87-48ea-9bfc-3a9f3c7a6bb1
**Safari**
https://github.com/linagora/tmail-flutter/assets/160106668/99d7e621-65f3-4b04-b2bc-31453f4f99b1
> TF-2737 Separate PDF view handler between each browser

- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/l10n/intl_ar.arb
- lib/l10n/intl_en.arb
- lib/l10n/intl_fr.arb
- lib/l10n/intl_it.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
#2646 
https://github.com/linagora/tmail-flutter/assets/80730648/5923c241-69c2-49e9-8c5c-ac03e03c6757
> TF-2646 Fix confused `Select all` name

- pubspec.lock
> Update flutter_date_range_picker dependency

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- test/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller_test.dart
- #2694 
https://github.com/linagora/tmail-flutter/assets/160106668/69395e7d-7a19-4f8b-8dc7-977cfa2304ca
https://github.com/linagora/tmail-flutter/assets/160106668/03b5271f-5b17-4c8a-8615-7082626f362b
> TF-2694 Clear sort order when mailbox is tapped

- core/lib/data/network/download/download_manager.dart
- core/lib/utils/html/html_utils.dart
- lib/features/mailbox_dashboard/presentation/widgets/download/download_task_item_widget.dart
#2754 
-  `PDFObject.js` library render html error on `Microsoft EDGE/ Opera`
- Use `PDF.js` as same `Chrome` platform
https://github.com/linagora/tmail-flutter/assets/80730648/1c78e619-afb3-4bf9-8dd3-fee61c85f6db
> TF-2754 Fix error viewing pdf on Microsoft EDGE

- lib/features/composer/presentation/view/mobile/mobile_container_view.dart
- lib/features/composer/presentation/view/mobile/tablet_container_view.dart
#2735 
- Android 14:
https://github.com/linagora/tmail-flutter/assets/80730648/e9c9b1ca-cf01-4321-8253-144907fdf9e1
-iOS 17.2:
https://github.com/linagora/tmail-flutter/assets/80730648/e8039085-8eac-46c6-b8b0-4f5a811fcf6b
> TF-2735 Gesture back for user in composer on mobile

- pubspec.lock
- #2658 
https://github.com/linagora/tmail-flutter/assets/160106668/9ebb4d0f-99df-4d6e-8779-e522e7ef9334
> TF-2658 Fix date range picker background color

- core/lib/utils/html/html_utils.dart
- #2708 
**Chrome**
https://github.com/linagora/tmail-flutter/assets/160106668/8a386d65-dc65-49cb-96fe-0425ce399ab5
**Edge**
https://github.com/linagora/tmail-flutter/assets/160106668/0ec7cf52-aa7d-4c3c-9880-19ff3752fa1e
> TF-2708 Oversized pdf

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- #2628 
**Mobile browser**
https://github.com/linagora/tmail-flutter/assets/160106668/61e23a42-2281-44d2-a8b4-d2466f1b9f98
**Web**
https://github.com/linagora/tmail-flutter/assets/160106668/ab9c1010-3c40-45dd-807e-759dd8bdc41c
> TF-2628 Temporary disable preview PDF

- core/lib/presentation/utils/html_transformer/dom/remove_max_width_in_image_style_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_style_tag_outside_transformers.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- core/lib/utils/print_utils.dart
#2772 
- Due some `style` tag in html make affect to display when printing
- Remove `style` tag outside html
- Revert `max-width` in style html to origin
https://github.com/linagora/tmail-flutter/assets/80730648/c4e9ce19-ab1e-4f2d-aff2-07f1c8affca0
> TF-2772 Fix print long mail start with a blank page

- docs/adr/0043-fix-memory-leak-with-controller-dispose.md
- lib/features/base/state/base_ui_state.dart
- lib/features/composer/presentation/composer_controller.dart
- #2533 
https://github.com/linagora/tmail-flutter/assets/160106668/8d79f169-b592-4965-8533-99224e91cee8
https://github.com/linagora/tmail-flutter/assets/160106668/e1ee69ce-b62f-4294-9fa8-53034e9500c8
> TF-2533 [PART-3] Composer memory leak

- lib/features/mailbox_dashboard/data/model/composer_cache.dart
https://github.com/linagora/tmail-flutter/assets/6462404/76f9cca5-c439-45d3-8286-5a8da7303b81
> Reload still keep composer open

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- pubspec.lock
- pubspec.yaml
- #2533 
- https://github.com/linagora/html-editor-enhanced/pull/34
**Before**
https://github.com/linagora/tmail-flutter/assets/160106668/d10eed44-594d-4de6-a1fa-2e9c30a64929
**After**
https://github.com/linagora/tmail-flutter/assets/160106668/a5bdfcb4-6ddc-4c25-941f-febc43101457
> TF-2533 [PART-2] Remove email detail iframe dependencies

- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
> TF-2758 Email event description in html

- lib/features/upload/presentation/controller/upload_controller.dart
- pubspec.lock
- pubspec.yaml
- #2533 
**Composer before**
https://github.com/linagora/tmail-flutter/assets/160106668/2f332d7b-3d51-42e5-b8ee-9a00c0356ffe
**Composer after**
https://github.com/linagora/tmail-flutter/assets/160106668/b8453acc-c7ba-44c3-b8af-2f2d93dcc311
**Identity edit before**
https://github.com/linagora/tmail-flutter/assets/160106668/6b9b8491-35ee-436e-bb9b-1686feab78ad
**Identity edit after**
https://github.com/linagora/tmail-flutter/assets/160106668/1602c32b-0a13-44c9-ab71-60f32b908a11
> TF-2533 [Part-4] File picker memory leak

- core/lib/presentation/utils/html_transformer/base/dom_transformer.dart
- core/lib/presentation/utils/html_transformer/dom/add_lazy_loading_for_background_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_collapsed_signature_button_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_lazy_loading_for_background_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_lazy_loading_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_tooltip_link_transformers.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- core/lib/utils/html/html_interaction.dart
- lib/features/email/domain/model/email_print.dart
- lib/features/email/domain/usecases/print_email_interactor.dart
- lib/features/email/presentation/action/email_ui_action.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
#2785 
- The email content has not yet been loaded but the email is printed
- Wait for the email to loaded successfully before printing the email
https://github.com/linagora/tmail-flutter/assets/80730648/8d0d8f41-dfa0-464b-84e5-358da45bdce3
> TF-2785 Fix print feature empty when clicked too early

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/styles/composer_style.dart
- pubspec.lock
- #2671 
- Need merged: https://github.com/linagora/enough_html_editor/pull/29
**iOS**
https://github.com/linagora/tmail-flutter/assets/160106668/33e955dd-99b6-4f4a-b13e-cb5cae98be96
https://github.com/linagora/tmail-flutter/assets/160106668/1c730350-7fb0-4b49-889d-9e82bdd1523d
https://github.com/linagora/tmail-flutter/assets/160106668/88598358-ff54-47b3-b8f1-6b8aacf2de78
**Android**
https://github.com/linagora/tmail-flutter/assets/160106668/cf9e28e7-210b-4f5f-9989-254548115bfd
> TF-2671 signature clipped when composing long content

- core/lib/presentation/extensions/string_extension.dart
- core/lib/presentation/views/text/rich_text_builder.dart
- core/lib/presentation/views/text/text_overflow_builder.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
#2122 
https://github.com/linagora/tmail-flutter/assets/80730648/960a08af-db55-4e26-b17b-6408514fe29b
> TF-2122 Fix searching result text font and highlight incorrect

- contact/pubspec.lock
- contact/pubspec.yaml
- email_recovery/pubspec.lock
- email_recovery/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- lib/features/email/data/datasource/calendar_event_datasource.dart
- lib/features/email/data/datasource_impl/calendar_event_datasource_impl.dart
- lib/features/email/data/datasource_impl/local_calendar_event_datasource_impl.dart
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/data/repository/calendar_event_repository_impl.dart
- lib/features/email/domain/exceptions/calendar_event_exceptions.dart
- lib/features/email/domain/repository/calendar_event_repository.dart
- model/pubspec.lock
- model/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
- server_settings/pubspec.yaml
- test/features/email/data/repository/calendar_event_repository_impl_test.dart
> [PART-II] TF-2800 Calendar event accept data source & repo 

- lib/features/manage_account/presentation/forward/widgets/autocomplete_contact_text_field_with_tags.dart
#2830 
https://github.com/linagora/tmail-flutter/assets/80730648/d3684a24-8634-40e7-83f5-742ec5cbafef
> TF-2830 Fix forwards add recipient is buggy

- lib/features/mailbox/presentation/widgets/user_information_widget.dart
> TF-2836 Fix button with no effect on android

- lib/features/email/data/datasource/calendar_event_datasource.dart
- lib/features/email/data/datasource_impl/calendar_event_datasource_impl.dart
- lib/features/email/data/datasource_impl/local_calendar_event_datasource_impl.dart
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/data/repository/calendar_event_repository_impl.dart
- lib/features/email/domain/repository/calendar_event_repository.dart
- lib/features/email/domain/state/calendar_event_accept_state.dart
- lib/features/email/domain/state/calendar_event_reply_state.dart
- lib/features/email/domain/state/parse_calendar_event_state.dart
- lib/features/email/domain/usecases/calendar_event_accept_interactor.dart
- lib/features/email/domain/usecases/parse_calendar_event_interactor.dart
- lib/features/email/presentation/bindings/calendar_event_interactor_bindings.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/model/blob_calendar_event.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_action_button_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- test/features/email/domain/usecases/calendar_event_accept_interactor_test.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
> [PART-III] TF-2802 Calendar event accept interactor and controller

- contact/pubspec.lock
- email_recovery/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/email/data/datasource/calendar_event_datasource.dart
- lib/features/email/data/datasource_impl/calendar_event_datasource_impl.dart
- lib/features/email/data/datasource_impl/local_calendar_event_datasource_impl.dart
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/data/repository/calendar_event_repository_impl.dart
- lib/features/email/domain/exceptions/calendar_event_exceptions.dart
- lib/features/email/domain/repository/calendar_event_repository.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- test/features/email/data/repository/calendar_event_repository_impl_test.dart
> [Part-V] TF-2819 Calendar event maybe data source and repo

- lib/features/email/domain/state/calendar_event_maybe_state.dart
- lib/features/email/domain/usecases/maybe_calendar_event_interactor.dart
- lib/features/email/presentation/bindings/calendar_event_interactor_bindings.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- test/features/email/domain/usecases/maybe_calendar_event_interactor_test.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
> [Part-VI] TF-2821 Calendar event maybe interactor and controller

- lib/features/email/data/datasource/calendar_event_datasource.dart
- lib/features/email/data/datasource_impl/calendar_event_datasource_impl.dart
- lib/features/email/data/datasource_impl/local_calendar_event_datasource_impl.dart
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/data/repository/calendar_event_repository_impl.dart
- lib/features/email/domain/exceptions/calendar_event_exceptions.dart
- lib/features/email/domain/repository/calendar_event_repository.dart
- test/features/email/data/repository/calendar_event_repository_impl_test.dart
> [Part-VII] TF-2838 Calendar event reject data source and repo

- docs/adr/0045-memory-leak-with-js-lifecycle.md
> TF-2533 Add ADR on memory leak js lifecycle

- docs/adr/0045-memory-leak-with-js-lifecycle.md
- docs/adr/0046-enable-silent-for-notification-in-device-android-when-use-flutter-local-notification-library.md
- lib/features/home/domain/state/get_session_state.dart
- lib/features/home/domain/usecases/get_session_interactor.dart
- lib/features/login/domain/state/get_credential_state.dart
- lib/features/login/domain/state/get_stored_token_oidc_state.dart
- lib/features/login/domain/usecases/get_authenticated_account_interactor.dart
- lib/features/login/domain/usecases/get_credential_interactor.dart
- lib/features/login/domain/usecases/get_stored_token_oidc_interactor.dart
- lib/features/push_notification/data/repository/fcm_repository_impl.dart
- lib/features/push_notification/presentation/controller/fcm_message_controller.dart
- lib/features/push_notification/presentation/listener/email_change_listener.dart
- lib/features/push_notification/presentation/notification/local_notification_config.dart
- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- pubspec.lock
- pubspec.yaml
- Set 
- `silent=true` for all notifications with id `EmailId` 
- `silent=false` for notifications with id `GroupdId`.
1. Notifications when  `disconnected` & `reconnected`:
https://github.com/linagora/tmail-flutter/assets/80730648/c44195cf-753d-496b-94b8-fd9ab0c45953
2. Notification unstable when terminated:
- Before: 
https://github.com/linagora/tmail-flutter/assets/80730648/d759fd90-2013-4632-b51d-aa149a6d30b2
- After: 
https://github.com/linagora/tmail-flutter/assets/80730648/a35fad3b-ee5f-43c3-b8e0-d3bd51d1c74a
> Fix notification flood on android

- pubspec.lock
- pubspec.yaml
- Build android app failed on CI
https://github.com/linagora/tmail-flutter/actions/runs/9312253546
> Hot fix build android failed on CI

- .github/workflows/analyze-test.yaml
- .github/workflows/build.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/release.yaml
- .github/workflows/test-reports.yaml
Also fixed test reporting integration
> Bumped versions of deprecated actions

- .github/workflows/analyze-test.yaml
- .github/workflows/build.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/image.yaml
- .github/workflows/release.yaml
> Bumped action versions to their latest stable

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/styles/mobile/tablet_bottom_bar_composer_widget_style.dart
- lib/features/composer/presentation/widgets/mobile/tablet_bottom_bar_composer_widget.dart
- lib/features/composer/presentation/widgets/web/bottom_bar_composer_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#2945
- Web:
https://github.com/linagora/tmail-flutter/assets/80730648/220f74ac-0900-4a46-adbe-de2364de10a0
- Tablet:
[demo-tablet.webm](https://github.com/linagora/tmail-flutter/assets/80730648/9408771f-4bfa-4156-8e5e-0a4a3c4310ec)
> TF-2945 Quick select for read receipt in composer

- lib/features/mailbox/presentation/widgets/user_information_widget.dart
- lib/features/mailbox_dashboard/presentation/mixin/user_setting_popup_menu_mixin.dart
#2946
https://github.com/linagora/tmail-flutter/assets/80730648/3d441773-c13f-4add-952a-fe273a8f79d6
https://github.com/user-attachments/assets/943ff15b-e9d4-4152-8411-555f55d6902d
https://github.com/user-attachments/assets/75b50ecf-7d0d-4001-9df7-de080fc90cbe
> TF-2946 Should have copy action to copy own email

- lib/features/email/presentation/widgets/email_receiver_widget.dart
#3000 
- Mobile:
[demo-android.webm](https://github.com/user-attachments/assets/716e111f-38f6-4cd7-bd88-55f1a65332bd)
- Web:
https://github.com/user-attachments/assets/0d2b513b-f8f7-49c0-ad7b-a0d20ef72322
> TF-3000 Fix long list recipient overlay in content body view

- lib/features/mailbox/presentation/mailbox_view_web.dart
#2806 
https://github.com/linagora/tmail-flutter/assets/80730648/db708782-eb89-49fa-afe5-dd1c47bd789f
> TF-2806 Disable reloading of mailbox list on web browser

- core/lib/presentation/extensions/uri_extension.dart
- core/test/presentation/extensions/uri_extension_test.dart
> Hot-fix API Url concat incorrect

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identities_radio_list_builder.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identity_loading_widget.dart
#2676 
#2724 
- `#2676`
https://github.com/linagora/tmail-flutter/assets/80730648/93b90c7c-3be0-4753-b1e4-b8b96f3869ce
- `#2724`
https://github.com/linagora/tmail-flutter/assets/80730648/758accd4-5d92-46b6-80ba-7624294502a3
> TF-2676, 2724 Fix creating identity with space only in name

- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/search/email/presentation/search_email_view.dart
#2771 
https://github.com/user-attachments/assets/01ee894a-e97e-4841-b83c-99b2df121b63
> TF-2771 Fix show list email when user changed filter or sort order on  iOS

- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/public_asset/domain/state/remove_identity_from_public_assets_state.dart
- lib/features/public_asset/domain/usecase/add_identity_to_public_assets_interactor.dart
- lib/features/public_asset/domain/usecase/remove_identity_from_public_assets_interactor.dart
- test/features/public_asset/domain/usecase/clean_up_public_assets_interactor_test.dart
> TF-3043 Handle public asset on identity delete

- lib/features/composer/presentation/composer_controller.dart
- model/lib/extensions/email_extension.dart
#2938 
https://github.com/user-attachments/assets/7c3954e7-f15d-42a9-8c00-6384c2aab4ef
> TF-2938 Fix request read receipt is not saved onto drafts

- core/lib/presentation/extensions/uri_extension.dart
- core/test/data/network/dynamic_url_interceptor_test.dart
- core/test/presentation/extensions/uri_extension_test.dart
- lib/features/base/reloadable/reloadable_controller.dart
- test/features/login/data/repository/credential_repository_imp_test.dart
> Fix baseUrl origin and support serverUrl and apiUrl are different

- lib/features/public_asset/data/datasource/public_asset_datasource.dart
- lib/features/public_asset/data/datasource_impl/remote_public_asset_datasource_impl.dart
- lib/features/public_asset/data/network/public_asset_api.dart
- lib/features/public_asset/data/repository/public_asset_repository_impl.dart
- lib/features/public_asset/domain/repository/public_asset_repository.dart
- lib/features/public_asset/domain/usecase/add_identity_to_public_assets_interactor.dart
- lib/features/public_asset/domain/usecase/remove_identity_from_public_assets_interactor.dart
- test/features/public_asset/data/network/public_asset_api_test.dart
> TF-3083 PublicAsset Partial update

- core/test/data/network/dynamic_url_interceptor_test.dart
- core/test/presentation/extensions/uri_extension_test.dart
- lib/features/base/reloadable/reloadable_controller.dart
- test/features/login/data/repository/credential_repository_imp_test.dart
- apply from `v0.11.4xxx` to `refactor` branch also
> Cherry pick fix base url

- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/search/email/presentation/search_email_view.dart
- lib/features/thread/presentation/styles/empty_emails_widget_styles.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/empty_emails_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- test/features/thread/presentation/widgets/empty_email_widget_test.dart
#2947 
- Web:
https://github.com/user-attachments/assets/9532360d-1822-4b16-aa4e-1a9a71e3dd83
- Web with no network:
https://github.com/user-attachments/assets/82c6a461-ac83-4ef9-8293-cbef7b121856
- Mobile
https://github.com/user-attachments/assets/d42d1040-ddcd-4ff6-8517-cb9bea8baf20
> TF-2947 Fix empty view for folder when no message in folder

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- #3095 
https://github.com/user-attachments/assets/adca3267-dc5f-45e9-8d7e-e68777b7e9ca
> TF-3095 public asset handle base64 on paste

- contact/pubspec.lock
- email_recovery/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/public_asset/data/network/public_asset_api.dart
- lib/features/public_asset/domain/exceptions/public_asset_exceptions.dart
- lib/features/public_asset/domain/state/create_public_asset_state.dart
- lib/features/public_asset/domain/usecase/create_public_asset_interactor.dart
- lib/features/public_asset/presentation/public_asset_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- #3096 
- https://github.com/linagora/jmap-dart-client/pull/92
Updating
> TF-3096 PublicAsset error handling

- lib/features/rules_filter_creator/presentation/model/rule_filter_action_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- rule_filter/lib/rule_filter/rule_action.dart
`Mark as Spam` action is not displayed when edit rule filter
Spam mailbox id not found do get all mailbox not completed
https://github.com/user-attachments/assets/e83f99db-0bf8-478f-9775-be981f42b281
> [HOT-FIX] `Mark as Spam` action is not displayed when edit rule filter

- test/features/rule_filter_creator/presentation/rule_filter_creator_controller_test.dart
- test/fixtures/widget_fixtures.dart
-  [x] Write widget test for RuleFilterCreatorController
- https://github.com/linagora/tmail-flutter/pull/3109
> Write widget test for rule filter creator controller

- lib/features/identity_creator/presentation/identity_creator_view.dart
- pubspec.lock
- https://github.com/linagora/tmail-flutter/issues/3101#issuecomment-2306298330
- https://github.com/linagora/enough_html_editor/pull/33
- https://github.com/linagora/rich-text-composer/pull/29
https://github.com/user-attachments/assets/b5468152-fb83-454d-b2ae-7c23d2346892
**Rich text + lazy loading images**
https://github.com/user-attachments/assets/53d1cb98-761d-45aa-a27f-8e1537dee717
> Fix iOS Identity editor height

- README.md
> Update reference to prebuild.sh in README

- lib/features/base/mixin/date_range_picker_mixin.dart
- test/features/base/mixin/date_range_picker_mixin_test.dart
#3088 
https://github.com/user-attachments/assets/1e5c2387-0c40-488b-b991-0f146b54095d
https://github.com/user-attachments/assets/afd12d7e-4527-41c5-a4c1-855b6b19bde9
> TF-3088 Fix custom date the ending date is not included in search

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
https://github.com/user-attachments/assets/b21dea04-4929-48d2-93ad-296d47b8473a
> [HOT-FIX] Fix display custom range incorrect in search

- lib/features/rules_filter_creator/presentation/extensions/list_rule_filter_action_argument_extension.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#3051
https://github.com/user-attachments/assets/560bcd03-ce81-4d63-8a6b-c53b53e9fec1
> TF-3051 Should not allow create rule with no actions

- core/lib/presentation/views/quick_search/quick_search_input_form.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/search/email/presentation/search_email_view.dart
- lib/features/search/email/presentation/widgets/search_email_loading_bar_widget.dart
#3087
- Mobile:
[Screen_recording_20240830_144320.webm](https://github.com/user-attachments/assets/d6ac4740-c45a-44e7-8ab2-e0ba6cf9d081)
- Web:
https://github.com/user-attachments/assets/b75487cd-afdf-4c0d-935a-7da44de18d59
> TF-3087 Fix no suggestion for email address in search bar on mobile

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
#3114 
- Android:
[android.webm](https://github.com/user-attachments/assets/80659993-5c96-404d-aa25-22eee1e5eebc)
- iOS
https://github.com/user-attachments/assets/36d13160-9c50-4c22-82b8-f51a24cdae20
> TF-3114 Fix list buttons covered by keyboard in identity creator view

- lib/l10n/intl_fr.arb
Currently translated at 100.0% (636 of 636 strings)
Translation: Linagora/TeamMail
Translate-URL: https://hosted.weblate.org/projects/linagora/teammail/fr/
> [WIP] L10n v0.13.2

- lib/features/thread/presentation/thread_view.dart
> TF-3045 Hide compose button situationally on mobile

- lib/features/login/presentation/login_view.dart
- lib/features/login/presentation/login_view_web.dart
> Show app version on login view

- core/lib/domain/extensions/media_type_extension.dart
- core/lib/domain/preview/supported_preview_file_types.dart
- core/lib/presentation/views/dialog/downloading_file_dialog_builder.dart
- ios/Podfile
- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/features/base/mixin/save_media_to_gallery_mixin.dart
- lib/features/email/domain/state/export_attachment_state.dart
- lib/features/email/domain/usecases/export_attachment_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/exceptions/storage_permission_exception.dart
- lib/main/localizations/app_localizations.dart
- lib/main/permissions/permission_dialog.dart
- lib/main/permissions/storage_permission_service.dart
- pubspec.lock
- pubspec.yaml
#3047 
- Video, Image
- Android
https://github.com/user-attachments/assets/448b1817-e81c-430f-824e-b773684055fa
- iOS
https://github.com/user-attachments/assets/026890d5-334b-4fce-86b9-7aed28dae50e
> TF-3047 Improve download video on mobile

- lib/features/composer/presentation/composer_controller.dart
- #3183
https://github.com/user-attachments/assets/cb1fa1d3-e4d7-46b8-8057-666aa4489d17
> TF-3183 Clean up draft after email sent

- core/lib/presentation/extensions/color_extension.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
#3192
https://github.com/user-attachments/assets/8277835c-a8d4-4d18-bd50-84cf1b82210a
> TF-3192 [SEARCH] Update highlight style as design

- lib/features/base/mixin/auto_complete_result_mixin.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/contact/presentation/contact_controller.dart
- test/features/base/mixin/auto_complete_result_mixin_test.dart
https://github.com/user-attachments/assets/9efc2ad3-dbed-4319-af75-8566b707011f
> [SEARCH] Add suggestion for new email address in `From/To` field

- CHANGELOG.md
- pubspec.yaml
- \#3002 \[SEARCH\] More filters
- \#3004 \[SEARCH\] Fix open close advanced search looses data
- \#3005 \[SEARCH\] Easily clear From and To search result header
- \#3006 \[SEARCH\] mail address handling in quick search bar
- \#3007 \[SEARCH\] Support drag and drop between From & To field
- \#3025 \[SEARCH\] Mark as read/unread/important/unimportant action refresh email view, reset selection in Search
- \#3192 \[SEARCH\] Update highlight style as design
- \[SEARCH\] Add suggestion for From/To dialog when input is new email address
- \#3045 Hide compose button situationally on mobile
- Show app version on login view
- \#2983 Fix download EML with special character
- Fix alignment receive time in email view
- Remove space when subject is empty or null
- Remove blink blink of next & previous …
> Bump version to `v0.13.3`

- CHANGELOG.md
- docs/configuration/platform_configuration.md
- pubspec.yaml
> Add configuration for deploy platform

- docs/user-guide/profile.md
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
i am new to the repository tmail-flutter, but i saw [this issue](https://github.com/linagora/tmail-flutter/issues/3149) and it seemed pretty straightforward so i wanted to give it a try.
i changed the field label and the documentation, and corrected a few typos while i was at it.
(this new PR is created directly in upstream branch whereas [this one](https://github.com/linagora/tmail-flutter/pull/3199) was created through a fork)
> TF-3149 identity management - add clarification to the Name field

- web/i18n/de.json
> Add german to web app startup - de.json

- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
- lib/l10n/intl_en.arb
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
i am tackling [this issue](https://github.com/linagora/tmail-flutter/issues/3200)
1. i modified `Open in New Tab` to `Open in new tab`
2. the order of the options is now changed to include `Delete folder` as the last option
> TF-3200 updated the menu options

- lib/features/email/presentation/widgets/pdf_viewer/pdf_viewer.dart
#3225 
https://github.com/user-attachments/assets/8ddba6e4-33e0-4cc4-b832-21ee2c3e5c0d
> TF-3225 Fix print button blink when preview PDF

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/mailbox_creator/presentation/extensions/validator_failure_extension.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- lib/features/manage_account/presentation/vacation/vacation_controller_bindings.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#3178 
https://github.com/user-attachments/assets/c358a356-3417-4a57-935f-750df2425fe4
> TF-3178 Disable save button when rule name only contain spaces

- docs/adr/0052-logic-sort-order-in-search.md
- integration_test/robots/search_robot.dart
- integration_test/scenarios/search_email_by_date_time_and_sort_order_relevance_scenario.dart
- integration_test/tests/search/search_email_by_date_time_and_sort_order_relevance_test.dart
- lib/features/mailbox_dashboard/presentation/model/search/email_receive_time_type.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/search/email/presentation/search_email_view.dart
- lib/features/thread/presentation/thread_controller.dart
#3292 
- Demo:
https://github.com/user-attachments/assets/cf3ef70b-ae28-4998-b1b8-a10f21b7b0f7
- Integration Test:
[demo.webm](https://github.com/user-attachments/assets/2fc351d8-7c28-4738-988a-76b98b921d43)
> TF-3292 Fix [SEARCH] If I filter emails by date and then sort them by relevance, the filter isn't applied

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/extensions/calendar_attendee_extension.dart
- lib/features/email/presentation/extensions/calendar_organizer_extension.dart
- model/lib/extensions/list_email_address_extension.dart
- model/test/extensions/list_email_address_extension_test.dart
#3294 
https://github.com/user-attachments/assets/7a25becc-6819-4869-95be-9fd383efd103
> TF-3294 Fix BLUE-BAR mail to attendees duplicated recipients

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/extensions/calendar_attendee_extension.dart
- lib/features/email/presentation/extensions/calendar_organier_extension.dart
- lib/features/email/presentation/widgets/calendar_event/attendee_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_attendee_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/organizer_widget.dart
#3295
https://github.com/user-attachments/assets/11454539-0faf-4c63-90e3-9d0caee4c4d4
> TF-3295 Fix BLUE-BAR attendees mail addresses are not clickable

- core/lib/presentation/utils/html_transformer/text/standardize_html_sanitizing_transformers.dart
- core/test/utils/standardize_html_sanitizing_transformers_test.dart
#3315 
- Because the tags `google-sheets-html-origin`, `colgroup`, `col` are removed when we sanitize html.
https://github.com/user-attachments/assets/76e16514-1cbc-4efe-9f3c-7b40fa2d856e
> TF-3315 Fix TMail web could not display embedded table correctly

- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
https://github.com/user-attachments/assets/3cedf4d3-2a0d-4100-b050-9057c9f6785d
https://github.com/user-attachments/assets/a54cc4c3-c1c1-4da7-9ddf-553cc8d5274f
> Hotfix identity creator view bug

- ios/Runner/Info.plist
- lib/features/base/base_controller.dart
- lib/features/base/mixin/logout_mixin.dart
- lib/features/base/mixin/message_dialog_action_mixin.dart
- lib/features/login/data/network/authentication_client/authentication_client_mobile.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#3312 
https://github.com/user-attachments/assets/ab330154-f818-4e13-9160-4a1ecf073a39
> TF-3312 [iOS] Logout: I got asked permission to use "abcxyz.org" to login

- lib/features/base/base_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/l10n/intl_messages.arb
- lib/main.dart
- lib/main/bindings/core/core_bindings.dart
- lib/main/localizations/app_localizations.dart
- lib/main/utils/twake_app_manager.dart
- test/features/base/base_controller_test.dart
- test/features/composer/presentation/composer_controller_test.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
- test/features/home/presentation/home_controller_test.dart
- test/features/identity_creator/presentation/identity_creator_controller_test.dart
- test/features/login/presentation/login_controller_test.dart
- test/features/mailbox_dashboard/presentation/controller/advanced_filter_controller_test.dart
- test/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller_test.dart
- test/features/mailbox_dashboard/presentation/view/mailbox_dashboard_view_widget_test.dart
- test/features/manage_account/presentation/profiles/identities/identities_controller_test.dart
- test/features/rule_filter_creator/presentation/rule_filter_creator_controller_test.dart
- test/features/thread/presentation/controller/thread_controller_test.dart
#3290 
- Click `Save & Refresh ` button:
https://github.com/user-attachments/assets/162c11bc-dd97-4675-947d-d4ddfe024005
- Click `No` button:
https://github.com/user-attachments/assets/3fdf2f25-e3ba-4b42-b608-81d950c2a087
- Click `Cancel` button:
https://github.com/user-attachments/assets/91adcc8b-c91b-4e72-964e-efb785052a7f
https://github.com/user-attachments/assets/f6c3a4c1-27d7-4624-bbbd-7ef95ad73514
> TF-3290 Only display the reconnect confirmation dialog when the editor is open

- README.md
Small PR - Commit 8fe9f2ece0c8d0bd550c152ea3bc36ef20c073af moved `docker-compose.yaml`. This PR adjusts sources to changes.
> Update `docker-compose.yaml` reference

- contact/pubspec.lock
- core/lib/presentation/views/text/text_field_builder.dart
- core/pubspec.lock
- core/pubspec.yaml
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/widgets/subject_composer_widget.dart
- model/pubspec.lock
- pubspec.lock
- pubspec.yaml
- Language tool spellcheck calls LanguageTool API too many times. When changing composer subject
- Disable language tool spellcheck for text field
https://github.com/user-attachments/assets/817a4011-1e04-47cb-8b9b-4e512005c424
> Disable language tool check for text field

- lib/features/base/mixin/mailbox_action_handler_mixin.dart
- lib/features/mailbox/data/network/mailbox_isolate_worker.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/mark_mailbox_as_read_loading_banner.dart
- lib/features/thread/data/datasource/thread_datasource.dart
- lib/features/thread/data/datasource_impl/local_thread_datasource_impl.dart
- lib/features/thread/data/datasource_impl/thread_datasource_impl.dart
- lib/features/thread/data/network/thread_isolate_worker.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/domain/repository/thread_repository.dart
- lib/features/thread/domain/state/empty_spam_folder_state.dart
- lib/features/thread/domain/usecases/empty_spam_folder_interactor.dart
- lib/features/thread/domain/usecases/empty_trash_folder_interactor.dart
- lib/features/thread/presentation/thread_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/utils/toast_manager.dart
#3372
https://github.com/user-attachments/assets/2fad8ccc-3fbf-4437-9fcd-e88236ce111d
https://github.com/user-attachments/assets/42c5503c-a94c-4870-af23-589e6fb66989
> TF-3372 paging empty trash spam

- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/model/move_to_mailbox_request.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/usecases/delete_multiple_emails_permanently_interactor.dart
- lib/features/email/domain/usecases/mark_as_email_read_interactor.dart
- lib/features/email/domain/usecases/move_to_mailbox_interactor.dart
- lib/features/mailbox/data/network/mailbox_isolate_worker.dart
- lib/features/thread/data/network/thread_isolate_worker.dart
- lib/features/thread/domain/usecases/mark_as_multiple_email_read_interactor.dart
- lib/features/thread/domain/usecases/mark_as_star_multiple_email_interactor.dart
- lib/features/thread/domain/usecases/move_multiple_email_to_mailbox_interactor.dart
- lib/main/error/capability_validator.dart
- model/lib/extensions/list_id_extension.dart
- model/lib/model.dart
- test/features/email/data/network/email_api_test.dart
- test/fixtures/session_fixtures.dart
> TF-3370 [MU] Fix very large email set fails

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/widgets/html_attachment_previewer.dart
[html-previewer.webm](https://github.com/user-attachments/assets/1d2409fb-79d1-4238-bd78-be5ae3c39eae)
> Hotfix Html attachment previewer on mobile

- lib/features/base/mixin/contact_support_mixin.dart
- lib/features/home/data/datasource_impl/session_datasource_impl.dart
- lib/features/home/data/extensions/session_hive_obj_extension.dart
- lib/features/home/data/network/session_api.dart
- lib/features/home/domain/converter/capability_properties_converter.dart
- lib/features/home/domain/extensions/session_extensions.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/navigation_bar/navigation_bar_widget.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_controller.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/menu/widgets/account_menu_item_tile_builder.dart
- lib/features/manage_account/presentation/model/account_menu_item.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/routes/route_utils.dart
- model/lib/support/contact_support_capability.dart
- test/features/session/session_extensions_test.dart
- Cherry pick PR #https://github.com/linagora/tmail-flutter/pull/3452 to `maintenance v0.14.2`
> Cherry pick contact support setting option to `maintenance v0.14.2`

- lib/features/base/base_mailbox_controller.dart
- lib/features/mailbox/presentation/model/mailbox_tree_builder.dart
- test/features/mailbox/presentation/model/mailbox_tree_builder_test.dart
- test/features/rule_filter_creator/presentation/rule_filter_creator_controller_test.dart
#3466 
https://github.com/user-attachments/assets/eabae73a-ab41-4049-8a51-f58b49121179
> TF-3466 Fix refresh folds folder

- integration_test/scenarios/search_email_with_sort_order_scenario.dart
- lib/features/mailbox_dashboard/presentation/model/search/email_sort_order_type.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
#3461
- Web
https://github.com/user-attachments/assets/4aa49f82-36da-4c59-8162-b8d9d0d1c7ee
- Mobile Integration test:
[demo-integration-test.webm](https://github.com/user-attachments/assets/b273bfc5-a34a-4f51-b6dd-97ab38ede49f)
> TF-3461 Sort by message size

- lib/features/email/presentation/styles/attachment/attachment_item_widget_style.dart
- lib/features/email/presentation/styles/email_attachments_styles.dart
- lib/features/email/presentation/utils/email_utils.dart
- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/email_attachments_widget.dart
- test/features/email/presentation/get_attachment_displayed_test.dart
- #3472 
https://github.com/user-attachments/assets/270b0aa9-23e7-48a1-8f6e-a37504cfdb6e
> TF-3472 Prevent attachments from wrapping 2nd line

- core/lib/utils/string_convert.dart
- core/test/utils/string_convert_test.dart
- lib/features/composer/presentation/extensions/auto_create_tag_for_recipients_extension.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- Convert `EmailAddress` to MailAddress support subaddressing incorrect
https://github.com/user-attachments/assets/f14d4071-ac5c-4b64-9514-47796ee2cb83
> TF-3539 Fix auto complete does not show name, no auto create tag when paste list email and unfocus

- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- #3511 
[android-email-view-system-back.webm](https://github.com/user-attachments/assets/9c94110d-0150-4992-9db7-95258ed4c4d7)
> TF-3511 Fix Android email view system back action

- lib/features/base/widget/circle_loading_widget.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/styles/composer_style.dart
- lib/features/composer/presentation/widgets/insert_image_loading_bar_widget.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identity_loading_widget.dart
- #3502 
https://github.com/user-attachments/assets/0e3ebf0f-866d-40a0-b494-3476d65c4dc4
[image-linear-mobile.webm](https://github.com/user-attachments/assets/5d6fe3c5-20d9-4d5f-b63e-a98ef54e1c65)
> TF-3502 Fix composer image loading icon

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- #3533 
- https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
> TF-3533 Migrate gradle plugins

- pubspec.lock
#3501 
- Need merge: https://github.com/linagora/html-editor-enhanced/pull/50
https://github.com/user-attachments/assets/fa13da43-262d-4cba-bfa9-b0080f18ce92
> TF-3501 Fix inlined answer must be shown on base level

- contact/pubspec.lock
- core/lib/presentation/extensions/color_extension.dart
- email_recovery/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/data/repository/calendar_event_repository_impl.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/model/blob_calendar_event.dart
- lib/features/email/presentation/styles/event_time_information_widget_styles.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_time_information_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- server_settings/pubspec.lock
- test/features/email/data/network/calendar_event_api_test.dart
- test/features/email/presentation/widgets/calendar_event/event_time_information_widget_test.dart
- #3578 
- Need merged: https://github.com/linagora/jmap-dart-client/pull/107
https://github.com/user-attachments/assets/b175be09-cce1-4fb7-a704-56b3e8c77295
> TF-3578 Calendar event show free busy status

- core/lib/presentation/utils/html_transformer/sanitize_autolink_filter.dart
- core/lib/presentation/utils/html_transformer/text/persist_preformatted_text_transformer.dart
- core/lib/utils/file_utils.dart
- core/lib/utils/html/html_template.dart
- core/lib/utils/html/html_utils.dart
- core/lib/utils/string_convert.dart
- core/test/sanitize_autolink_filter_test.dart
- core/test/utils/file_utils_test.dart
- core/test/utils/string_convert_test.dart
- lib/features/base/upgradeable/upgrade_hive_database_steps_v12.dart
- lib/features/base/upgradeable/upgrade_hive_database_steps_v14.dart
- lib/features/caching/caching_manager.dart
- lib/features/caching/config/cache_version.dart
- lib/features/caching/config/hive_cache_config.dart
- lib/features/push_notification/presentation/extensions/type_name_extension.dart
- lib/features/thread/presentation/thread_controller.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
Email content in `text/plain` format does not automatically wrap when displayed on mobile
From fixing the display of `markdown` table content, we always use the `pre` tag to wrap the email content, resulting in the email content not automatically wrapping.
We will check if the email content is a `markdown` table or `ASCII art` table. If so, we will use `style` to display as markdown, otherwise we will leave the text as is.
- Mobile:
- Web:
Shared
> [HOT-FIX] Email content in `text/plain` format does not automatically wrap when displayed on mobile

- lib/features/composer/presentation/view/web/desktop_responsive_container_view.dart
#3640 
https://github.com/user-attachments/assets/88c7ba9f-46f7-41fd-942b-470551407d44
> TF-3640 Increase composer size when there is only one composer

- lib/features/composer/presentation/extensions/email_action_type_extension.dart
- lib/main/routes/route_utils.dart
- test/main/routes/route_utils_test.dart
- #3651 
https://github.com/user-attachments/assets/8258e2f1-6a31-4bc9-9de9-a9193fbe3b16
> TF-3651 Support mailto url from OpenPaas

- contact/pubspec.lock
- contact/pubspec.yaml
- core/pubspec.lock
- core/pubspec.yaml
- email_recovery/pubspec.lock
- email_recovery/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- lib/features/thread_detail/data/data_source/thread_detail_data_source.dart
- lib/features/thread_detail/data/data_source/thread_detail_remote_data_source_impl.dart
- lib/features/thread_detail/data/network/thread_detail_api.dart
- lib/features/thread_detail/data/repository/thread_detail_repository_impl.dart
- lib/features/thread_detail/domain/exceptions/empty_thread_detail_exception.dart
- lib/features/thread_detail/domain/repository/thread_detail_repository.dart
- lib/features/thread_detail/domain/state/get_thread_by_id_state.dart
- lib/features/thread_detail/domain/usecases/get_thread_by_id_interactor.dart
- lib/features/thread_detail/presentation/extension/handle_get_email_ids_by_thread_id_success.dart
- lib/features/thread_detail/presentation/model/thread_detail_arguments.dart
- lib/features/thread_detail/presentation/thread_detail_controller.dart
- model/pubspec.lock
- model/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
- server_settings/pubspec.lock
- server_settings/pubspec.yaml
- #3639 
- https://github.com/linagora/jmap-dart-client/pull/109
> [Thread Detail] [Part 1] TF-3639 data layer and controller

- core/lib/core.dart
- core/lib/presentation/views/loading/cupertino_loading_widget.dart
- core/lib/presentation/views/semantics/checkbox_semantics.dart
- core/lib/presentation/views/semantics/icon_semantics.dart
- core/lib/presentation/views/semantics/text_field_semantics.dart
- core/lib/presentation/views/text/text_field_builder.dart
- lib/features/identity_creator/presentation/widgets/identity_input_field_builder.dart
- lib/features/identity_creator/presentation/widgets/set_default_identity_checkbox_builder.dart
- lib/features/thread/presentation/widgets/thread_view_loading_bar_widget.dart
#3678
- `Set as default identity` checkbox and `Identity input field`
https://github.com/user-attachments/assets/e6695bed-0910-44ae-b157-f744f91b6512
- `Loading icon` in mail list
https://github.com/user-attachments/assets/0e5874d0-5811-4231-aea4-609a9e3b3247
> TF-3678 Enable semantic for some widget to support automation on web

- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
#3701 
https://github.com/user-attachments/assets/f6feee3f-6ceb-452c-8874-702c5a36fa57
> TF-3701 Fix translation issue on favorites toggle

- lib/features/search/email/presentation/search_email_view.dart
- lib/features/thread/presentation/thread_controller.dart
https://github.com/linagora/tmail-flutter/issues/3729#issuecomment-2893538760
- Android:
[android.webm](https://github.com/user-attachments/assets/a2bf1afb-db0a-4d95-8e69-d8d9abc6f4e1)
- iOS:
https://github.com/user-attachments/assets/aaaa8f03-c501-4aa4-b1a4-1a7c20bcefff
- Web:
https://github.com/user-attachments/assets/b78800ac-85d6-4ddc-bf42-2d52f7a9271a
> [HOT-FIX] Cannot back search list when open email from search in mobile

- lib/features/identity_creator/presentation/identity_creator_controller.dart
- lib/features/identity_creator/presentation/widgets/identity_input_decoration_builder.dart
Missed case `Can not get inputted value Name field in Identity dialog` in issue: https://github.com/linagora/tmail-flutter/issues/3678
https://github.com/user-attachments/assets/1423c690-2f3d-4403-abe8-10a6f1a8386c
> [Automation][Web] Allow accessibility value of name input identity creator view

- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/views/quick_search/type_ahead_field_quick_search.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- lib/features/search/mailbox/presentation/search_mailbox_view.dart
- lib/features/search/mailbox/presentation/utils/search_mailbox_utils.dart
#3761
https://github.com/user-attachments/assets/d36f2380-699d-453f-97b1-e310382dc0c6
> TF-3761 Update search bar for search mailbox in left menu

- lib/features/composer/presentation/extensions/setup_email_request_read_receipt_flag_extension.dart
#3795 
- Capability setting server is supported:
https://github.com/user-attachments/assets/4796b2e4-2162-4b03-800c-d2d88b20de40
- Capability setting server is not supported:
https://github.com/user-attachments/assets/02d80e59-e482-4278-a2df-8ecef6370fe2
> TF-3795 Fix cannot send emails with stalwart

- lib/features/email/presentation/bindings/email_bindings.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/styles/email_attachments_styles.dart
- lib/features/email/presentation/utils/email_action_reactor/email_action_reactor.dart
- lib/features/email/presentation/widgets/calendar_event/event_body_content_widget.dart
- lib/features/email/presentation/widgets/email_subject_widget.dart
- lib/features/email/presentation/widgets/mail_unsubscribed_banner.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread_detail/presentation/action/thread_detail_ui_action.dart
- lib/features/thread_detail/presentation/extension/get_thread_detail_email_mailbox_contains.dart
- lib/features/thread_detail/presentation/extension/get_thread_detail_loading_view.dart
- lib/features/thread_detail/presentation/extension/get_thread_details_email_views.dart
- lib/features/thread_detail/presentation/extension/handle_email_moved_action.dart
- lib/features/thread_detail/presentation/extension/handle_get_emails_by_ids_success.dart
- lib/features/thread_detail/presentation/extension/thread_detail_on_email_action_click.dart
- lib/features/thread_detail/presentation/thread_detail_controller.dart
- lib/features/thread_detail/presentation/thread_detail_view.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
- #3775 
https://github.com/user-attachments/assets/1c47811a-da56-4d8c-88fd-9e41f8c18d1e
https://github.com/user-attachments/assets/3e93c46b-9f66-443c-9498-b4ba79536498
https://github.com/user-attachments/assets/8ad28ec4-c826-4a78-9f06-59f4f1266442
> TF-3775 Thread Detail Fix remaining bugs

- lib/features/composer/data/repository/composer_repository_impl.dart
- model/lib/extensions/email_body_part_extension.dart
- model/lib/extensions/set_email_body_part_extension.dart
- model/lib/model.dart
#3792
https://github.com/user-attachments/assets/28f49716-98c0-48b3-8fc9-06413bca1e3b
> TF-3792 Fix cannot reply to email on Stalwart server

- lib/features/quotas/presentation/quotas_view.dart
#3822
https://github.com/user-attachments/assets/03a5699d-2c24-42e6-8e2e-4a9ac67d1320
> TF-3822 Fix quota view misaligned

- docs/adr/0066-robust-oidc-guessing.md
- lib/features/login/domain/model/oidc_guessing_origin.dart
- lib/features/login/domain/state/dns_lookup_to_get_jmap_url_state.dart
- lib/features/login/domain/state/try_guessing_web_finger_state.dart
- lib/features/login/domain/usecases/dns_lookup_to_get_jmap_url_interactor.dart
- lib/features/login/domain/usecases/try_guessing_web_finger_interactor.dart
- lib/features/login/presentation/extensions/generate_oidc_guessing_urls.dart
- lib/features/login/presentation/login_bindings.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/widgets/login_message_widget.dart
- test/features/login/domain/model/oidc_guessing_origin_test.dart
- test/features/login/domain/usecases/try_guessing_web_finger_interactor_test.dart
- test/features/login/presentation/login_controller_test.dart
- #3826 
[no-internet.webm](https://github.com/user-attachments/assets/aea840dc-87bd-466c-80ed-3e8008a52c86)
https://github.com/user-attachments/assets/857a714c-64a3-486d-bbb5-15ba9b00dbe0
[guess-webfinger-fail.webm](https://github.com/user-attachments/assets/935d1f5d-e9b9-40e3-a5d7-ec645216d4dd)
> TF-3826 DNS look up error handling

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_body_content_widget.dart
- lib/features/thread_detail/presentation/extension/get_thread_details_email_views.dart
- #3845 
https://github.com/user-attachments/assets/efc39e61-0657-4da8-a4d7-940a5bdd9a2d
> TF-3845 Thread Detail Fix blue bar detail scroll

- lib/features/email/presentation/utils/email_action_reactor/email_action_reactor.dart
- #3844 
https://github.com/user-attachments/assets/79c3d8cf-2b26-425c-8593-cd13189cc6f5
> TF-3844 Thread Detail Fix context menu style

- core/lib/presentation/extensions/color_extension.dart
- core/lib/presentation/views/dialog/confirm_dialog_button.dart
- core/lib/presentation/views/dialog/confirmation_dialog_builder.dart
- lib/features/base/mixin/message_dialog_action_mixin.dart
- lib/features/base/widget/email_address_with_copy_widget.dart
- lib/features/base/widget/user_avatar_builder.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/widgets/email_address_bottom_sheet_builder.dart
- lib/features/email/presentation/widgets/email_address_detail_widget.dart
- lib/features/email/presentation/widgets/email_address_dialog_builder.dart
- lib/features/mailbox/presentation/widgets/mailbox_app_bar.dart
- lib/features/mailbox_dashboard/presentation/widgets/profile_setting/profile_label_widget.dart
https://www.notion.so/linagora/New-style-modal-profile-UI-22262718bad180b188e7e1aaf8c2d92b?source=copy_link
- Web:
https://github.com/user-attachments/assets/114fc445-6554-4cdc-b63e-5418bbc13ab0
- Mobile:
> Apply new style modal profile UI

- lib/features/composer/presentation/extensions/create_email_request_extension.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/manage_account/presentation/language_and_region/language_and_region_controller.dart
- lib/main.dart
- lib/main/localizations/localization_service.dart
- https://github.com/linagora/tmail-flutter/pull/3887
> Cherry pick `TF-3885 Fix language defaults` to master

- core/lib/domain/extensions/datetime_extension.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/utils/email_action_reactor/email_action_reactor.dart
- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
- lib/features/email/presentation/widgets/received_time_builder.dart
- lib/features/manage_account/presentation/model/setting_option_type.dart
- lib/features/thread/data/extensions/email_cache_extension.dart
- lib/features/thread/data/extensions/email_extension.dart
- lib/features/thread/data/model/email_cache.dart
- lib/features/thread/domain/constants/thread_constants.dart
- lib/features/thread_detail/data/data_source/thread_detail_local_data_source_impl.dart
- lib/features/thread_detail/presentation/extension/get_thread_details_email_views.dart
- lib/features/thread_detail/presentation/extension/handle_refresh_thread_detail_action.dart
- lib/features/thread_detail/presentation/extension/initialize_thread_detail_manager.dart
- lib/features/thread_detail/presentation/extension/thread_detail_next_previous_actions.dart
- lib/features/thread_detail/presentation/extension/thread_detail_on_email_action_click.dart
- lib/features/thread_detail/presentation/thread_detail_controller.dart
- lib/features/thread_detail/presentation/thread_detail_manager.dart
- lib/features/thread_detail/presentation/thread_detail_view.dart
- lib/features/thread_detail/presentation/widgets/thread_detail_app_bar.dart
- lib/main/localizations/app_localizations.dart
- model/lib/email/presentation_email.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- test/features/thread_detail/presentation/extension/handle_refresh_thread_detail_action_test.dart
- #3876 
- #3878 
- #3881 
- #3882  
https://github.com/user-attachments/assets/cb73179b-88f4-4558-afc7-9fca4ad464e4
https://github.com/user-attachments/assets/e199b8d5-7a68-441d-b841-edb3fb5f9d56
https://github.com/user-attachments/assets/c7b212c1-b8bc-44b3-92b4-65fe211106b3
https://github.com/user-attachments/assets/483999e4-fb82-4ac2-b332-c8bbb26df78d
> TF-3881 Thread Detail New UI

- lib/features/thread/presentation/styles/item_email_tile_styles.dart
- lib/features/thread/presentation/widgets/desktop_list_email_action_hover_widget.dart
- lib/features/thread/presentation/widgets/web_tablet_body_email_item_widget.dart
#3914 
https://github.com/user-attachments/assets/a4aefb3f-86df-4e17-88b7-32e1be92f112
> TF-3914 Apply new style for actions on hover in list

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
https://github.com/user-attachments/assets/bc22526d-1ae4-427d-928c-fe210b7875a6
https://github.com/linagora/tmail-flutter/pull/3322
https://github.com/user-attachments/assets/8432e63c-5528-4ec7-845e-e5fa73c1bfeb
> [HOT] Fix green background signature in profile setting

- core/lib/presentation/utils/html_transformer/dom/hide_draft_signature_transformer.dart
- core/lib/presentation/utils/html_transformer/dom/signature_transformers.dart
- core/lib/utils/html/html_template.dart
- core/lib/utils/html/html_utils.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/extensions/sanitize_signature_in_email_content_extension.dart
- lib/features/composer/presentation/styles/subject_composer_widget_style.dart
- lib/features/composer/presentation/styles/web/bottom_bar_composer_widget_style.dart
- lib/features/composer/presentation/view/web/desktop_responsive_container_view.dart
- lib/features/composer/presentation/widgets/subject_composer_widget.dart
- lib/features/composer/presentation/widgets/web/bottom_bar_composer_widget.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- lib/features/email/data/local/html_analyzer.dart
#3944 
https://github.com/user-attachments/assets/67b7ae1e-d37a-4c20-b858-717cdfd4825c
> TF-3944 Apply new style for composer

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
https://github.com/linagora/tmail-flutter/issues/3975#issuecomment-3218694424
https://github.com/user-attachments/assets/677da9ec-00db-40d3-90f8-0d55a8973d56
https://github.com/user-attachments/assets/4c332ae7-7ee2-40b4-9ec2-8a5d1b1bc7c1
> HOTFIX Composer cursor blink
