linagora/tmail-flutter

- ios/Flutter/AppFrameworkInfo.plist
- ios/Runner.xcodeproj/project.pbxproj
Currently, the iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99.
> Change the minimum IOS Deploying Target to 9.0

- lib/features/login/presentation/login_view.dart
- lib/l10n/intl_en.arb
- lib/l10n/intl_fr.arb
- lib/l10n/intl_messages.arb
- lib/l10n/intl_ru.arb
- lib/l10n/intl_vi.arb
- lib/main/localizations/app_localizations.dart
That has been in some feedbacks that it was confusing.
I also saw that the text input type for the url in the login form was emailAddress, which is wrong (I think), so I changed it to url type.
> Change label "username" to "Email" in login form

- lib/features/mailbox/data/datasource_impl/mailbox_cache_datasource_impl.dart
- lib/features/mailbox/data/extensions/mailbox_extension.dart
Doing a sort using SortOrder on the list of mailboxes before display.
INBOX has always the lowest SortOrder, followed gradually by other system mailboxes and then finally the other folders. We should use the SortOrder in the jmap mailbox object, it's for this kind of purpose I think. 
I could reproduce the issue on preprod with user `firstname1.surname1`.
Master branch:
This fix:
> TF-220 Sort list of mailboxes by SortOrder before display

- android/app/build.gradle
- android/build.gradle
- bitrise.yml
the same issue: https://github.com/bitrise-steplib/bitrise-step-flutter-test/issues/34
Add the workaround solution to script before `flutter test`: 
```
dart pub global activate junitreport
```
> Workaround solution for junitreport

- Jenkinsfile
As I understood after talking with @chibenwa we should:
* build on master branch and tags
* not build on release branch
If you want to have a web image build proper to a release version you should push a tag with the version number (like `0.3.0`) then it will build you the image `linagora/tmail-web:0.3.0`. The release branch will NOT build anything.
> Should not build web image on release branch

- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/home/presentation/home_bindings.dart
- lib/features/home/presentation/home_view.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_controller.dart
- lib/features/session/presentation/session_page_bindings.dart
- lib/features/session/presentation/session_view.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/main/bindings/credential/credential_bindings.dart
- lib/main/bindings/main_bindings.dart
- lib/main/bindings/session/session_bindings.dart
- lib/main/pages/app_pages.dart
https://user-images.githubusercontent.com/6462404/158948193-0ff2f61a-6ce9-4787-ad57-1bf1708e7a23.mov
When user click on `reload` button in browser, a widget will be reloaded, and we catch the event on `onReady` of controller to set up all the things:
- url interceptor
- authentication interceptor
- get new session
> Reload web #362

- docs/adr/0003-reduce-main-file-size-on-web-browser.md
- lib/main/pages/app_pages.dart
- lib/main/pages/deferred_widget.dart
- Issues:  
- The file size `main.dart.js` generated when building the web is too large.
- This issue is discussed [here](https://github.com/flutter/flutter/issues/46589)
**Current `main.dart.js` file size : 3.8MB** 
- Cause: Simultaneous download of all pages 
- Solve: Use [Lazily loading](https://dart.dev/guides/language/language-tour#lazily-loading-a-library) which could split your code in multiple JavaScript files
- Result: 
**After implement Lazily loading. File `main.dart.js` has size : 3.4MB**
> TF-358 Reduce `main.dart.js` file size at web browser startup

- core/lib/presentation/utils/html_transformer/dom/link_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/meta_transformers.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
@hoangdat  Please review it 
- Issues: The subtags in the `a`  tag are gone.
- Resolve: Keep the subtags of the `a` tag, and add the `tooltip` display tag
https://user-images.githubusercontent.com/80730648/163098529-7d608af4-cb1d-4d32-beef-823f0895e483.mov
> Fix show view flyover for links in Email Detail

- ios/Runner/Info.plist
-  Set `CADisableMinimumFrameDurationOnPhone` to true for support high frame rate for newer devices (>= iPhone 13 Pro)  [https://github.com/flutter/flutter/issues/94508](https://github.com/flutter/flutter/issues/94508)
> TF-501 Set TeamMail app to be default mail app in iOS

- lib/features/mailbox/data/network/mailbox_isolate_worker.dart
- pubspec.yaml
- My [worker_manager](https://github.com/Renesanse/worker_manager/pull/58) improvement PR has been merged
- We can use the latest version of [worker_manager](https://pub.dev/packages/worker_manager) `4.4.0 ` on [pub.dev](https://pub.dev) to use.
> Update worker_manager library official for isolate

- core/lib/presentation/views/responsive/responsive_widget.dart
<table>
<tr>
<td><img width="353" alt="Screen Shot 2022-07-08 at 15 46 58" src="https://user-images.githubusercontent.com/80730648/177954961-c99b4a56-94a5-4f35-a40f-0010720ae0ba.png"></td>
<td><img width="353" alt="Screen Shot 2022-07-08 at 15 46 53" src="https://user-images.githubusercontent.com/80730648/177954987-7d3bfa46-f244-4cd9-a876-e8670e94f908.png"></td>
</tr>
</table>
<table>
<tr>
<td><img width="353" alt="Screen Shot 2022-07-08 at 15 46 58" src="https://user-images.githubusercontent.com/80730648/177955689-a223b527-36b7-43b9-a00d-34d9e96916ae.png"></td>
<td><img width="353" alt="Screen Shot 2022-07-08 at 15 46 53" src="https://user-images.githubusercontent.com/80730648/177955781-b781f3f3-0a4a-4ea9-831a-b5e68839a68f.png"></td>
</tr>
</table>
> [HOT-FIX] Fix wrong screen response on mobile

- lib/features/composer/presentation/composer_view_web.dart
- Sometimes select 2 times to select font family & Can not close dropdown menu when click outside of it _**=> Fixed in the latest version of the code.**_
- Update size width dropdown menu font
https://user-images.githubusercontent.com/80730648/182095675-112c2918-cd6d-465d-ab50-cdfadf0b7863.mov
> TF-752 [Web] Improve Dropdown font family dropdown menu

- lib/features/thread/presentation/widgets/email_tile_web_builder.dart
#778 
https://user-images.githubusercontent.com/6462404/182378202-c0ccda86-d47b-42dc-a0b3-ee8d718230c8.mov
> TF-778 Fix text is cut after `-` symbol in web

- docs/adr/0013-migrate-composer-editor-repository-to-linagora.md
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- pubspec.yaml
#753 
- Merge [https://github.com/linagora/html-editor-enhanced/pull/2](https://github.com/linagora/html-editor-enhanced/pull/2)
- Migrate [enough_html_editor](https://github.com/ManhNTX/enough_html_editor) library to [Linagora](https://github.com/linagora/enough_html_editor) with branch [email_supported](https://github.com/linagora/enough_html_editor/tree/email_supported) 
- Migrate [html_editor_enhanced](https://github.com/dab246/html-editor-enhanced) library to [Linagora](https://github.com/linagora/html-editor-enhanced) with branch [email_supported](https://github.com/linagora/html-editor-enhanced/tree/email_supported)
> TF-753 Migrate composer editor library to Linagora

- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/app_bar_mail_widget_builder.dart
Related issue #904
When clicking on the line with the mailbox name, it goes back to the mailbox.
The link "size" is very wide, until the "move message" button, so licking on the "white space" also redirects to mailbox, but I don't think it is a problem.
Feel free to test or suggest changes.
> TF-904 Clicking mailbox name redirects to mailbox

- android/app/build.gradle
Because of `androidx.webkit.webkit:1.5.0`
> #909 [Android ]Upgrade compileSDK 32 

- core/lib/presentation/utils/html_transformer/html_template.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- docs/adr/0010-crash-app-when-open-webview-on-android-device.md
- model/lib/email/presentation_email.dart
- #884 
- Email title has too many spaces
- [https://github.com/linagora/enough_html_editor/pull/6](https://github.com/linagora/enough_html_editor/pull/6)
- Trim email title: 
- 
https://user-images.githubusercontent.com/80730648/188869872-9f9c9ffa-7cee-4aea-993f-f02b34663784.mp4
> TF-884 [Bug] Crash when open email 

- contact/test/contact/autocomplete_tmail_contact_method_test.dart
- forward/test/forward/get_forward_method_test.dart
- forward/test/forward/set_forward_method_test.dart
- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/email/domain/usecases/download_attachment_for_web_interactor.dart
- lib/features/email/domain/usecases/download_attachments_interactor.dart
- lib/features/email/domain/usecases/export_attachment_interactor.dart
- lib/features/session/domain/state/get_session_state.dart
- lib/features/session/presentation/session_controller.dart
- lib/features/session/presentation/session_page_bindings.dart
- rule_filter/test/rule_filter/get_rule_filter_method_test.dart
- rule_filter/test/rule_filter/set_rule_filter_method_test.dart
#940 
#949 
- [https://github.com/linagora/jmap-dart-client/pull/37]( https://github.com/linagora/jmap-dart-client/pull/37)
- With domain of `Fastmail`
https://user-images.githubusercontent.com/80730648/191583055-784cd8ae-7b7e-465d-8fed-4014532d59b7.mov
- With domain of `Jmap Linagrora`
https://user-images.githubusercontent.com/80730648/191583247-4b729669-2500-4ad4-a410-a6aec26c048a.mov
> TF-940, 949 Using `apiUrl` in session to set up path for `jmap-dart-client`

- lib/features/composer/domain/exceptions/send_email_exception.dart
- lib/features/composer/domain/model/email_request.dart
- lib/features/composer/domain/usecases/send_email_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/presentation/email_controller.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/email_quick_search_item_tile_widget.dart
- lib/features/search/presentation/search_email_controller.dart
- lib/features/search/presentation/search_email_view.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- model/lib/extensions/email_extension.dart
- model/lib/extensions/mailbox_id_extension.dart
- model/lib/extensions/mailbox_name_extension.dart
- model/lib/mailbox/presentation_mailbox.dart
#942 
- [https://github.com/linagora/jmap-dart-client/pull/38](https://github.com/linagora/jmap-dart-client/pull/38)
- [https://github.com/linagora/jmap-dart-client/pull/39](https://github.com/linagora/jmap-dart-client/pull/39)
- For `jmap.linagora.com`
https://user-images.githubusercontent.com/80730648/191917891-b7144ed6-ec3c-429b-821a-118bc1308a55.mov
- For `api.fastmail.com` has mailbox with name `Outbox`
https://user-images.githubusercontent.com/80730648/191918237-9de88a60-34aa-49d2-a931-558598cb7c74.mov
- For `api.fastmail.com` has not mailbox with name `Outbox`
https://user-images.githubusercontent.com/80730648/191918403-9a2cd5af-5d87-4c4f-949e-288c54de05f7.mov
> TF-942 Auto generate missing default mailboxes in client side

- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/presentation/thread_controller.dart
- wrong condition: if `moreItems` have any item in `emailList` will be ignored to append.
https://user-images.githubusercontent.com/6462404/194032802-7ba98576-853e-45bd-aa9a-e233f4725838.mov
https://user-images.githubusercontent.com/6462404/194032821-b573138a-d002-456e-9a54-9ccb47238f16.mov
> #1045 Remove wrong conditions to append more items after loading more

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
This should free up macos runners for ios builds, and use ubuntu for android builds
> Specific runner per OS

- core/lib/presentation/utils/html_transformer/text/convert_url_string_to_html_links_transformers.dart
- core/lib/utils/linkify_html.dart
#991 
- Because there are many similar links in an email body. So `replace` string is incorrect.
- Before fixed
https://user-images.githubusercontent.com/80730648/194454282-bccebce5-5998-43b1-95fa-ecdcbd46e992.mov
- After fixed
https://user-images.githubusercontent.com/80730648/194461778-a8b122f0-a996-4d11-8ce4-411924d541d4.mov
> TF-991 Fix link problem on my JIRA notifications

- Dockerfile
- README.md
- docker-compose.yaml
- env.file
Also simplified the Dockerfile and moved `gzip` to a seperate `RUN` so the container can be restarted.
This compose file uses the `linagora/tmail-backend:memory-branch-master`image.
> Added compose file for quick local setup

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- Components using IntentFilter must set android:exported="true"
- Other required was not impacted
> Support targetSDK 31 (required from Play store)

- lib/main.dart
#1284 
- Because `dotenv.load()` has not been initialized but already used.
https://user-images.githubusercontent.com/80730648/206169099-f40fed96-800d-4dae-92c8-a6e888053b20.mov
> TF-1284 Fix some view blank when reload web

- lib/features/base/base_controller.dart
- lib/main/utils/app_utils.dart
#1356 
- Because every time the `env` file loads, the `clean` function is called.
- Use the `mergeWith` parameter in the `load` . function
> [HOT-FIX] TF-1356 Fix `Env.file` data lost after logout and login again

- lib/features/push_notification/data/datasource_impl/fcm_datasource_impl.dart
- lib/features/push_notification/domain/extensions/firebase_subscription_extension.dart
- Because `response` from `FirebaseRegistration/set` does not contain `deviceId`
- Mappings `deviceId` from `request` to use
> [HOT-FIX] Fix device id null after register new token successful

- lib/features/push_notification/presentation/config/fcm_configuration.dart
Issue: When the user login after that call `getFcmToken` and `onRefreshFcmToken` to fcm token has duplicated.
Solution:  Delete `getFcmToken` func and keep `onRefreshFcmToken`
Android: 
after solving
> Hot fix: Fix duplicate fcm token when login

- lib/features/mailbox/presentation/mailbox_controller.dart
Fix don't open Spam Mailbox when clicking to showDetail in SpamReportBanner
https://user-images.githubusercontent.com/99852347/212885686-67692cdc-88f2-4b90-9c09-8ab6d09f677f.mov
https://user-images.githubusercontent.com/99852347/212885731-43ba76ad-017a-47ff-a92a-876169120fb9.mov
> Hotfix : Fix don't open Spam Mailbox

- lib/features/email/domain/state/delete_multiple_emails_permanently_state.dart
- lib/features/email/domain/state/move_to_mailbox_state.dart
- lib/features/email/domain/usecases/delete_multiple_emails_permanently_interactor.dart
- lib/features/email/domain/usecases/move_to_mailbox_interactor.dart
- lib/features/mailbox/domain/state/create_new_mailbox_state.dart
- lib/features/mailbox/domain/state/delete_multiple_mailbox_state.dart
- lib/features/mailbox/domain/state/move_mailbox_state.dart
- lib/features/mailbox/domain/state/rename_mailbox_state.dart
- lib/features/mailbox/domain/state/search_mailbox_state.dart
- lib/features/mailbox/domain/usecases/create_new_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/delete_multiple_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/move_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/rename_mailbox_interactor.dart
- lib/features/mailbox/domain/usecases/search_mailbox_interactor.dart
- lib/features/thread/domain/state/mark_as_multiple_email_read_state.dart
- lib/features/thread/domain/state/mark_as_star_multiple_email_state.dart
- lib/features/thread/domain/state/move_multiple_email_to_mailbox_state.dart
- lib/features/thread/domain/usecases/mark_as_multiple_email_read_interactor.dart
- lib/features/thread/domain/usecases/mark_as_star_multiple_email_interactor.dart
- lib/features/thread/domain/usecases/move_multiple_email_to_mailbox_interactor.dart
https://user-images.githubusercontent.com/80730648/213106567-005e5137-2ee6-446e-a44a-2661ee16fa9b.mov
- Since the `ViewState` variable of `Mailbox Dashboard` is the `Obx` variable that received the same value in a short period of time, the `listen` function was not called.
https://user-images.githubusercontent.com/80730648/213106935-8177ea21-1847-4ef3-b2d3-2d62913e1c7f.mov
> [HOT] Fix can not refresh change list mailbox and email

- lib/features/composer/data/repository/composer_repository_impl.dart
- lib/features/composer/domain/repository/composer_repository.dart
- lib/features/composer/domain/state/upload_attachment_state.dart
- lib/features/composer/domain/usecases/upload_attachment_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/upload/data/datasource/attachment_upload_datasource.dart
- lib/features/upload/data/datasource_impl/attachment_upload_datasource_impl.dart
- lib/features/upload/data/network/file_uploader.dart
- lib/features/upload/domain/exceptions/upload_exception.dart
- lib/features/upload/domain/model/upload_attachment.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- lib/features/upload/presentation/extensions/upload_attachment_extension.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/routes/route_utils.dart
#1323 
- Because server `preprod` returned error `500 Internal Server Error`
- Works well on `prod` . server
- `Try/catch` the error and show toast error message on the screen 
- Log the error in `debug` mode
> TF-1323 Fix can not attach image on mobile and web

- web/firebase-messaging-sw.js
#1278 
- The browser always automatically shows the default notification every time it receives a message from `push notification` in the `background/terminated` state. If we don't customize it.
- Hide notification in `setBackgroundMessageHandler` method
- Not reproduced. More research is needed.
> TF-1278 Hide notification on background web browser when support FCM

- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/text_field_auto_complete_email_adress.dart
- lib/features/manage_account/presentation/mailbox_visibility/mailbox_visibility_view.dart
Fix search and auto-complete don't input the final email
Issue :
GIVEN I type the name 
AND select the email address suggestion
WHEN I launch the search and sent it as text, not an email address
THEN there is no result
Solution :
- After choosing an email address, the suggestion should be sent to the email address
Demo 
https://user-images.githubusercontent.com/99852347/218955251-1cc6eccc-7872-4f78-ab5e-9242fad0f484.mov
> Fix search and auto-complete don't input the final email

- lib/features/base/base_mailbox_controller.dart
- lib/features/destination_picker/presentation/destination_picker_controller.dart
- lib/features/destination_picker/presentation/destination_picker_view.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/manage_account/presentation/mailbox_visibility/mailbox_visibility_view.dart
Fixed cannot expand default mailbox
`Mobile`
https://user-images.githubusercontent.com/99852347/221460248-a6cf79bf-5321-4e40-a165-447febdcd002.mp4
`Web`
https://user-images.githubusercontent.com/99852347/221457630-280d0d55-a7a6-4741-9e89-899b487ef24d.mov
Support for auto scroll when expand folder on `Destination Picker` and `Mailbox visibility`
`Mobile`
https://user-images.githubusercontent.com/99852347/221498543-fc79853b-a62f-49ac-b814-28907c827a51.mp4
`Web`
https://user-images.githubusercontent.com/99852347/221498607-35c1772f-5d58-4a95-a0e3-6017c2518d34.mov
> Hot fix cannot expand default mailbox

- lib/main.dart
#1469 
- Due to default `animation` transition when navigate to page.
- `Android`
https://user-images.githubusercontent.com/80730648/223356340-f128c9e9-7699-4000-9930-a7856a01e054.mov
- `iOS`
https://user-images.githubusercontent.com/80730648/223356685-074108a0-04ee-4977-ba21-21ceb8b98ee2.mp4
> TF-1469 Fix [Reply/Responding] Reply screen is display not smoothly, it's lagging

- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/identity_creator/presentation/identity_creator_view.dart
- lib/features/manage_account/presentation/vacation/vacation_view.dart
- pubspec.lock
Issue: 
#1528 
When we use func `setFullScreenEditor ` it sets the html editor widget to a fixed height and then it cannot scroll automatically. The library already supports this so we shouldn't use func `setFullScreenEditor ` to set height during initialization.
- RESOLVE
[https://pub.dev/packages/html_editor_enhanced](url)
```
shouldEnsureVisible
Default value: false
This option parameter will scroll the editor container into view whenever the webview is focused or text is typed into the editor.
You can only use this parameter if your HtmlEditor is inside a Scrollview, otherwise it does nothing.
This is useful in cases where the page is a SingleChildScrollView or something similar with multiple widgets (eg a form). When the user is going through the different fields, it will pop the …
```
> TF1528: Auto down one line when typing

- lib/features/login/data/repository/credential_repository_impl.dart
- lib/features/login/data/utils/login_constant.dart
- lib/features/login/domain/model/login_constants.dart
- lib/features/login/presentation/login_controller.dart
#1440 
- `auth_destination_url`: Is our current page path (Here is `LoginView` with path: `https://domain.com#/login`)
- Because `auth_destination_url` already exists in `SessionStorage`. The authentication method always checks if `auth_destination_url` is present on storage. If so, you cannot continue.
https://user-images.githubusercontent.com/80730648/227429967-edc46c4a-cc61-48c3-9056-d51defb129db.mov
> TF-1440 Fix user can not sign again after click back browser button in OIDC

- lib/features/push_notification/presentation/notification/local_notification_manager.dart
- Do not assign a value to `_notificationsEnabled` when the permission is checked `_isAndroidPermissionGranted`
https://user-images.githubusercontent.com/80730648/228790101-9cc64acc-0ce0-45e9-8c8b-613509d267e7.mov
> [HOT] Fix cannot show push notification on android

- contact/pubspec.lock
- core/pubspec.lock
- core/pubspec.yaml
- docs/adr/0020-fix-tmail-ui-broken-after-create-identity-successfully-by-html-style.md
- model/pubspec.lock
- pubspec.lock
- pubspec.yaml
#1688 
- Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once.
-  This issue is still under discussion and there is no official fix from `flutter` side. See details here: https://github.com/flutter/flutter/issues/118159 or https://github.com/flutter/flutter/issues/104970
- Use `pointer_interceptor` version `0.9.1`
https://user-images.githubusercontent.com/80730648/229415507-18d0c007-3897-47fb-94d1-c58f9b09c495.mov
> TF-1688 Fix Tmail UI is broken after user create identity successfully by html style

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/manage_account/data/datasource/identity_data_source.dart
- lib/features/manage_account/data/datasource_impl/identity_data_source_impl.dart
- lib/features/manage_account/data/repository/identity_repository_impl.dart
- lib/features/manage_account/domain/repository/identity_repository.dart
- lib/features/manage_account/domain/state/transform_html_signature_state.dart
- lib/features/manage_account/domain/usecases/transform_html_signature_interactor.dart
- lib/features/manage_account/presentation/profiles/identities/identities_controller.dart
- lib/features/manage_account/presentation/profiles/identities/identity_bindings.dart
- lib/features/manage_account/presentation/profiles/identities/identity_interactors_bindings.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identities_radio_list_builder.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/signature_builder.dart
- pubspec.lock
- pubspec.yaml
#1684 
- The contents of the `a` tags are retrieved at the same time when `click` the web view on the browser.
- Transform html signature like email content
https://user-images.githubusercontent.com/80730648/229472412-e7d007ec-e740-4818-8468-de1f23ec1bd5.mov
> TF-1684 Fix user click on blank area but system redirect user to 404 not found page

- lib/features/mailbox/presentation/action/mailbox_ui_action.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/action/dashboard_action.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/spam_report_controller.dart
- lib/features/mailbox_dashboard/presentation/widgets/spam_report_banner_web_widget.dart
- lib/features/search/mailbox/presentation/search_mailbox_controller.dart
- lib/features/thread/presentation/widgets/spam_report_banner_widget.dart
#1698 
- Since the `dashBoardAction` variable does not refresh the stream, the controller cannot listen.
- Using `throttleTime` within 800ms so it is not possible to get the latest value when changing continuously in a short period of time.
https://user-images.githubusercontent.com/80730648/230828425-52983bf8-15b9-48d5-bbbd-5e015a7541b9.mov
> TF-1698 Fix system not redirect correct url when user double click many times to view email in mailbox

- lib/features/login/presentation/base_login_view.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/widgets/login_text_input_builder.dart
- pubspec.lock
- pubspec.yaml
#1434 
- https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/466
- Minimum SDK version supports `autofill`: `Android >= 26 | iOS >= 10.0`
- Configuration `autofill` on mobile: 
+ **Android**: Go to `Settings -> System -> Languages & input -> Autofill service`. 
+ **iOS**: Go to `Settings -> Password, turn on "Autofill Passwords"`.
+ See more at [here](https://api.flutter.dev/flutter/material/TextField/autofillHints.html)
- **Android: version 29**
https://user-images.githubusercontent.com/80730648/221745083-dc9808e7-e73a-45cb-97dd-e66090905ee8.mov
> TF-1434 Implement `autofillHints` for login view

- lib/features/composer/presentation/composer_controller.dart
- model/lib/extensions/list_email_address_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- Issue: #1759 
- Resolved:
`
GIVEN I am the sender
AND the only recipient
WHEN I click on reply
THEN the 'to' field is fielded with my user address
`
https://user-images.githubusercontent.com/99852347/231968492-75465cc2-5f26-4ddc-a321-e7f59529c4cf.mov
`
GIVEN I am the sender
AND there are other recipients
WHEN I click on reply
THEN the 'to' field is fielded with my user address
`
https://user-images.githubusercontent.com/99852347/232328091-6c912ca0-40b2-4d4c-935a-9c60cce31d8f.mov
`
WHEN I am the only recipient
THEN Reply to all is not shown
`
https://user-images.githubusercontent.com/99852347/231968632-3e9d8017-9576-4aea-9158-9870a7702e5d.mov
`
GIVEN I am the sender
AND there are other recipients
WHEN I click on reply to all
THEN the 'to' field is populated with all email addresses, …
> TF-1759: Check when replying and all replies will include me in the recipient

- .github/workflows/pr-deployments.yaml
- web/index.html
Every time there's an opened PR, this workflow will create a review deployment at `https://linagora.github.io/tmail-flutter/<PR number>`. This should use the credentials in preprod to login.
We are utilizing Github Pages to accomplish this. 
Only changes in `*.dart` files can trigger this workflow.
After the PR is deployed, a bot will comment on the PR with the deployment URL.
> Added workflow to create a deployment on PR

- core/lib/presentation/extensions/string_extension.dart
- docs/adr/0020-fix-tmail-ui-broken-after-create-identity-successfully-by-html-style.md
- docs/adr/0023-fix-system-not-display-signature-in-email-which-has-been-sent.md
- docs/adr/0024-fix-logic-of-replacing-dot-in-long-email-address.md
- lib/features/composer/presentation/composer_view.dart
- lib/features/mailbox/presentation/widgets/mailbox_folder_tile_builder.dart
- lib/features/mailbox/presentation/widgets/user_information_widget_builder.dart
- lib/features/manage_account/presentation/profiles/identities/widgets/identity_list_tile_builder.dart
- lib/features/search/mailbox/presentation/widgets/mailbox_searched_item_builder.dart
- lib/features/thread/presentation/mixin/base_email_item_tile.dart
- pubspec.lock
- pubspec.yaml
#1778 , #1779 
- `#1778`: Due to a syntax error in javascript. In `string` contains the characters `'` and `"`
- `#1779`:  When we use the `overflow=TextOverflow.ellipsis` property for the `Text` widget for long texts, it will result in incorrect string breaks. Since string contains some characters that are supposed to be word breaks in the string. The characters ` ` and `-`
- Need merged https://github.com/linagora/enough_html_editor/pull/20
https://user-images.githubusercontent.com/80730648/233637320-83e20587-ec2c-4104-9408-3dfaa75d81ec.mov
> TF-1778,1779 System not display signature in email after sent on mobile

- docs/adr/0025-fix-can-not-select-suggestion-email-by-mouse-clicking-on-web.md
- lib/features/composer/presentation/widgets/email_address_input_builder.dart
- lib/main/utils/app_constants.dart
- pubspec.lock
- pubspec.yaml
#1753 
Because the thing that the overlay is attached to is a `TextField`, so in order to keep from unfocused the text field when tapping outside of it, you need to tell the overlay widget that it's part of the TextField for purposes of the `Tap outside` behavior
- Need merged: https://github.com/dab246/super_tag_editor/pull/19
https://user-images.githubusercontent.com/80730648/233897128-5e3277d7-ce6b-429c-a6f9-c042dc04449b.mov
> TF-1753 Fix [EmailSuggestion] Email at cc is removed once user select email at bcc suggestion list

- core/lib/presentation/utils/html_transformer/html_template.dart
- docs/adr/0026-fix-horizontal-scroll-bar-in-email-detail-view.md
- Issue: #1743 
- Root cause: 
The horizontal scrollbar appears when the content inside the body element is wider than the width of the viewport. By default, the overflow property is set to "visible", which means that the content can overflow the element's boundaries.
- Resolved:
`Mac OS`
https://user-images.githubusercontent.com/99852347/234059455-a4a71800-2423-4ab3-8928-03dc8cfe988b.mov
`Ubuntu (Firefox, chromium)`
https://user-images.githubusercontent.com/99852347/234156703-8c3b23b6-17a8-4ed9-bd07-55424047e6f5.mov
> TF-1743: Hide Hide Horizontal scroll bar in Email detail view

- lib/features/composer/presentation/composer_view_web.dart
#1806 
- Due the `onChangeSelection` function is not called every time the editor changes the style. `onChangeSelection` is called only when `ToolbarWidgetState != null`
https://user-images.githubusercontent.com/80730648/236453232-c7679c46-771c-401b-a48a-6d3ef1a1f50a.mov
> TF-1806 Fix impossible to disable used fonts in email composer

- server/nginx.conf
resolved https://github.com/linagora/tmail-flutter/issues/1507
Upon new release, NGINX would return 200 OK with new static files. 
Otherwise, NGINX would return 304 Not Modified with an empty response, and the browser continues to reuse cached static files.
rf: https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests#cache_update
> Force browsers to re-validate cache before reuse

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- We have compiled the class with Java 17(major version 17) and we are trying to run class file under lower java version (version 16 or below)
- Upgrade gradle version
> [HOT-FIX] Upgrade gradle version to support class file major version 61 in Java (Java 17)

- lib/features/caching/clients/detailed_email_hive_cache_client.dart
- lib/features/caching/config/hive_cache_client.dart
- lib/features/caching/utils/caching_constants.dart
- lib/features/email/data/datasource/email_datasource.dart
- lib/features/email/data/datasource_impl/email_datasource_impl.dart
- lib/features/email/data/datasource_impl/email_hive_cache_datasource_impl.dart
- lib/features/email/data/repository/email_repository_impl.dart
- lib/features/email/domain/extensions/detailed_email_extension.dart
- lib/features/email/domain/repository/email_repository.dart
- lib/features/email/domain/usecases/get_email_content_interactor.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/offline_mode/manager/detailed_email_cache_manager.dart
- lib/features/offline_mode/manager/opened_email_cache_manager.dart
- lib/features/thread/data/local/email_cache_manager.dart
- lib/features/thread/domain/usecases/get_email_by_id_interactor.dart
- lib/features/thread/presentation/thread_bindings.dart
- Issue: #1869 
- Resolved:
**- OFFLINE MODE** 
1.  Received new noti and save to local DB
https://github.com/linagora/tmail-flutter/assets/99852347/d1f2434d-cef7-46c2-9718-5796a0ee42af
2. Check local DB has been save
https://github.com/linagora/tmail-flutter/assets/99852347/1fe45d4b-ffcb-451b-8aca-8c8702f44c81
3. Open noti and double check for duplicate email
https://github.com/linagora/tmail-flutter/assets/99852347/7788e2be-c115-4620-90ab-5d3feddac2ad
4. When reconnecting network and opening email again 
In this case: Only open email in folder `new_email` has been saved when received noti. Not save to `opened_email`
https://github.com/linagora/tmail-flutter/assets/99852347/36d2b775-7826-446a-b7ab-1277e23cf706
**- ONLINE MODE** 
1. Received new noti and save to local DB, Check local DB …
> TF-1869: Open email cache from notification

- docs/adr/0029-fix-show-widget-of-draggable-when-click-right-on-email.md
- lib/features/thread/presentation/thread_view.dart
- Issue: #1862 
- The childWhenDragging widget will still be draggable, including the ability to trigger the right-click event. This is because the childWhenDragging widget is a part of the draggable behavior and inherits the drag-related properties and behaviors from the Draggable widget.The Draggable widget allows you to customize the appearance and behavior of the dragged item during the dragging process by providing the feedback and childWhenDragging properties. The feedback widget is used to display a visual representation of the dragged item, while the childWhenDragging widget is used to replace the original item when it is being dragged.
- Resolved :
Wrap it with a GestureDetector and handle the right-click event as mentioned in the previous answer. This way, you can have separate …
> TF-1862: Fix show  widget of Draggable when click right on email

- lib/features/thread/presentation/thread_view.dart
- Issue : 
```
GIVEN I am in email list view
WHEN I right click on an item multiple times
THEN the right clicks menu open
AND the move dialog is shown
WHEN I left click to close menu
THEN the move dialog is still here
```
https://github.com/linagora/tmail-flutter/assets/99852347/56f25735-a015-4bb3-973f-b9b3b5541fc7
- Resolved:
https://github.com/linagora/tmail-flutter/assets/99852347/813de239-83d4-4654-810a-855d2e9d1467
> TF-1862: Fix show widget of draggable when click right on email part ii

- lib/features/caching/caching_manager.dart
- lib/features/mailbox/data/datasource_impl/state_datasource_impl.dart
- lib/features/mailbox/data/model/state_type.dart
- lib/features/thread/presentation/thread_controller.dart
#1913 
- Because `EmailState` has not been cleared in cache
```dart
_stateCacheClient.deleteItem(StateType.email.value);
```
- Clear email cache with `TupleKey` 
```dart
_stateCacheClient.deleteItem(StateType.email.getTupleKeyStored(accountId, username));
```
> TF-1913 Fix thread view keeps reloading

- lib/features/thread/presentation/model/loading_more_status.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
#1931 
- `isLoadMore` is not reset to `false` when network connection is re-enabled
- Create `LoadingMoreStatus` to manage loading status more
```dart
enum LoadingMoreStatus {
idle,
running,
completed;
}
```
- Reset value of `loadingMoreStatus = idle` when it process is a error
https://github.com/linagora/tmail-flutter/assets/80730648/80614212-01d2-421a-9a01-dfb4565190aa
> TF-1931 Fix user cannot do infinity scroll when he turn off network and reconnect again

- lib/features/email/domain/usecases/download_attachments_interactor.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
#1974 
- I have hard-coded for `RefreshToken` as null. Before calling `appAuth.token()` and getting the same error as store.
- After that investigation, we concluded that `refreshToken` was empty leading to the application crash.  Details in the native library [openid](https://github.com/openid/AppAuth-Android/blob/d73ced59d07a4b93d9039ab3d193942fc7197959/library/java/net/openid/appauth/TokenRequest.java#L399)
- It only happens on Android devices
- Check for non-empty `refreshToken` before being used.
- Same issue raised on `Flutter AppAuth` library [Issues#396](https://github.com/MaikuB/flutter_appauth/issues/396)
> TF-1974 RefreshToken with OIDC on `jmap.linagora.com/oidc`

- core/lib/presentation/utils/html_transformer/text/sanitize_html_transformers.dart
- core/lib/utils/app_logger.dart
- lib/features/composer/presentation/widgets/toolbar_rich_text_builder.dart
- lib/features/email/data/local/html_analyzer.dart
- #1912 
- The video reproduces the error 
https://github.com/linagora/tmail-flutter/assets/80730648/bfa9daa7-a4e7-4f92-8715-3b374de37ec6
- Characters are rendered as html tags and commands
https://github.com/linagora/tmail-flutter/assets/80730648/2d84166a-85d8-4800-9384-2c9f3aa5865d
> TF-1912 Rendering issue on TMail when reading an email

- .github/workflows/analyze-test.yaml
- .github/workflows/build.yaml
- .github/workflows/pr-deployments.yaml
- .github/workflows/release.yaml
- Dockerfile
- android/build.gradle
- contact/pubspec.lock
- contact/pubspec.yaml
- core/pubspec.lock
- core/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/icon_open_advanced_search_widget.dart
- lib/features/thread/presentation/thread_controller.dart
- model/pubspec.lock
- model/pubspec.yaml
- prebuild.sh
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
- #1849
- [super_tag_editor](https://github.com/dab246/super_tag_editor/pull/22)
- [flutter-date-range-picker](https://github.com/linagora/flutter-date-range-picker/pull/6)
- [html-editor-enhanced](https://github.com/linagora/html-editor-enhanced/pull/17)
> Upgrade flutter to `v3.10.6`

- env.file
- lib/features/login/data/network/config/authorization_interceptors.dart
- `DioError` has `response` as null.
- Request header
```
POST /oidc/jmap HTTP/1.1
Accept-Encoding: gzip, deflate
Accept-Language: vi,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 625
DNT: 1
Host: apisix.example.com:9080
Origin: http://test.sso.example.com:8080
Referer: http://test.sso.example.com:8080/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
accept: application/json;jmapVersion=rfc-8621
authorization: Bearer token
content-type: application/json
```
- Response header
```
HTTP/1.1 401 Unauthorized
Date: Mon, 17 Jul 2023 04:57:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 653
Connection: keep-alive
WWW-Authenticate: Bearer realm="apisix", error="invalid_token", …
```
> Fix re-login app when token expires in OIDC

- contact/pubspec.lock
- core/lib/presentation/extensions/color_extension.dart
- fcm/pubspec.lock
- forward/pubspec.lock
- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/extensions/calendar_event_extension.dart
- lib/features/email/presentation/styles/calendar_date_icon_widget_styles.dart
- lib/features/email/presentation/styles/calendar_event_action_banner_styles.dart
- lib/features/email/presentation/styles/calendar_event_information_widget_styles.dart
- lib/features/email/presentation/widgets/calendar_date_icon_widget.dart
- lib/features/email/presentation/widgets/calendar_event_action_banner_widget.dart
- lib/features/email/presentation/widgets/calendar_event_information_widget.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view.dart
- lib/main/localizations/language_code_constants.dart
- lib/main/localizations/localization_service.dart
- lib/main/utils/app_utils.dart
- model/pubspec.lock
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
#2040 
- Need merged: https://github.com/linagora/jmap-dart-client/pull/70
- Mobile:
https://github.com/linagora/tmail-flutter/assets/80730648/f32eaa70-4d78-48a5-8edd-3b8e2d48ae58
- Tablet:
https://github.com/linagora/tmail-flutter/assets/80730648/1fd97682-69de-4250-91b1-04670baa7b57
- Responsive browser:
https://github.com/linagora/tmail-flutter/assets/80730648/ee747f2a-c3c0-4100-a58f-72f0fc41c3d7
> TF-2040 Add calendar date icon in email view

- ios/Runner/Info.plist
#2087 
- iOS
https://github.com/linagora/tmail-flutter/assets/80730648/d7040f9c-e8d8-45c3-87f3-a781d585f2fb
- Android
[android.webm](https://github.com/linagora/tmail-flutter/assets/80730648/54972d69-906f-48ea-9744-87b8890a552e)
> TF-2087 Fix status bar missing in dark theme mode

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
#2089 
- Because we override SingleScrollView's scroll event, RefreshIndicator can't listen and control its scroll.
- Mobile
https://github.com/linagora/tmail-flutter/assets/80730648/58fc19e1-682c-4573-bc0e-5e6d9ecf6760
- Web
https://github.com/linagora/tmail-flutter/assets/80730648/b3eb79c6-6986-48e3-ae6b-35f1ee953e8b
> TF-2089 Pull to refresh mailbox view not working

- lib/features/quotas/domain/extensions/quota_extensions.dart
#2099
- Due to the conversion of `limit` to `hardLimit`, we only use `hardLimit` and ignore `limit` in the new version.
- Use both `limit` when `hardLimit` is null. Ex: `presentationHardLimit = hardLimit ?? limit`
https://github.com/linagora/tmail-flutter/assets/80730648/cb14d017-40e0-4037-bf18-c4906312606e
> TF-2099 Fix Quota information are missing

- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/login/data/network/config/oidc_constant.dart
#1974 
- We get this error when we call refreshToken: `PlatformException(token_failed, Concurrent operations detected: token, token, null, null)` . As implied by the error, this would mean your application is making concurrent calls to the plugin where it's not waiting for an operation to finish before starting another one.
- Use `QueuedInterceptorsWrapper`.  If there are multiple concurrent requests, the request is added to a queue before
entering the interceptor. Only one request at a time enters the interceptor, and after that request is processed by the interceptor, the next request will enter the interceptor.
- Work fine  on device Android
> TF-1974 Fix refresh token OIDC failed

- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
#1845 
https://github.com/linagora/tmail-flutter/assets/80730648/a56871db-9676-4fbd-8536-5c1b61e1aa04
> TF-1845 Fix the searching result is not correct with the condition `Doesn't have` and `Has the words`

- lib/features/email/domain/model/mark_read_action.dart
- lib/features/email/domain/state/mark_as_email_read_state.dart
- lib/features/email/domain/usecases/mark_as_email_read_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/presentation/mixin/email_action_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
---
#1946
#1947 
---
- Use `Dismissible` to make item can swipe
---
- Mobile
https://github.com/linagora/tmail-flutter/assets/80142234/0763126a-1d4b-469d-ab43-1646b84c05a8
- Web
https://github.com/linagora/tmail-flutter/assets/80142234/64b69ebb-1312-4fe1-adad-d0debd600761
> TF-1946,1947 Swipe left in item of Thread View

- core/lib/utils/app_logger.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/upload/data/model/upload_file_arguments.dart
- lib/features/upload/data/network/file_uploader.dart
- lib/features/upload/domain/extensions/file_info_extension.dart
- lib/features/upload/domain/model/mobile_file_upload.dart
#2129 
- Impact from upgrading version flutter `3.10.6` and dart `3.0.0`. Dart SDK have tightened the rules for which objects can be sent across isolates (see https://api.dart.dev/stable/3.0.0/dart-isolate/SendPort/send.html and https://github.com/dart-lang/sdk/commit/67683c39)
https://github.com/linagora/tmail-flutter/assets/80730648/b836a564-b032-4a01-9cbb-b1b4716bcebb
> TF-2129 Fix cannot attach file on mobile

- docs/adr/0031-fix-refresh-token-with-oidc.md
- lib/features/login/data/network/config/authorization_interceptors.dart
#1974 
- When executing tasks concurrently, they are pushed into the queue along with the old `header` values (the old `authentication` is retained). So when the first request receives a `401` error and tries to get a new token, it will be updated with the new `authentication-header` value.
https://github.com/linagora/tmail-flutter/assets/80730648/fc883e99-a417-49f9-93eb-e6ad9db28cb1
> [HOT-FIX] Fix refresh token with oidc on `upn`

- core/lib/presentation/extensions/color_extension.dart
- lib/features/rules_filter_creator/presentation/model/rule_filter_condition_type.dart
- lib/features/rules_filter_creator/presentation/model/rules_filter_input_field_arguments.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_remove_button_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_widget.dart
- lib/features/rules_filter_creator/presentation/widgets/rules_filter_input_decoration_builder.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- pubspec.yaml
---
#2083 
---
https://github.com/linagora/tmail-flutter/assets/80142234/8deca3b1-a814-405f-869d-71016f2e5467
> TF-2083 Add/remove conditions in UI

- core/lib/presentation/extensions/html_extension.dart
#2092 
https://github.com/linagora/tmail-flutter/assets/80730648/322b4511-d86e-4af7-831b-e9bdc0292c05
> TF-2092 Add `dash-dash-space` to signature delimiter

- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
- lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_row_builder.dart
- lib/features/rules_filter_creator/presentation/widgets/rule_filter_condition_widget.dart
https://github.com/linagora/tmail-flutter/assets/80730648/0dbe4da3-3ebc-47c2-a575-29d2d6177779
> [Hotfix] Temporarily hide `Add condition` in filter rule for release new version

- server/nginx.conf
- Impact from configuring the URL strategy on the web use `PathUrlStrategy` not work on `release` mode
- Due to the line `include /etc/nginx/conf.d/*.conf;`. The `default.conf` is loaded and your server config is ignored.
- Comment the following line: 
```
```
https://github.com/linagora/tmail-flutter/assets/80730648/92afced7-4381-489b-8143-a98ed22c7ad9
> [HOT-FIX] Fix built release but nginx route `404 not found` on web

- pubspec.lock
#2120 
#2121 
- Because the `drag and drop` handling function of the `summernote` library is incorrect.
- Fixed here: https://github.com/linagora/html-editor-enhanced/pull/22
- Need merged: https://github.com/linagora/html-editor-enhanced/pull/22
https://github.com/linagora/tmail-flutter/assets/80730648/c1631a4f-1293-4149-81e2-9ac19bc819ce
> TF-2120, 2121 Fix drag and drop text inside/outside the composer on web

- core/lib/domain/extensions/media_type_extension.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/composer/presentation/extensions/file_upload_extension.dart
- lib/features/composer/presentation/view/web/web_editor_view.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- lib/features/upload/domain/model/upload_attachment.dart
- lib/features/upload/domain/state/attachment_upload_state.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- model/lib/upload/file_info.dart
- pubspec.lock
#2118 
- Need merged: https://github.com/linagora/html-editor-enhanced/pull/24
https://github.com/linagora/tmail-flutter/assets/80730648/b8739a6b-40b4-447e-9c95-b11ba1198cc0
> TF-2118 Support `drag n drop`  for `Image/File`

- lib/features/base/mixin/app_loader_mixin.dart
- lib/features/caching/caching_manager.dart
- lib/features/caching/config/cache_version.dart
- lib/features/email/data/network/email_api.dart
- lib/features/email/domain/state/download_attachment_for_web_state.dart
- lib/features/email/domain/usecases/download_attachment_for_web_interactor.dart
- lib/features/email/domain/usecases/download_attachments_interactor.dart
- lib/features/email/domain/usecases/export_attachment_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/login/data/datasource_impl/hive_account_datasource_impl.dart
- lib/features/login/data/extensions/account_cache_extensions.dart
- lib/features/login/data/extensions/list_account_cache_extensions.dart
- lib/features/login/data/local/account_cache_manager.dart
- lib/features/login/data/local/authentication_info_cache_manager.dart
- lib/features/login/data/network/config/authorization_interceptors.dart
- lib/features/login/data/repository/account_repository_impl.dart
- lib/features/login/data/repository/credential_repository_impl.dart
- lib/features/login/domain/exceptions/authentication_exception.dart
- lib/features/login/domain/repository/account_repository.dart
- lib/features/login/domain/repository/credential_repository.dart
- lib/features/login/domain/usecases/get_credential_interactor.dart
- lib/features/mailbox_dashboard/presentation/model/download/download_task_state.dart
- lib/features/mailbox_dashboard/presentation/widgets/download/download_task_item_widget.dart
- lib/features/sending_queue/domain/model/sending_email.dart
- lib/features/session/data/datasource_impl/hive_session_datasource_impl.dart
- lib/features/session/data/exceptions/session_exceptions.dart
- model/lib/account/account_request.dart
- test/features/caching/accountl_cache_test.dart
#2177 
- Due Token not found in cache, multiple accounts exist at the same time
https://github.com/linagora/tmail-flutter/assets/80730648/899542ba-c256-49e2-a84a-f0adf170e3a3
> TF-2177 Download attachment file is not working

- lib/features/composer/presentation/styles/recipient_tag_item_widget_style.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- lib/features/composer/presentation/widgets/recipient_tag_item_widget.dart
- pubspec.lock
- pubspec.yaml
#2259
- Need merged: https://github.com/dab246/super_tag_editor/pull/29
- Mobile
https://github.com/linagora/tmail-flutter/assets/80730648/53dbb566-aced-4e48-9a33-98a7230731be
- Web:
https://github.com/linagora/tmail-flutter/assets/80730648/dc0cd367-3eb6-4a5f-b1e8-887d29e93082
> TF-2259 Fix suggestion will be displayed on top in composer

- core/lib/presentation/extensions/color_extension.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/styles/mobile/from_composer_bottom_sheet_style.dart
- lib/features/composer/presentation/styles/mobile/from_composer_mobile_widget_style.dart
- lib/features/composer/presentation/styles/web/from_composer_drop_down_widget_style.dart
- lib/features/composer/presentation/widgets/mobile/from_composer_bottom_sheet_builder.dart
- lib/features/composer/presentation/widgets/mobile/from_composer_mobile_widget.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- lib/features/composer/presentation/widgets/web/from_composer_drop_down_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
---
#2196 
---
- Web:
https://github.com/linagora/tmail-flutter/assets/80142234/aa6bd199-fae3-4fb0-9009-81dc4787e001
- Mobile:
https://github.com/linagora/tmail-flutter/assets/80142234/2e2b50eb-280c-4c76-b0d1-db08a02c2a28
> TF-2196 Add field 'From' to composer

- lib/features/email/data/network/email_api.dart
- model/lib/extensions/list_email_id_extension.dart
- model/lib/extensions/mailbox_id_extension.dart
Adding testing feature for marking mails which are going to spam and they will be unread so counter of unread messages will not rise, working for draging, moving to spam trough button and also marking as spam.
> TF-2203 Unread emails which are going to spam folder will be unread

- model/lib/email/attachment.dart
- model/lib/extensions/list_attachment_extension.dart
#2345 
https://github.com/linagora/tmail-flutter/assets/80730648/ede5f68c-cc02-4332-a60e-03f72d18fb88
> TF-2345 Fix attachments are not displayed when cid is present

- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
---
#2394 
---
https://github.com/linagora/tmail-flutter/assets/80142234/eac84ff1-6496-4d2a-994e-2f2a14690021
> [bugfix] TF-2394 Add `mostRecent` as default value of sortOrder

- model/lib/extensions/presentation_mailbox_extension.dart
#2326 
- Web:
https://github.com/linagora/tmail-flutter/assets/80142234/3d949f71-02d2-452f-a2c2-cca713c02500
- Android:
https://github.com/linagora/tmail-flutter/assets/80142234/8c660220-56a1-4433-951a-4772b814dc99
> TF-2326 Allow display count of total emails for draft folder

- model/lib/extensions/presentation_email_extension.dart
- test/model/lib/extensions/presentation_email_extension_test.dart
#2459 
```dart
GIVEN I am not the sender
Sender configured the replyTo
AND there are other recipients
WHEN I click on reply
THEN the 'to' field is fielded with all email
```
https://github.com/linagora/tmail-flutter/assets/80142234/1a32dfe2-4a56-4309-b780-eaff379878a9
- When current user is not the sender and email has `replyTo` field in the header, we combined `to` field and `replyTo` field for generating recipients which should only contain `replyTo`.
https://github.com/linagora/tmail-flutter/assets/80142234/0f39dfc6-6be6-49aa-8a13-9ebf07628484
> [bugfix] TF-2459 ReplyTo and ReplyToAll have the same effect

- lib/features/email/presentation/extensions/attachment_extension.dart
- lib/features/email/presentation/styles/attachment/attachment_item_widget_style.dart
- lib/features/email/presentation/styles/attachment/attachment_list_item_widget_styles.dart
- lib/features/email/presentation/styles/attachment/attachment_list_styles.dart
- lib/features/email/presentation/styles/email_attachments_styles.dart
- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_bottom_sheet_body_builder.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_dialog_body_builder.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_item_widget.dart
- lib/features/email/presentation/widgets/email_address_dialog_builder.dart
- lib/features/email/presentation/widgets/email_attachments_widget.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
- lib/features/upload/presentation/model/upload_file_state.dart
- model/lib/email/attachment.dart
- model/lib/extensions/attachment_extension.dart
- model/lib/extensions/list_attachment_extension.dart
- model/test/attachment_test.dart
- test/features/model/attachment_extension_test.dart
#2510 
https://github.com/linagora/tmail-flutter/assets/80730648/a8be6ad5-b81d-4acf-89e5-afde7a91ef7f
> TF-2510 Fix failure handle empty CIDs

- lib/features/composer/domain/state/download_image_as_base64_state.dart
- lib/features/composer/domain/usecases/download_image_as_base64_interactor.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view.dart
- lib/features/composer/presentation/controller/rich_text_mobile_tablet_controller.dart
- lib/features/composer/presentation/view/mobile/mobile_container_view.dart
- lib/features/composer/presentation/widgets/mobile/app_bar_composer_widget.dart
- lib/features/composer/presentation/widgets/mobile/landscape_app_bar_composer_widget.dart
- lib/features/composer/presentation/widgets/mobile/tablet_app_bar_composer_widget.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/upload/domain/state/attachment_upload_state.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- lib/features/upload/presentation/extensions/upload_attachment_extension.dart
- lib/features/upload/presentation/model/upload_file_state.dart
- lib/main/utils/email_receive_manager.dart
- pubspec.lock
#2532 
- Need merged: 
- https://github.com/linagora/enough_html_editor/pull/27
- https://github.com/linagora/rich-text-composer/pull/26
- Android
https://github.com/linagora/tmail-flutter/assets/80730648/340b1372-5144-4d31-933e-81c2768a058a
- iPhone
https://github.com/linagora/tmail-flutter/assets/80730648/a700568e-fcd6-402f-9246-76cc2b1d660b
- iPad
https://github.com/linagora/tmail-flutter/assets/80730648/5e650aac-4bda-4bc3-b6af-8eef3d4aceb3
> TF-2532 Add `attachment/inlineImage` to app bar composer Mobile/Tablet

- lib/l10n/intl_fr.arb
Backport of https://github.com/linagora/tmail-flutter/pull/2593
> FR translation: vacances => réponse automatique (like GMail)

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
#2559 
#2560 
#2603 
- This problem only occurs when the `To/Cc/Bcc` fields remain `focused`. 
- The reason is that the height of `WebViewEditor` changed, causing it to be re-rendered, so the parent widget is still displayed on the screen. (Influenced by PR change #2516)
- Only listen for height changes of the `composer` widget. Not listening for `editor` height changes
https://github.com/linagora/tmail-flutter/assets/80730648/fcda0447-aa12-47f1-9e54-6e5ca04e520a
> TF-2559, 2560, 2603 Cannot close composer when `forward/send` email

- lib/features/thread/data/datasource/thread_datasource.dart
- lib/features/thread/data/datasource_impl/local_thread_datasource_impl.dart
- lib/features/thread/data/datasource_impl/thread_datasource_impl.dart
- lib/features/thread/data/local/email_cache_manager.dart
- lib/features/thread/data/network/thread_isolate_worker.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
#2564 
- Context: On Mobile, use `Isolate` to delete emails in the mailbox. After each deletion of an email list, we call `sendPort.send()` to transmit the deleted email list to `main`:
- If `sendPort.send()` submitted successfully → Update cache
- If `sendPort.send()` faulty  → Cache not updated. This is the issue.
We wait for the email delete request to `JMAP` to complete before updating the cache.
> TF-2564 Fix impossible clean all spam mailbox when more 1000 emails

- docs/adr/0038-logic-for-displaying-attachment-types-in-emails.md
- model/lib/email/attachment.dart
- model/lib/extensions/attachment_extension.dart
- model/test/attachment_test.dart
#2610
- The attachment display logic is incorrect. In this case, we don't display when `disposition = inline` and `cid is null`
- Change attachment display logic.
- Write `adr` for attachments display logic
> TF-2610 Fix missing attachments when mail sent from iphone

- core/lib/utils/platform_info.dart
- core/lib/utils/web_renderer/canvas_kit.dart
- core/lib/utils/web_renderer/canvas_kit_stub.dart
- core/lib/utils/web_renderer/canvas_kit_web.dart
- lib/features/composer/presentation/widgets/attachment_item_composer_widget.dart
- lib/features/composer/presentation/widgets/recipient_tag_item_widget.dart
- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_item_widget.dart
- lib/features/email/presentation/widgets/feedback_draggable_attachment_item_widget.dart
#2537 
- Dependence `ExtendedText` widget use `BlendMode.clear` but flutter web does not support `BlendMode.clear` or `BlendMode.dst` when using `html renderer`
- Only use `ExtendedText` widget when `web_renderer` is `canvaskit`
https://github.com/linagora/tmail-flutter/assets/80730648/d774d255-13f9-4525-a77a-aaa6f0d7722e
> TF-2537 Fix user got crash when trying attach pdf file

- CHANGELOG.md
- contact/pubspec.lock
- contact/pubspec.yaml
- core/lib/core.dart
- core/lib/utils/option_param_mixin.dart
- email_recovery/pubspec.lock
- email_recovery/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/manage_account/presentation/model/vacation/vacation_presentation.dart
- lib/features/manage_account/presentation/vacation/vacation_controller.dart
- model/pubspec.lock
- model/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
- #2638 
- root cause: null value is not update exactly for `toDate` field
https://github.com/linagora/tmail-flutter/assets/6462404/a79f34c8-2b41-424f-b606-7efd0b18871e
> Update exactly what Vacation change

- core/lib/data/constants/constant.dart
- core/lib/data/network/download/download_manager.dart
- docs/adr/0039-logic-for-opening-pdf-in-new-browser-tab.md
- lib/features/email/domain/state/view_attachment_for_web_state.dart
- lib/features/email/domain/usecases/view_attachment_for_web_interactor.dart
- lib/features/email/presentation/bindings/email_bindings.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/attachment_item_widget.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_dialog_body_builder.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_dialog_builder.dart
- lib/features/email/presentation/widgets/attachment_list/attachment_list_item_widget.dart
- lib/features/email/presentation/widgets/draggable_attachment_item_widget.dart
- lib/features/email/presentation/widgets/email_attachments_widget.dart
- pubspec.lock
- pubspec.yaml
- test/features/email/domain/usecases/view_attachment_for_web_interactor_test.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
https://github.com/linagora/tmail-flutter/issues/2628
As discussed with @hoangdat , @dab246 & @hieutbui , attachment button for PDF in web version will have 2 functionalities. When user tap on download icon inside the button, openDownloadedFileWeb will be triggered, showing the PDF inside new browser tab and user can download the file here themselves. When tapping anywhere else inside the attachment button, the PDF will be downloaded automatically, and the auto opening feature will be handle by the browser itself depends on its own settings.
- Firefox
https://github.com/linagora/tmail-flutter/assets/160106668/9947e64d-b9db-4670-8d9b-ed6e2810a83d
https://github.com/linagora/tmail-flutter/assets/160106668/27166523-d924-4ca1-8e18-c53867f3f749
- Safari …
> TF-2628 Create open PDF in new browser tab feature

- lib/features/composer/presentation/composer_controller.dart
Root cause: if open and close composer very frequently, sometime userAgent is not `init` and `release` well
> Try to fix crash in composer

- core/lib/utils/html/html_utils.dart
- docs/adr/0041-fix-text-overlap-on-pasting-or-dropping-rich-text.md
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
#2591 
Run a JS script to update text-height for all elements to 100% on content pasted & drag-dropped to the editor
- On paste
https://github.com/linagora/tmail-flutter/assets/160106668/e10fc7eb-9d52-4e56-9327-51ae593d5c66
- On drop
https://github.com/linagora/tmail-flutter/assets/160106668/4d91c4df-45c8-4c0b-aba0-c7702ccf5483
> TF-2591 Fix text overlap after pasting rich text

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
#1534 
- Due to conflict between `LongPress` and `Scroll` gesture responses
- Reduced `LongPressGestureRecognizer` response time
- iOS
https://github.com/linagora/tmail-flutter/assets/80730648/acdc8e52-be04-43eb-8c51-601fbe4d7883
- Android
https://github.com/linagora/tmail-flutter/assets/80730648/ff585688-8081-4dc1-b583-8f682e1c8a9d
> TF-1534 Fix cannot selection text on ios

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
> TF-2533: [PART-1] Clean up email detail content

- core/lib/data/network/download/download_client.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
#2774 
- Missing `;` character to separate values in `style` attribute of `img` tag results in `max-width=100%` value not working as expected.
- Add `;` character after after each value
https://github.com/linagora/tmail-flutter/assets/80730648/12aed6ef-31c5-42a8-9043-4f21f7582abd
> TF-2774 Fix big image dimension in signature

- docs/adr/0044-memory-leak-at-current-state.md
> TF-2533 Create ADR to put memory footprint task on hold

- lib/features/login/domain/exceptions/login_exception.dart
- lib/features/login/domain/usecases/get_token_oidc_interactor.dart
- lib/features/login/presentation/login_controller.dart
- lib/features/login/presentation/widgets/login_message_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- pubspec.yaml
- test/features/login/presentation/login_controller_test.dart
https://github.com/MaikuB/flutter_appauth/pull/465
No browser available for OIDC
- parse native exception to business exception `NoSuitableBrowserForOIDCException`
- show error to user
[case_dnslookup.webm](https://github.com/linagora/tmail-flutter/assets/6462404/1e72921a-0941-4009-ab66-0b74caa66fff)
[case_baseUrl.webm](https://github.com/linagora/tmail-flutter/assets/6462404/2859f21c-9a8a-4ffa-9ce7-57a6366870f5)
> TF-2810 Handle crashed when no browser available for OIDC

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- pubspec.lock
- pubspec.yaml
- #2533 
**Before**
https://github.com/linagora/tmail-flutter/assets/160106668/052ab6d5-351a-430b-8837-275518c7ed3a
**After**
https://github.com/linagora/tmail-flutter/assets/160106668/72052419-c011-4b47-bc4a-de8961e34315
> TF-2533 [Part-3] Replace beforeunload with pagehide

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/styles/calendar_event_action_button_widget_styles.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_action_button_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
- #2812 
- Take an `ics` from prod's email, change `organizer` to an email from preprod, let's call email A, in the form of `abc@upn.integration-open-paas.org`, also update an attendee to the testing email, let's call email B, with the same form as the organizer
- Sign in to email B, compose an email, send to self, with the attachment is the ics above
- Due to faking of calendar event, the email content will not be qualify for the 3 buttons `yes`, `maybe` and `no` to appear. A fake parse has to be created. Head to `lib/features/email/data/local/html_analyzer.dart`, replace all code inside `getListEventAction` to:
```dart
return [
EventAction(EventActionType.yes, ''),
EventAction(EventActionType.maybe, ''),
EventAction(EventActionType.no, ''),
];
```
- Make the loading duration longer by …
> [Part-IV] TF-2812 Calendar event accept Integrate UI

- lib/features/base/reloadable/reloadable_controller.dart
- lib/features/login/data/datasource_impl/authentication_oidc_datasource_impl.dart
- lib/main/bindings/credential/credential_bindings.dart
- test/features/home/presentation/home_controller_test.dart
- use `remoteExceptionThrower` for cache operation
> TW-2835 Add right exception thrower for database operation of AuthenticationOIDCDatasource

- lib/features/email/domain/state/calendar_event_reject_state.dart
- lib/features/email/domain/usecases/calendar_event_reject_interactor.dart
- lib/features/email/presentation/bindings/calendar_event_interactor_bindings.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- test/features/email/domain/usecases/calendar_event_reject_interactor_test.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
> [Part-VIII] TF-2840 Calendar event reject interactor and controller

- lib/features/manage_account/domain/exceptions/forward_exception.dart
- lib/features/manage_account/presentation/forward/forward_controller.dart
- lib/features/manage_account/presentation/forward/forward_view.dart
- lib/features/manage_account/presentation/forward/widgets/autocomplete_contact_text_field_with_tags.dart
- lib/l10n/intl_fr.arb
#2830 
- Forward:
https://github.com/linagora/tmail-flutter/assets/80730648/ab330185-98a6-46bd-89ce-edaffa1a8252
- Read recipient:
https://github.com/linagora/tmail-flutter/assets/80730648/b0f747f3-1bde-4dbf-a7ed-79606642e2e3
> TF-2830 Fix add recipient is buggy in forwards

- docs/adr/0047-fcm-ios-push-configuration-confirmation.md
https://github.com/linagora/tmail-backend/commit/43c49615a06edb850fdd7d4b35fbd05873dfc6af#r141977107
**No push notification case**
```ini
[com.linagora.ios.teammail] Received remote notification request <ID> [ waking: 0, hasAlertContent: 0, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Background]
```
**Push notification case**
```ini
[com.linagora.ios.teammail] Received remote notification request <ID> [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 1 pushType: Alert]
```
> Create ADR reconfirming the configuration of fcm ios payload

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/widgets/attachment_item_composer_widget.dart
- lib/features/composer/presentation/widgets/attachment_progress_loading_composer_widget.dart
- lib/features/composer/presentation/widgets/mobile/mobile_attachment_composer_widget.dart
- lib/features/composer/presentation/widgets/web/attachment_composer_widget.dart
- lib/features/upload/presentation/controller/upload_controller.dart
#2919
>  1.  Memory leak when attach files in composer
https://github.com/linagora/tmail-flutter/assets/80730648/577f36bf-05d8-44ad-9e0a-d79b3a2006f4
- Because `AttachmentItemComposerWidget` and `AttachmentProgressLoadingComposerWidget` still hold a reference to the `UploadFileState` object, `UploadFileState` contains the `FileInfo` object with the `bytes` property. So when `ComposerController` and `UploadController` are disposed, this reference still exists, leading to a memory leak.
https://github.com/linagora/tmail-flutter/assets/80730648/e56b77bd-7773-4b3b-b8e6-c0bec698abe8
> TF-2919 [Part 2] Refactor New composer

- pubspec.lock
#2868 
- Side effect of fixing memory leak error in PR https://github.com/linagora/html-editor-enhanced/pull/34. Resulting in `ToolbarWidget` not being created, causing `toolbar` object in `HtmlEditorController` to be null. And `onChangeSelection` is not listened to.
- https://github.com/linagora/html-editor-enhanced/pull/39
https://github.com/linagora/tmail-flutter/assets/80730648/ab0ae98c-7081-4875-b054-c9c1dcffb856
> TF-2868 Fix composer bold option toggle

- lib/features/email/domain/model/email_print.dart
- lib/features/email/presentation/action/email_ui_action.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/widgets/email_view_app_bar_widget.dart
- lib/features/email/presentation/widgets/email_view_bottom_bar_widget.dart
#2827 
- Only display the `Reply`, `Reply all`, `Forward`, `Print` actions when the email content has been loaded successfully.
https://github.com/linagora/tmail-flutter/assets/80730648/3f37d187-0980-43d3-afc5-dec79e58485b
> TF 2827 Fix clicking reply before content is loaded

- core/lib/domain/exceptions/web_session_exception.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- core/lib/presentation/utils/html_transformer/transform_configuration.dart
- lib/features/base/base_controller.dart
- lib/features/base/before_unload_handler.dart
- lib/features/base/before_unload_manager.dart
- lib/features/composer/domain/state/restore_email_inline_images_state.dart
- lib/features/composer/domain/usecases/restore_email_inline_images_interactor.dart
- lib/features/composer/domain/usecases/save_composer_cache_on_web_interactor.dart
- lib/features/composer/presentation/composer_bindings.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/model/screen_display_mode.dart
- lib/features/composer/presentation/widgets/insert_image_loading_bar_widget.dart
- lib/features/email/presentation/extensions/composer_arguments_extension.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox_dashboard/data/datasource/session_storage_composer_datasource.dart
- lib/features/mailbox_dashboard/data/datasource_impl/session_storage_composer_datasoure_impl.dart
- lib/features/mailbox_dashboard/data/model/composer_cache.dart
- lib/features/mailbox_dashboard/data/repository/composer_cache_repository_impl.dart
- lib/features/mailbox_dashboard/domain/repository/composer_cache_repository.dart
- lib/features/mailbox_dashboard/domain/usecases/get_composer_cache_on_web_interactor.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- lib/main/bindings/core/core_bindings.dart
- test/features/base/before_unload_manager_test.dart
- #2901 
https://github.com/linagora/tmail-flutter/assets/160106668/931b2476-3786-4bd9-b3d9-94a8951b0ce4
> TF-2901 Composer cache web

- contact/pubspec.lock
- contact/pubspec.yaml
- email_recovery/pubspec.lock
- email_recovery/pubspec.yaml
- fcm/pubspec.lock
- fcm/pubspec.yaml
- forward/pubspec.lock
- forward/pubspec.yaml
- lib/features/email/data/network/calendar_event_api.dart
- lib/features/email/domain/exceptions/calendar_event_exceptions.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/email/presentation/extensions/calendar_event_extension.dart
- lib/features/email/presentation/extensions/list_attendee_extension.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/calendar_event_information_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_attendee_detail_widget.dart
- lib/features/email/presentation/widgets/calendar_event/event_attendee_information_widget.dart
- model/pubspec.lock
- model/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- rule_filter/pubspec.lock
- rule_filter/pubspec.yaml
- server_settings/pubspec.yaml
#2907 
- https://github.com/linagora/jmap-dart-client/pull/88
https://github.com/linagora/tmail-flutter/assets/80730648/fff8145a-4e81-429c-b960-f6dd61cec47d
> TF-2907 Disable `YES/NO/MAYBE` action for events when missing `METHOD/ORGANIZER/ATTENDEES` in ics

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/view/web/web_editor_view.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- pubspec.lock
#2989 
- Due disable summernote's default `drag & drop` in `html-editor-enhanced` to customize drop zone view
- https://github.com/linagora/html-editor-enhanced/pull/42
- https://github.com/linagora/html-editor-enhanced/pull/43
https://github.com/linagora/tmail-flutter/assets/80730648/15055d87-97dc-4a27-8c77-a603cc338ebf
> TF-2989 Fix drag and drop text within composer is broken

- contact/pubspec.lock
- fcm/pubspec.lock
- forward/pubspec.lock
- model/lib/mailbox/presentation_mailbox.dart
- model/pubspec.lock
- pubspec.lock
- rule_filter/pubspec.lock
- server_settings/.gitignore
- server_settings/pubspec.lock
This is the role that should be used according to the JMAP specification. Closes #2894
In order not to break compatibility with current JAMES implementation (that uses incorrect `spam` role), this should be merged when `jmap-dart-client` [PR 89](https://github.com/linagora/jmap-dart-client/pull/89) has been merged.
> Use `junk` role for `Spam/Junk` folder

- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/thread/domain/state/get_all_email_state.dart
- lib/features/thread/domain/state/refresh_changes_all_email_state.dart
- lib/features/thread/domain/usecases/get_emails_in_mailbox_interactor.dart
- lib/features/thread/domain/usecases/refresh_changes_emails_in_mailbox_interactor.dart
- lib/features/thread/presentation/thread_controller.dart
- test/features/thread/domain/usecases/get_emails_in_mailbox_interactor_test.dart
- test/features/thread/domain/usecases/refresh_changes_emails_in_mailbox_interactor_test.dart
#2925 
- Because `RefreshChangeEmail` executes before `GetAllEmail` but returns the following result. So the email list will not be updated correctly.
[demo.webm](https://github.com/user-attachments/assets/6455ebbf-27ce-4427-ae92-f207ac370ce0)
> TF-2925 The message list not showed correctly when change mailbox very quick 

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
#2951
https://github.com/user-attachments/assets/e4b6746e-c271-4c50-97fb-22285d16adbe
> TF-2951 Remove Clean button, "Empty Trash/Spam now" banner and Filters when there is no email in Spam/Trash folder

- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/composer_view_web.dart
- lib/features/composer/presentation/extensions/file_upload_extension.dart
- lib/features/composer/presentation/view/web/web_editor_view.dart
- lib/features/composer/presentation/widgets/web/web_editor_widget.dart
- lib/features/upload/domain/extensions/list_file_info_extension.dart
- lib/features/upload/domain/extensions/list_file_upload_extension.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/lib/upload/file_info.dart
- pubspec.lock
- pubspec.yaml
- Cannot copy & paste base64 image as inline image in composer web
https://github.com/linagora/html-editor-enhanced/pull/44
- Single image:
https://github.com/user-attachments/assets/8d9d9e63-05fb-478d-a937-a909006d95b8
- Multiple Image:
https://github.com/user-attachments/assets/96469ac8-40fe-4cea-a2c9-8498188a78ca
> [HOT-FIX] Fix cannot copy & paste base64 image as inline image in composer web

- lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart
Cannot display mailbox name when edit rule filter
- Side effect from PR #3049
https://github.com/user-attachments/assets/343d1715-29b4-4002-935a-d60636681938
> [HOT-FIX] Cannot display mailbox name when edit rule filter

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- #3077
After merging 
- #3129
[mark-mailbox-as-read.webm](https://github.com/user-attachments/assets/6ad755f4-1901-4011-a987-58af61c9343f)
> TF-3077 Remove stacktrace from error toast

- lib/features/thread/data/network/thread_isolate_worker.dart
- lib/main.dart
- lib/main/bindings/network/network_isolate_binding.dart
#3113 
[reproduced.webm](https://github.com/user-attachments/assets/41525a2b-c933-4bcb-9b5b-6a2d16f81e9d)
- [SendPort.send()](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html) of isolate flutter only supports some objects
- Network connection objects cannot be shared between isolates.
[demo-spam.webm](https://github.com/user-attachments/assets/c82868e1-95ea-4c62-b7e9-70cb8e71c685)
> TF-3113 Fix cannot empty spam on mobile

- lib/features/upload/data/network/file_uploader.dart
- lib/features/upload/domain/model/upload_attachment.dart
- lib/features/upload/presentation/controller/upload_controller.dart
- #2769 
- https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html
- https://github.com/machinescream/worker_manager/issues/86
We are using `lib/features/upload/data/network/file_uploader.dart:FileUploader:uploadAttachment:_handleUploadAttachmentAction` function to handle upload file in mobile, with the help of `Dio`, inside a separate isolate with app's main isolate. When this `Dio` throw `DioError` exception, by any reason, this exception in turns get sent from this separate isolate to the main isolate. Inside this `DioError`, the `RequestOptions:data` is sent back out of this separate isolate, with type `Stream`, exactly the type we passed into this isolate by `File(argsUpload.mobileFileUpload.filePath).openRead()`. This type is not supported by `send()` function of `Isolate` …
> TF-2769 Fix isolate illegal data

- lib/features/base/reloadable/reloadable_controller.dart
- test/main/utils/type_operator_test.dart
- https://github.com/linagora/tmail-flutter/pull/3139
- In Dart, there is no operator `!is`. Construction `!is` will perform a non-null assertion on the left operand (!) and then execute the is operator. So the code almost never behaves as expected.
- https://dart.dev/language/operators#type-test-operators
> [HOT-FIX] operator not supported in dart

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- test/features/mailbox_dashboard/presentation/view/mailbox_dashboard_view_widget_test.dart
- test/features/thread/presentation/controller/thread_controller_test.dart
#3123 
https://github.com/user-attachments/assets/e81f19ca-c5da-49ca-8e7e-d21cd05856b9
- Because the list returned when loading more always has the `last element` of the current list
https://github.com/user-attachments/assets/25695b8d-da62-44c5-a224-7af2d094ff9d
> TF-3123 Fix load more irrelevant when filtering emails by unread

- model/lib/email/attachment.dart
- model/test/email/attachment_test.dart
> TF-2983 Fix download EML with special character

- core/lib/utils/platform_info.dart
- lib/features/composer/presentation/composer_controller.dart
- lib/features/composer/presentation/model/saved_email_draft.dart
- pubspec.lock
- pubspec.yaml
- test/features/composer/presentation/composer_controller_test.dart
- test/features/composer/presentation/model/saved_email_draft_test.dart
- test/mocks/mock_web_view_platform.dart
- #3034 
- Compose new email
https://github.com/user-attachments/assets/8f1fb7c8-f63e-4cb1-b432-ae07933bdb4e
- Edting draft email
https://github.com/user-attachments/assets/76cb7626-bf22-41d0-956e-f132840802fd
- Mobile (both cases)
[mobile_draft_save.webm](https://github.com/user-attachments/assets/ccf24d66-54b5-4872-b395-a11897d92238)
> TF-3034 Prevent duplicate draft warning

- docs/adr/0052-logic-sort-order-in-search.md
- lib/features/mailbox_dashboard/presentation/action/dashboard_action.dart
- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/mailbox_dashboard/presentation/widgets/search_input_form_widget.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- test/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller_test.dart
#3006 
- Web:
https://github.com/user-attachments/assets/848ad0e9-cfbb-4ed3-8189-7fa16f7b9037
- Mobile
[Screen_recording_20240917_141456.webm](https://github.com/user-attachments/assets/ae07828a-4487-478b-9ab5-9015c1ba3a57)
> [SEARCH] TF-3006 Mail address handle in quick search bar

- lib/features/mailbox_dashboard/presentation/controller/advanced_filter_controller.dart
- lib/features/mailbox_dashboard/presentation/model/search/advanced_search_filter.dart
- lib/features/mailbox_dashboard/presentation/styles/text_field_autocomplete_email_address_style.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/advanced_search_input_form.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/autocomplete_tag_item_widget_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/advanced_search/text_field_autocomplete_email_address_web.dart
#3007 
https://github.com/user-attachments/assets/6bf596e6-8a7c-445f-ae88-c321276d5598
> TF-3007 [SEARCH] Support drag and drop between From & To field

- lib/features/manage_account/presentation/language_and_region/extensions/locale_extension.dart
- lib/l10n/intl_en.arb
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/localizations/language_code_constants.dart
- lib/main/localizations/localization_service.dart
- lib/main/utils/app_utils.dart
Add german to flutter web app.
> Add german to web app

- lib/features/mailbox_dashboard/presentation/controller/search_controller.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/domain/constants/thread_constants.dart
#3247 
- Due to missing `Cc`property when passing in `Email/get` method
https://github.com/user-attachments/assets/3e46d7fb-eff6-4b6d-827c-7de443613979
> TF-3247 [SEARCH] Fix Cc is displayed when clicking quick search results

- lib/features/email/presentation/extensions/calendar_event_extension.dart
- test/features/email/presentation/extensions/calendar_event_extension_test.dart
- #3222 
- https://www.rfc-editor.org/rfc/rfc5546.html#section-3.2
https://github.com/user-attachments/assets/da2e68ed-3f0a-45e1-8941-906aeaab457e
> TF-3222 Hide reply calendar event action buttons if email is event reply

- lib/features/login/presentation/base_login_view.dart
https://github.com/user-attachments/assets/73dc94a1-ae7e-49e5-8b7c-19ededd95fd2
[mobile.webm](https://github.com/user-attachments/assets/cf3fabbe-40a5-4651-b6c8-573a826a509f)
> Fix focus problem when tab on Login Screen

- core/lib/presentation/utils/html_transformer/dom/sanitize_hyper_link_tag_in_html_transformers.dart
This PR #2917 solved 3D links on web, but still not working on mobile.
[reproduce.webm](https://github.com/user-attachments/assets/e9b499c9-700b-408e-8eb0-c5c200c479f2)
- Because the value `useTooltip=true` is only true on the web. So `sanitizeUrl` only handle for web
- Separate `sanitizeUrl` handling to apply to both mobile and web.
- Clear email cache avoid emails content being loaded from storage.
[demo.webm](https://github.com/user-attachments/assets/c0fd4438-9043-4bf2-aae5-07e43c270eec)
> Fix 3D links not work on mobile

- core/lib/presentation/utils/html_transformer/dom/add_lazy_loading_for_background_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/block_code_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/block_quoted_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/hide_draft_signature_transformer.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_collapsed_signature_button_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_lazy_loading_for_background_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_lazy_loading_image_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_max_width_in_image_style_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_style_tag_outside_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/remove_tooltip_link_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/sanitize_hyper_link_tag_in_html_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/script_transformers.dart
- core/lib/presentation/utils/html_transformer/dom/signature_transformers.dart
- core/lib/presentation/utils/html_transformer/sanitize_autolink_filter.dart
- core/lib/presentation/utils/html_transformer/sanitize_url.dart
- core/test/sanitize_url_test.dart
#3243
- Because the function `Uri.decodeFull(inputText)` throws an exception `FormatException: Invalid UTF-8 byte (at offset 11)` during handle `3D Links ` in DOM.
- This error only occurs on the web
- Add `try/catch` blocks to all email `transformer` DOM handler  functions
- Web:
https://github.com/user-attachments/assets/de975aff-0f1d-454e-b41a-af26412e8aa8
- Mobile:
[demo-mobile.webm](https://github.com/user-attachments/assets/06d394df-f359-4271-94fa-fddaa04a436e)
> TF-3243 Fix email without content

- docs/adr/0036-mailto-uri-chemes-to-interact-twake-mail.md
- lib/features/composer/presentation/composer_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/model/composer_arguments.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailto/presentation/mailto_url_controller.dart
- lib/main/routes/navigation_router.dart
- lib/main/routes/route_utils.dart
- test/main/routes/route_utils_test.dart
- #3221
- https://www.rfc-editor.org/rfc/rfc6068
- Click link
https://github.com/user-attachments/assets/545a29b3-650a-4d99-afb9-8dccbe844aad
- Paste link in browser's navigation bar
https://github.com/user-attachments/assets/bf2dfb01-2fa4-49ff-8984-d131b34c9b4b
> TF-3221 Handle mailto with additional cc and bcc

- lib/features/base/mixin/date_range_picker_mixin.dart
- lib/features/email_recovery/presentation/email_recovery_controller.dart
- lib/features/email_recovery/presentation/model/email_recovery_field.dart
- lib/features/email_recovery/presentation/model/email_recovery_time_type.dart
- lib/features/email_recovery/presentation/model/session_extension.dart
- lib/features/email_recovery/presentation/widgets/date_selection_field/date_selection_field_web_widget.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_desktop_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_mobile_builder.dart
- lib/features/email_recovery/presentation/widgets/email_recovery_form/email_recovery_form_tablet_builder.dart
- lib/features/email_recovery/presentation/widgets/limits_banner.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- pubspec.lock
- pubspec.yaml
- test/features/email_recovery/session_extension_test.dart
tackling [the issue 3219](https://github.com/linagora/tmail-flutter/issues/3219) (duplicated with [the issue 3274](https://github.com/linagora/tmail-flutter/issues/3274))
> Display limits of email recovery

- android/app/build.gradle
- pubspec.lock
- pubspec.yaml
- Current `Patrol` version is `3.11.1`, fixing the issue of white space in test name for androidx test orchestrator 1.5.0 ([Patrol changelogs](https://pub.dev/packages/patrol/changelog))
- Androidx test orchestrator released version 1.5.1, which is to fix the same issue
- With `Patrol: 3.11.1`, our test cases now crash with https://github.com/leancodepl/patrol/issues/1725
Revert `Patrol` back 1 patch to `3.11.0`, reverting the change `Patrol` tried to fix with Androidx test orchestrator 1.5.0
Currently we have 6 test cases, but only 2 is ran. The test crashed so the other 4 is discarded.
All 6 test cases is ran.
> Fix patrol test on Firebase Test Lab

- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/widgets/email_receiver_widget.dart
- lib/features/email/presentation/widgets/email_view_bottom_bar_widget.dart
- lib/features/email/presentation/widgets/information_sender_and_receiver_builder.dart
- lib/features/sending_queue/presentation/widgets/sending_email_tile_widget.dart
- model/lib/extensions/list_email_address_extension.dart
- model/lib/extensions/presentation_email_extension.dart
- model/test/extensions/presentattion_email_extension_test.dart
#3379 
https://github.com/user-attachments/assets/2c279ab5-304a-4089-8e8f-96d7ccd1f719
> TF-3379 Fix email sent to mailing list from other people dont have replyAll button

- CHANGELOG.md
- docs/adr/0055-remove-flutter-service-worker.md
- pubspec.yaml
- web/index.html
- Delegate cache control from Flutter to browser
> Rel 0.14.7

- lib/features/mailbox_dashboard/presentation/extensions/move_emails_to_mailbox_extension.dart
- lib/features/thread/presentation/thread_controller.dart
- #3385 
https://github.com/user-attachments/assets/c49ef057-f959-4971-8fea-e23a3255447e
> TF-3385 Fix loading forever when empty mailbox with less than 20 items

- lib/features/base/base_controller.dart
- lib/features/push_notification/presentation/controller/web_socket_controller.dart
#3323
- In case the user loses network connection or closes the device and reopens it after a while. The websocket connection fails, the number of reconnection attempts `_retryRemained = 0` but still cannot connect to the server.
- Use `AppLifecycleListener` to listen for changes in the application state. We will perform a WebSocket connection check every time the application appears and the user can interact ('onResume'). If the WebSocket connection is lost, we reconnect.
> TF-3323 Handle corner cases of web socket disconnected 

- lib/features/mailbox_dashboard/presentation/model/search/search_email_filter.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- test/features/search/verify_before_time_in_search_email_filter_test.dart
#3345
https://github.com/user-attachments/assets/04455b15-7583-4741-9efc-ad74710a3557
- Because the `before` date time is null when sort order by sender every time user refresh change email
https://github.com/user-attachments/assets/05768aa7-95c9-4e52-90d0-85f61becf6ee
> TF-3345 Fix sort order blinks when deleting emails in search

- lib/features/base/mixin/contact_support_mixin.dart
- lib/features/home/data/datasource_impl/session_datasource_impl.dart
- lib/features/home/data/extensions/session_hive_obj_extension.dart
- lib/features/home/data/network/session_api.dart
- lib/features/home/domain/converter/capability_properties_converter.dart
- lib/features/home/domain/extensions/session_extensions.dart
- lib/features/mailbox/presentation/mailbox_view.dart
- lib/features/mailbox/presentation/mailbox_view_web.dart
- lib/features/mailbox_dashboard/presentation/mailbox_dashboard_view_web.dart
- lib/features/mailbox_dashboard/presentation/widgets/navigation_bar/navigation_bar_widget.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
- lib/features/manage_account/presentation/menu/manage_account_menu_view.dart
- lib/features/manage_account/presentation/menu/settings/settings_controller.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/manage_account/presentation/menu/widgets/account_menu_item_tile_builder.dart
- lib/features/manage_account/presentation/model/account_menu_item.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/routes/route_utils.dart
- model/lib/support/contact_support_capability.dart
- test/features/session/session_extensions_test.dart
tackling [this issue](https://github.com/linagora/tmail-flutter/issues/3451)
disclaimer: i could not test it because i could not find a server that advertizes the `contactSupport` capability
> contact support setting option

- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/presentation/thread_controller.dart
- test/features/search/verify_before_time_in_search_email_filter_test.dart
- Cherry pick PR https://github.com/linagora/tmail-flutter/pull/3437 to `master`
> Cherry pick  #3345 sort order blinks to master

- lib/features/login/data/network/oidc_http_client.dart
- lib/features/mailbox/presentation/mixin/mailbox_widget_mixin.dart
- lib/features/mailbox/presentation/utils/mailbox_utils.dart
- lib/features/manage_account/presentation/manage_account_dashboard_controller.dart
- lib/features/manage_account/presentation/menu/settings/settings_first_level_view.dart
- lib/features/search/mailbox/presentation/search_mailbox_view.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- lib/main/utils/toast_manager.dart
i suggest here two small improvements for tmail-frontend:
1. on the login page, sometimes i was getting a frustrating `unknown error occurred, please try again`. upon inspecting the logs, the error was actually known and had a helpful descriptive message. i think it would be better to display that message rather than leaving it in the logs ? i corrected that in one line.
2. even when working with a server that does not support the `recover deleted messages` feature (eg, the capability `deletedMessagesVault` `com:linagora:params:jmap:messages:vault`), the option still appears in the `trash` mailbox actions. i corrected the bug by adding a little `if` statement.
> Small improvements

- lib/features/login/data/network/oidc_http_client.dart
- lib/features/login/domain/exceptions/login_exception.dart
- lib/features/login/presentation/login_controller.dart
here is a fix for a bug pointed out by [this user experience review](https://github.com/linagora/tmail-flutter/discussions/3435#discussioncomment-12008196).
- upon providing `https://api.fastmail.com/jmap/session`, the actual error is a `401 Unauthorized` and this case was handeled in [this pull request](https://github.com/linagora/tmail-flutter/pull/3428) ;
- upon providing the correct `https://api.fastmail.com`, another error occured because the server answers with HTML instead of JSON, eg, `FormatException`. the correct behaviour, which i fix with the current PR, is to ignore webfinger and fall back to the classic credential form.
> handle parsing exception for `OIDCHttpClient::checkOIDCIsAvailable()`

- lib/features/manage_account/presentation/menu/manage_account_menu_controller.dart
When I do a page reload at the Setting screen, a gray overlay appears on the screen and doesn't go away.
https://github.com/user-attachments/assets/e3ff3658-d7f7-45f0-8231-efb4de7bafd7
- Because `Get.find<MailboxDashBoardController>();` is null in ManageAccountMenuController and it's not use any where.
From https://github.com/linagora/tmail-flutter/pull/3452/files#diff-bf070e8df0d2bb83d6cdd5ed8f5fa9043a199f60caae971e6c77c0e2909c2377
https://github.com/user-attachments/assets/28b2eb81-de17-420e-9eba-e8d82f2c4137
> Hot fix gray screen when reload setting view

- CHANGELOG.md
- pubspec.yaml
- #3349 Sender can set priority in composer
- #3349 Display priority in Email list 
- #3517 Fix "Reply to *me*" field is added when save an email as draft
- #3407 Enable SelectableText for email display name in EmailAddressDialogBuilder
- #3318 Fix black pixel when clicking on attachment with long name
- #3316 Fix inconsistent vacation message
- #3293 Fix blue bar cannot select action banner text
- #3461 Add sort by message size
- #3472 Only display attachment in one line
- #3514 Detect base64 image and transform to CID attachment
- #3539 Autocomplete not show display name
- #3539 Can not paste emails in mouse out focus and tab button
> Bump version to v0.14.15

- integration_test/mixin/scenario_utils_mixin.dart
- integration_test/robots/email_robot.dart
- integration_test/scenarios/email_detailed/reply_all_email_scenario.dart
- integration_test/scenarios/email_detailed/reply_email_with_reply_to_scenario.dart
- integration_test/scenarios/email_detailed/reply_email_without_reply_to_scenario.dart
- integration_test/scenarios/email_detailed/reply_to_list_email_scenario.dart
- integration_test/scenarios/forward_email_scenario.dart
- integration_test/tests/email_detailed/reply_all_email_test.dart
- integration_test/tests/email_detailed/reply_email_with_reply_to_test.dart
- integration_test/tests/email_detailed/reply_email_without_reply_to_test.dart
- integration_test/tests/email_detailed/reply_to_list_email_test.dart
- provisioning/integration_test/eml/forward_email/0.eml
- provisioning/integration_test/eml/reply_email/reply-all.eml
- provisioning/integration_test/eml/reply_email/reply-to-list.eml
- provisioning/integration_test/eml/reply_email/with-reply-to.eml
- provisioning/integration_test/eml/reply_email/without-reply-to.eml
- provisioning/integration_test/eml/search_email_with_sort_order/0.eml
- provisioning/integration_test/eml/search_email_with_sort_order/1.eml
- provisioning/integration_test/eml/search_email_with_sort_order/2.eml
- provisioning/integration_test/eml/search_email_with_sort_order/4.eml
- provisioning/integration_test/provisioning.sh
#3554 
- E2E console log:
```console
🧪 SHOULD see the Subject contain the prefix `Re:`
AND the To, Cc, Bcc field should display correctly
: 
: > Task :app:connectedDebugAndroidTest
: Starting 4 tests on Pixel_3a_API_31(AVD) - 12
✅   1. waitUntilVisible widgets with type "TwakeWelcomeView".
✅   2. tap widgets with text "Use company server".
✅   3. waitUntilVisible widgets with type "LoginView".
✅   4. tap widgets with type "TextField" descending from widgets with key [<'dns_lookup_input_form'>].
✅   5. enterText widgets with type "TextField" descending from widgets with key [<'dns_lookup_input_form'>].
✅   6. waitUntilVisible widgets with text "bob".
✅   7. tap widgets with text "Next".
✅   8. waitUntilVisible widgets with key [<'base_url_form'>] descending from widgets with type …
```
> TF-3554 E2E email view reply forward email

- integration_test/scenarios/send_email_with_mark_as_important_scenario.dart
- lib/features/composer/presentation/extensions/email_action_type_extension.dart
- lib/features/composer/presentation/extensions/setup_email_subject_extension.dart
```
When I reply an email
Then I don't see prefix `Re:` in subject field
```
2. Integration test failed
https://github.com/user-attachments/assets/54077ce7-deb9-49a7-bef4-f628c4a65f8c
> [HOT-FIX] Fix missing email subject prefix (`Re:`, `Fwd:`) when `reply` or `forward` email

- core/lib/presentation/state/failure.dart
- core/lib/presentation/utils/app_toast.dart
- core/test/presentation/utils/app_toast_test.dart
- lib/features/base/base_controller.dart
- lib/features/email/domain/state/get_email_content_state.dart
- lib/features/email/domain/usecases/get_email_content_interactor.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/mailbox/data/repository/mailbox_repository_impl.dart
- lib/features/mailbox/domain/state/get_all_mailboxes_state.dart
- lib/features/mailbox/domain/usecases/get_all_mailbox_interactor.dart
- lib/features/mailbox/presentation/mailbox_controller.dart
- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
- lib/features/search/email/presentation/search_email_controller.dart
- lib/features/thread/domain/state/search_email_state.dart
- lib/features/thread/domain/usecases/search_email_interactor.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- test/features/email/presentation/controller/single_email_controller_test.dart
- test/features/mailbox/repository/mailbox_respository_test.dart
- test/features/thread/domain/usecases/search_email_interactor_test.dart
- #3487 
https://github.com/user-attachments/assets/f316bb34-e646-4754-9f78-63eecce51ede
https://github.com/user-attachments/assets/6d27f467-ad52-43d0-949e-b31f109db140
https://github.com/user-attachments/assets/7eacd1bb-c2ed-4dbf-8c5f-d36b9550dcfc
https://github.com/user-attachments/assets/d8da09ce-69e8-42ae-90a6-426d78a5567c
> TF-3487 Handle Twake Mail errors

- lib/features/identity_creator/presentation/identity_creator_controller.dart
#3623 
The `controller.isMobile(context)` check fails to correctly identify mobile layout when the screen height is less than its width, causing the bottom actions to not display as expected.
Ensure the platform is correctly detected to render the appropriate layout or UI elements
https://github.com/user-attachments/assets/44cc807c-9d80-447f-a3e3-76408e56d288
> TF-3623 Fix `Cancel`, `Create`, `Save as default` are displayed 2 times in the dialog `Create new identity`

- core/lib/data/network/download/download_client.dart
- core/lib/presentation/utils/html_transformer/dom/image_transformers.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- core/lib/utils/html/html_interaction.dart
- core/lib/utils/platform_info.dart
- integration_test/scenarios/email_detailed/deformed_inlined_image_scenario.dart
- integration_test/tests/email_detailed/deformed_inlined_image_test.dart
- lib/features/composer/presentation/controller/rich_text_web_controller.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/email/presentation/email_view.dart
- lib/features/public_asset/presentation/public_asset_controller.dart
#3622
Some `img` elements have a width attribute that is larger than the current display width. In the previous handling flow, we always added the `max-width=100%` property to the style to ensure that the image fits the display width. However, this caused the images to become deformed.
Normalize the images each time email content is loaded for display by checking their dimensions. If an image's width exceeds the allowed display width, we remove its default width and height attributes; otherwise, we leave them unchanged.
- Web:
https://github.com/user-attachments/assets/0917e9ab-1059-44bd-b6d2-d690c9838ee9
- Mobile:
[demo.webm](https://github.com/user-attachments/assets/70e38463-b37a-44ca-a9b1-8b54737834ef)
- Integration test:
[Screen_recording_20250411_140028.webm](https://github.com/user- …
> TF-3622 Fix deformed inlined image

- contact/pubspec.lock
- core/lib/core.dart
- core/lib/presentation/views/pull_to_refresh/pull_to_refresh_widget.dart
- core/pubspec.lock
- core/pubspec.yaml
- docs/adr/0058-fix-offline-cache-prevents-updating-email-query-view-on-mobile.md
- lib/features/mailbox/data/local/state_cache_manager.dart
- lib/features/mailbox_dashboard/presentation/bindings/mailbox_dashboard_bindings.dart
- lib/features/push_notification/data/local/fcm_cache_manager.dart
- lib/features/thread/data/datasource/thread_datasource.dart
- lib/features/thread/data/datasource_impl/local_thread_datasource_impl.dart
- lib/features/thread/data/datasource_impl/thread_datasource_impl.dart
- lib/features/thread/data/local/email_cache_manager.dart
- lib/features/thread/data/repository/thread_repository_impl.dart
- lib/features/thread/domain/repository/thread_repository.dart
- lib/features/thread/domain/state/clean_and_get_all_email_state.dart
- lib/features/thread/domain/usecases/clean_and_get_emails_in_mailbox_interactor.dart
- lib/features/thread/presentation/extensions/handle_pull_to_refresh_list_email_extension.dart
- lib/features/thread/presentation/thread_bindings.dart
- lib/features/thread/presentation/thread_controller.dart
- lib/features/thread/presentation/thread_view.dart
- lib/features/thread/presentation/widgets/thread_view_loading_bar_widget.dart
- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
- model/pubspec.lock
- pubspec.lock
- test/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller_test.dart
- test/features/mailbox_dashboard/presentation/view/mailbox_dashboard_view_widget_test.dart
- test/features/search/verify_before_time_in_search_email_filter_test.dart
- test/features/thread/presentation/controller/thread_controller_test.dart
#3507
- When we perform too many actions on multiple emails `(Mark as read, mark as star, move, delete, etc.)`, `Email/get` from the value of `Email/changes` will throw an error.
```json
[
"error",
{
"type": "requestTooLarge",
"description": "Too many items in an email read at level FULL. Got 183 items instead of maximum 100."
},
"c2"
]
```
- Some emails in the `update` of the `Email/change` response were not found in `Email/get`
- But we still update `newState` of email 
- Perform 2 actions when `Pull to refresh`:
- `Refresh` : Call get all emails
- `Deep refresh`: Clean email cache & call get all emails
[demo.webm](https://github.com/user-attachments/assets/5fb39309-fddd-4768-8127-fffb28ae87e5)
> TF-3507 Fix offline cache prevents updating email query view cache

- core/lib/presentation/views/html_viewer/html_content_viewer_widget.dart
- #3647 
- Flutter zoom on web view is buggy (https://github.com/pichillilorenzo/flutter_inappwebview/issues/2458, https://github.com/flutter/flutter/issues/138815)
- Even when zoomed, user cannot pan to view the content that is outside the view, as swipe action is reserved to change email.
> TF-3647 Disable email view zoom

- lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
#3656 
https://github.com/user-attachments/assets/dfe50791-83c8-4c11-a4fc-d361afa6e4cc
Do not update the `identities` list when it is `empty` or `null`
https://github.com/user-attachments/assets/5d7d6ab7-1212-4ef2-a373-2a9ae83bac57
> TF-3656 Fix still see signature is shown after delete all identity in setting

- CHANGELOG.md
- pubspec.yaml
- #3578 Blue bar: free and busy status
- #3589 Add CalendarAttendance method
- #3591 Add Calendar Counter event action
- Mobile E2E tests: forward email,
- #3501 Inlined answer mus be shown on base level
- #3601 Height Limit in webview in iOS
- Try to wrap content for text/plain
- #3487 Error handling for some cases: get email content, refreshing, get mailbox
- #3623 Duplicate confirm buttons in creating identity
- #3640 Increase composer size in case of singel composer
- #3621 Fix search return wrong result with Doesn't have 
- #3622 Display exceeded image 
- #3507 Pull to refresh to resolve missing cache in mobile
- #3647 Disable email zoom in mobile
- Handling refreshToken in composers
- #3651 Support mailto url from Openpaas
- Reply to own sent email
- #3656 Fix identities was not …
> Bump version to v0.15.2

- CHANGELOG.md
- pubspec.yaml
- #3670 Forwarding email make attachment bar disappear
- #3661 Fix memory leak for file picker
- #3674 Refactor reply email base on thunderbird logic
- Handle session in case of using isolate for Mark as Read, Empty Trash, Empty Spam
> Bump version to v0.15.3

- integration_test/exceptions/mailbox/null_inbox_unread_count_exception.dart
- integration_test/robots/mailbox_menu_robot.dart
- integration_test/scenarios/mailbox/mailbox_count_real_time_update_scenario.dart
- integration_test/tests/mailbox/mailbox_count_real_time_update_test.dart
- #3564 
```console
✅ Should see mailbox unread count update real time (integration_test/tests/mailbox/mailbox_count_real_time_update_test.dart) (19s)
Test summary:
📝 Total: 1
✅ Successful: 1
❌ Failed: 0
⏩ Skipped: 0
📊 Report: .../tmail-flutter/build/app/reports/androidTests/connected/index.html
⏱️  Duration: 38s
```
[mailbox-count-real-time-update.webm](https://github.com/user-attachments/assets/8368f8a3-bd4e-443c-ab96-7d05b481b700)
> TF-3564 E2E Mailbox count real time update

- pubspec.lock
#3684 
- According to [MDN's document](https://developer.mozilla.org/en-US/docs/Web/CSS/float), the `float` attribute changes the order of elements in html. So images set to `float: right` will float to the right and content behind it can `float` up to the edge of the image.
- Only the `Web` is affected because the new web has the feature to change `float` for images
Set `clear: both` CSS style for Signature to remove the effect of `float`. See more at [MDN-Web/CSS/clear](https://developer.mozilla.org/en-US/docs/Web/CSS/clear)
Need merged: 
- https://github.com/linagora/html-editor-enhanced/pull/53 
https://github.com/user-attachments/assets/58e94683-fafd-4264-995b-504988783160
> TF-3684 Fix signature is located in a wrong place if you move an inline image right-left

- core/lib/utils/html/html_utils.dart
- lib/main/utils/app_utils.dart
#3734 
In the `launchUrl` function of the `url_launcher` package, use `window.open(url, target, 'noopener,noreferrer')`. But due to the strict security restrictions of Safari `16.6`, adding a third parameter to the `window.open` function, such as `noopener,noreferrer` will cause Safari to limit access between windows, and in some cases, it thinks it is malicious behavior or not part of the user gesture, it will block opening a new tab.
On Safari with `version < 17`, use `html.window.open(url, '_blank');` directly without the 3rd parameter.
- Safari `v16.6`:
https://github.com/user-attachments/assets/44cefcff-c6e6-4b4a-bb8b-8cc8e144e807
- Safari `v18.1.1`:
https://github.com/user-attachments/assets/ce6889fc-e1d2-458b-bb4a-c755f09deee7
- Chrome: …
> TF-3734 Fix cannot open email as new tab on safari `v16.6`

- core/lib/presentation/views/html_viewer/html_content_viewer_on_web_widget.dart
- lib/features/email/presentation/email_view.dart
- lib/features/thread_detail/presentation/extension/get_thread_details_email_views.dart
#3644 
`HtmlElementView (iframe)` does not allow Flutter to intervene at the mouse scroll level due to platform view class limitation.
Use `JavaScript` in `iframe` to forward scroll event to `Flutter`
- Send scroll event from iframe to Flutter
- Catch message event from iframe in Flutter Web by create a `JS interop` to listen for `postMessage` from iframe
https://github.com/user-attachments/assets/329ccd5a-a3ca-454b-ab4a-c65d7cee9e72
> TF-3644 Handle scroll thread detail when cursor is in email content area

- lib/features/composer/presentation/composer_controller.dart
#3735
- Web:
https://github.com/user-attachments/assets/ade699df-3606-45fe-ba59-ecf6e8f69866
- Mobile:
https://github.com/user-attachments/assets/866ff092-67af-4f64-ad40-2e96ec11819d
> TF-3735 Add clearer warning dialog when sending message with Reply-To but no recipients

- CHANGELOG.md
- pubspec.yaml
- #3772 Change Splash screen
- #3795 Fix cannot send emails with stalwart
- #3712 Common settings for language
- #3603 Cozy app bar
- #3766 Change context menu for mobile
- #3759 Change context menu for web app
- #3763 Update style for Advanced search form
- #3767 Recent items for search history
- #3765 Change dialog style
- #3786 Add Return-Path header when request read receipt (- #3790)
- #3764 Empty view for folder
- #3758 Update Mailbox View
- #3773 Change banner of Trash/Spam folder
- #3761 Fix correct size for search icon in mailbox search
- #3752 Better error handling when updating recipients in Forwarding
- #3760 Change style of input dialog on web
- #3717 Allow access settings when own email address is null (Stalwart interopability)
- #3484 Try get oidc configuration if possible …
> Bump version to v0.16.0

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
- Apple required privacy manifest from all common used 3rd party frameworks
- Current lottie-ios version lacks privacy manifest
- https://github.com/airbnb/lottie-ios/issues/2213#issuecomment-1854431163
Update lottie-native, in turns, lottie-ios is updated
> HOTFIX Update lottie ios to have privacy manifest

- android/app/src/main/res/values-night-v31/styles.xml
- android/app/src/main/res/values-night/styles.xml
- android/app/src/main/res/values-v31/styles.xml
- android/app/src/main/res/values/styles.xml
Cursor pointer indicator in composer is wrong color on Android >= 31
Missing value `colorControlActivated` in android resource values folder. Side effect from https://github.com/linagora/tmail-flutter/pull/3788
- Android 31:
- Android 33:
> Hot fix cursor pointer indicator in composer is wrong color on Android >= 31

- lib/features/mailbox/presentation/base_mailbox_view.dart
- lib/features/mailbox/presentation/widgets/folder_widget.dart
- Web:
https://github.com/user-attachments/assets/773b6674-9e8e-489d-aa3f-a57709d23b66
- Mobile:
> [HOT] Fix incorrect `Support` folder alignment

- pubspec.lock
#3820 
The statement causing the error: `nodeEditor.insertBefore(signatureContainer, quotedMessage);`. `quotedMessage` is not a direct child of `nodeEditor`, will throw `NotFoundError`
Need merged:
- https://github.com/linagora/enough_html_editor/pull/38
- Compose email:
https://github.com/user-attachments/assets/7bd1f8d5-0926-4189-995d-6d54849d7cca
- Reply email:
https://github.com/user-attachments/assets/fd8e9511-5eb1-49d3-91ed-31797f019649
> TF-3820 Fix IOS signature is not shown after switching between identities if having a quote text

- web/index.html
[TMail load fonts from https://fonts.gstatic.com](https://www.notion.so/linagora/TMail-Load-fonts-from-https-fonts-gstatic-com-21862718bad1806ebcb2d8b26d6e9bee?source=copy_link)
Twake Mail load font from other domains:
```
https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
https://fonts.gstatic.com/s/notosanssymbols/v43/rP2up3q65FkAtHfwd-eIS2brbDN6gxP34F9jRRCe4W3gfQ8gavVFRkzrbQ.ttf
```
In our project, we do not declare any objects related to loading fonts from 
```
https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
https://fonts.gstatic.com/s/notosanssymbols/v43/rP2up3q65FkAtHfwd-eIS2brbDN6gxP34F9jRRCe4W3gfQ8gavVFRkzrbQ.ttf
```
These are the default fonts of Flutter 
Flutter web allows you to set a custom font fallback base URL via …
> Fix TMail load fonts from `https://fonts.gstatic.com`

- lib/features/composer/presentation/extensions/create_email_request_extension.dart
- lib/features/email/presentation/controller/single_email_controller.dart
- lib/features/manage_account/presentation/language_and_region/language_and_region_controller.dart
- lib/main.dart
- lib/main/localizations/localization_service.dart
#3885
https://github.com/user-attachments/assets/6520c2e4-4fc3-4121-800d-0c06b18dfc4c
Since device local returns a Locale without `countryCode` so the test condition `supportedLocales.contains(deviceLocale)` returns `false` resulting in the default locale `en` being used
https://github.com/linagora/tmail-flutter/blob/78cb93ef1cbbd47959f1207e35d7b145efc05f6c/lib/main/localizations/localization_service.dart#L97-L102
- When server & cached locale is NULL
https://github.com/user-attachments/assets/5ea48f15-c0d3-4329-bd40-6a2b126b2f92
- When server & cached locale is not NULL
https://github.com/user-attachments/assets/667fa9ed-e421-4be2-9c6e-beb4e697a93a
> TF-3885 Fix language defaults

- lib/l10n/intl_messages.arb
- lib/main/localizations/app_localizations.dart
When run command 
`dart run intl_generator:extract_to_arb --output-dir=./lib/l10n lib/main/localizations/app_localizations.dart `
get error message
```console
Skipping invalid Intl.message invocation
<Intl.plural(days, zero: '', one: ' (1 day ago)', other: ' ($days days ago)')>
reason: The 'args' argument for Intl.message must be specified for messages with parameters. Consider using rewrite_intl_messages.dart
from lib/main/localizations/app_localizations.dart    line: 4842, column: 12
```
https://github.com/user-attachments/assets/a583fff7-2abf-442e-a4f6-7a8c1a8154d4
> [HOT] Fix missing `name` and `args` to `Intl.plural` in `daysAgo`

- lib/features/composer/presentation/composer_view.dart
#3889
[reproduce.webm](https://github.com/user-attachments/assets/e33321a3-c143-410a-8700-329c345ff232)
Because we have created GlobalKey `headerEditorMobileWidgetKey` to calculate the height of the fields on the editor (`From, To, Cc, Bcc, Subject,..)`. But we have not assigned it on the view side, so the result is that it cannot be calculated, leading to not being able to jump to the correct cursor position.
- Android:
[demo.webm](https://github.com/user-attachments/assets/1a39caee-eeeb-4970-862e-2e41de0398a5)
- iOS:
https://github.com/user-attachments/assets/2efb9bf8-efd0-4f26-81f4-e22558071e2f
> TF-3889 Fix cannot see input when typing email body with attachments on mobile

- core/lib/core.dart
- core/lib/utils/mail/named_address.dart
- core/lib/utils/string_convert.dart
- core/test/utils/string_convert_test.dart
- lib/features/base/extensions/handle_mailbox_action_type_extension.dart
- lib/features/composer/presentation/extensions/auto_create_tag_for_recipients_extension.dart
- lib/features/composer/presentation/extensions/list_address_extension.dart
- lib/features/composer/presentation/extensions/list_named_address_extension.dart
- lib/features/composer/presentation/extensions/named_address_extension.dart
- lib/features/composer/presentation/widgets/recipient_composer_widget.dart
- model/lib/extensions/list_email_address_extension.dart
- test/features/composer/presentation/extensions/list_address_extension_test.dart
- test/features/composer/presentation/extensions/list_named_address_extension_test.dart
- test/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller_test.dart
#3864 
https://github.com/user-attachments/assets/c3c40dec-391d-4b0d-9d04-8b565af36989
> TF-3864 Support pasting address with display name
